### ISSUE TITLE
Configure listen IP

### ISSUE THREAD

**Issue by dani** [gotenberg/gotenberg#1008]
For now, we can only set --api-port (or via the env var), but this only allows to set the port, not the listen IP, and gotenberg always listen on 0.0.0.0.
It'd be useful to configure the IP on which the API listen. One use case I have is running gotenberg on a Nomad cluster, and exposing it through the Consul service mesh. When using the mesh, all the security relies on the fact that services are only listening on 127.0.0.1, so they can be accessed though an envoy proxy in the same allocation (= pod in Nomad's terminology).
With gotenberg listening on 0.0.0.0, random other workloads which are happening to run on the same host can access gotenberg, bypassing the service mesh, and the ACL applied by the mesh.

**Comment by gulien** [comment]
Hey @dani,

I don't explicitly set the listening IP to 0.0.0.0, so my guess is it's either a Docker or a Nomad thing.
For instance, inside a Gotenberg container:

```bash
gotenberg@754c0b078bb3:~$ curl localhost:3000/health
{"status":"up","details":{"chromium":{"status":"up","timestamp":"2024-10-07T12:21:24.86165338Z"},"libreoffice":{"status":"up","timestamp":"2024-10-07T12:21:24.86166488Z"}}}
```

**Comment by dani** [comment]
Of course it'll respond if you call localhost. But there's no way to restrict it to localhost.
```
root@0ae90e014b64:/home/gotenberg# netstat -laputen
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name    
tcp6       0      0 :::3000                 :::*                    LISTEN      1001       4881268    -                   
root@0ae90e014b64:/home/gotenberg#

**Comment by dani** [comment]
I don't think there's a lot of usecase where you'd want to restrict to a specific IP, which wouldn't be 127.0.0.1, but IMHO `--api-ip` is more aligned with the existing `--api-port` setting.

**Comment by gulien** [comment]
Yep, it's just for a maintainer perspective, I will have to check for the validity of the provided IP, while the `—api-restrict-to-localhost` flag is just me setting the ip to `127.0.0.1` 😄

**Comment by dani** [comment]
Ah OK :-)
Well, anyway, I'm fine with either option, as in my case, I'm just interested in restricting to localhost

**Comment by gulien** [comment]
@dani could you test `gotenberg/snapshot:featapi-restrict-to-localhost` and tells me if it works as expected?

Usage: new flag `--api-restrict-ip-to-localhost=true|false` (false by default).

**Comment by dani** [comment]
Working as expected :+1:

**Comment by gulien** [comment]
@dani thanks for the suggestion!

I've opted for the flag `--api-bind-ip`, which set the IP address the API should bind to for incoming connections. An empty value results to the same behavior as you mentioned in your issue, but, in your case, you can set it to localhost with `--api-bind-ip=127.0.0.1`.

The image `gotenberg/gotenberg:edge` should be available within ~1 hour with this feature. I plan to release a new version of Gotenberg by the end of the week 😉
