### ISSUE TITLE
Images Fail to Load on /convert/url Endpoint Due to Authentication Headers Rejected by CDNs

### ISSUE THREAD

**Issue by forg002-ctrl** [gotenberg/gotenberg#1011]
I noticed that when I send a request to the **_/convert/url_** endpoint with the following data:
```
{
  { “extraHeaders”: { “Authentication”: “Basic base64data” }
}
```
Some images, selected randomly each time, do not load. I believe this is because Gotenberg sends authentication headers for each frontend request, and some CDN servers reject these headers, especially the **_Authentication_** header. This seems to be the reason why some images are not loading.
I ran into a similar problem using the Puppeteer npm package, but **_Puppeteer_** offers an async method **_page.authenticate_** that handles authentication by acting like a native browser passing basic authentication. The authentication header is not sent along with the FE request to the third-party APIs (loading images for display).
Do you have any suggestions or solutions to help with this issue?

**Comment by gulien** [comment]
Hey @forg002-ctrl 👋 

Looks like its the same issue as mentioned in #993 by @valerian-martin-tbc!

Indeed, Gotenberg sends the extra HTTP headers for each frontend request. As a workaround, for now, you may use cookie authentication as an alternative (if possible).

But that's definitely a feature I could implement.

**Comment by gulien** [comment]
@forg002-ctrl `gotenberg/snapshot:featchromium-authenticate` is available with two new form fields:

1. `basicAuthenticationUsername`
2. `basicAuthenticationPassword`

It set the credentials only for the main page, not each frontend request.

**Comment by forg002-ctrl** [comment]
Hi @gulien,

I've tested using the new form settings and we're getting a connection timeout when doing the request:
  curl -u NoTest:Test \
  --request POST http://localhost:3000/forms/chromium/convert/url \
  --form 'url=https://headers.4tools.net' \
  --form 'basicAuthenticationUsername=$Username' \
  --form 'basicAuthenticationPassword=$Password' \
  -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" -o print.pdf && open print.pdf

Can you please let me know what am I doing wrong?

**Comment by OsoianMarcel** [comment]
Hello @gulien,

The issue we're facing isn't related to a connection timeout, but rather the absence of the Authorization header in requests.

To reproduce: 

1. Run the snapshot image:
```bash
docker run --rm --network=host gotenberg/snapshot:featchromium-authenticate gotenberg --api-port=3002
```

2. Generate a PDF of the page https://headers.4tools.net/ to inspect the headers (with basicAuthenticationUsername & basicAuthenticationPassword set).
```bash
curl --request POST http://localhost:3002/forms/chromium/convert/url \
  --form 'url=https://headers.4tools.net' \
  --form 'basicAuthenticationUsername=user' \
  --form 'basicAuthenticationPassword=pass' \
  -o print.pdf && open print.pdf
```

These are the headers sent by Chrome within the Gotenberg container:

```
Host: headers.4tools.net
sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
upgrade-insecure-requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/129.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-
exchange;v=b3;q=0.7
sec-fetch-site: none
sec-fetch-mode: navigate
sec-fetch-user: ?1
sec-fetch-dest: document
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9
priority: u=0, i
Cookie: _pk_id.22.d373=2a1979dc97b41ee7.1728463187.; _pk_ses.22.d373=1
```

The **Authorization** header is missing, even though the basic authentication credentials are provided.

Could you please advise on how to ensure the Authorization header is included?

**Comment by gulien** [comment]
Hello @OsoianMarcel,

I cannot make it work with the URL you povided (keep getting a "Please Wait" PDF).

However, it is working as expected with the URL https://authenticationtest.com/HTTPAuth/.

If the form fields are not provided, it fails, while they are provided the page is working as expected.

Make sure to download the latest version of `gotenberg/snapshot:featchromium-authenticate` (docker pull).

**Comment by OsoianMarcel** [comment]
@gulien,

I tested with the URL https://authenticationtest.com/HTTPAuth, and it works as expected.
I also re-tested on https://headers.4tools.net, and the Authorization headers appeared.

We also applied the snapshot image to our staging environment, and it looks like the issue with images has been resolved.

We'll continue testing for another hour, and if everything looks good, we will let you know.
If you'll be able to create a new release, that would be great. 

Thank you.

**Comment by gulien** [comment]
I can create a new release once your testing is done!

**Comment by forg002-ctrl** [comment]
@gulien 

We ran into a problem, when we make a request, the basic authentication only goes through for the document file "index.html" file(200 http response status), but all other page resources(css, js files) get a 401 error - so the page isn't loaded and the error is occurred.
We have checked this in the nginx logs.

**Comment by gulien** [comment]
Yep, it only works for the main page for now 🤔

**Comment by gulien** [comment]
An alternative solution could be to scope the extra HTTP headers to specific domains.

**Comment by forg002-ctrl** [comment]
> An alternative solution could be to scope the extra HTTP headers to specific domains.

Let's try.

**Comment by OsoianMarcel** [comment]
> @gulien,
> 
> I tested with the URL https://authenticationtest.com/HTTPAuth, and it works as expected. I also re-tested on https://headers.4tools.net, and the Authorization headers appeared.
> 
> We also applied the snapshot image to our staging environment, and it looks like the issue with images has been resolved.
> 
> We'll continue testing for another hour, and if everything looks good, we will let you know. If you'll be able to create a new release, that would be great.
> 
> Thank you.

I just want to clarify why I initially said that it worked before: This was because my first request used **extraHeaders**, which caused the assets to be cached. So, when I tested again using basicAuthenticationUsername and basicAuthenticationPassword, it seemed to work because all the assets were already cached.

**Comment by gulien** [comment]
@OsoianMarcel @forg002-ctrl 

Newer version of `gotenberg/snapshot:featchromium-authenticate` now supports an optional *scope* token:

```
curl --request POST \
--url http://localhost:3000/forms/chromium/convert/url \
--header 'content-type: multipart/form-data' \
--form url=https://authenticationtest.com/HTTPAuth/ \
--form 'extraHttpHeaders={"Authorization":"Basic dXNlcjpwYXNz;scope=https?:\\/\\/([a-zA-Z0-9-]+\\.)*authenticationtest\\.com\\/.*"}'
```

It accepts a valid regex pattern.

**Comment by forg002-ctrl** [comment]
I made everything, like you've described, but nothing works. Can you take a look please?
![image](https://github.com/user-attachments/assets/16b7fa0a-751b-49bf-8cf3-a9cb3d1e8851)

**Comment by gulien** [comment]
I think bash is interpreting wrongly the regex 🤔 
But from your code or postman equivalent it should work as expected.

**Comment by gulien** [comment]
@forg002-ctrl  Ok so I've found a working solution lol:

```
curl --request POST \
--url http://localhost:3000/forms/chromium/convert/url \
--header 'content-type: multipart/form-data' \
--form url=https://authenticationtest.com/HTTPAuth/ \
--form-string 'extraHttpHeaders={"Authorization":"Basic dXNlcjpwYXNz;scope=https?:\\/\\/([a-zA-Z0-9-]+\\.)*authenticationtest\\.com\\/.*"}'
```

Notice `--form` vs `--form-string` 😄

**Comment by gulien** [comment]
If its works for you, I can release a version today 😉

**Comment by forg002-ctrl** [comment]
@gulien Thank you very much for your work, we appreciate it. It would be great if you would release this version.
