### ISSUE TITLE
Feature request : start page numbering at a defined offset in convert routes

### ISSUE THREAD

**Issue by KojoEnch** [gotenberg/gotenberg#1016]
In https://github.com/gotenberg/gotenberg/issues/964, I exposed an issue with page numbering :

> In order to generate a PDF with a different header for each chapter, we first generate partial PDFs and then merge them. The issue is that page numbering in the merged footer keeps the inherited numbering, i.e. restarting at 1 for each chapter.

Given there's no obvious way to fix it while merging, I'm opening this new issue to suggest another approach. 
Since the PDF is built step by step, we could recursively : 
- convert a chapter to PDF
- then get the total pages of that chapter (for instance reading  _PageCount_ from `/forms/pdfengines/metadata/read`)
- finally pass this total as, for instance, a `startPageNumberingAt` form field to the [convert Route](https://gotenberg.dev/docs/routes#convert-with-chromium) when converting the next chapter.

Do you think something like that could be achieved ?
Thank you !

**Comment by KojoEnch** [comment]
Hello @gulien :wave: 

> I don’t know how to target specifically the footer. It also depends on the structure of the PDF I guess (afaik footers are not a standardized element of a PDF).

Maybe my explanation was confusing ? My idea is that the property `startPageNumberingAt` would be passed to the convert route, and the API doesn't deal with a PDF at this stage. 
I'd say  the issue is _how to force Chromium to deal with a page numbering offset_ instead ? 

I tried to understand how things work there, even if I don't know C++. If I target the correct repo, the stack might be something like this.

In [print_header_footer_template_page.html](https://source.chromium.org/chromium/chromium/src/+/main:components/printing/resources/print_header_footer_template_page.html) , we have : 
```
  for (const cssClass of ['date', 'title', 'url', 'pageNumber', 'totalPages']) {
    for (const element of document.querySelectorAll(`.${cssClass}`)) {
      element.textContent = options[cssClass];
    }
  }
```
where **options** are an argument of the function `setupHeaderFooterTemplate`, called by [kPageSetupScriptFormat](https://source.chromium.org/chromium/chromium/src/+/main:components/printing/renderer/print_render_frame_helper.cc;drc=f553eb815cb85eea6e8788611460840a825ad3ca;bpv=1;bpt=1;l=128?gsn=kPageSetupScriptFormat&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fchromium.googlesource.com%2Fcodesearch%2Fchromium%2Fsrc%2F%2Fmain%3Flang%3Dc%252B%252B%3Fpath%3Dcomponents%2Fprinting%2Frenderer%2Fprint_render_frame_helper.cc%23Y_WnNSSJOc52MMzJccFF82zvtWV_B5B_jGvCN5yy--4) : `const char kPageSetupScriptFormat[] = "setupHeaderFooterTemplate(%s);";`

From my nullish understanding of C++, the placeholder is set [here](https://source.chromium.org/chromium/chromium/src/+/main:components/printing/renderer/print_render_frame_helper.cc;drc=5a02fc6cdee77d0a39e9c43a4c2a29bbccc88852;l=180?q=setupHeaderFooterTemplate&ss=chromium) : `ExecuteScript(&frame, kPageSetupScriptFormat, base::Value(std::move(options))); `

A few lines above, we have : 
```
  options.Set("pageNumber", base::checked_cast<int>(page_index + 1));
  options.Set("totalPages", base::checked_cast<int>(total_pages));
```
leading to [PrintHeaderAndFooter](https://source.chromium.org/chromium/chromium/src/+/main:components/printing/renderer/print_render_frame_helper.cc;drc=5a02fc6cdee77d0a39e9c43a4c2a29bbccc88852;l=2545) 

Then I lose the stack trace. Maybe if you get the point, you'd find the glue  to set this `page_index` variable from your [pfdOptions](https://github.com/gotenberg/gotenberg/blob/main/pkg/modules/chromium/routes.go#L208C2-L208C12)  ?

I won't be offended if you make fun of this attempt though. :laughing:

**Comment by gulien** [comment]
Hey @KojoEnch,

No worries, I'm not here to judge 😄 

Gotenberg does not compile Chromium itself, and I don't think it's worth the hassle for such customization.

I think the best option for you would be to create the footer "by hand", i.e., by using dedicated CSS rules:

* https://www.w3.org/TR/WD-CSS2-971104/page.html#h-12.3.6
* https://www.geeksforgeeks.org/how-to-print-header-and-footer-on-every-printed-page-of-a-document-in-css/

Plus some JavaScript to detect the current page (maybe paged.js?).

**Comment by KojoEnch** [comment]
Thanks for your insights.

BTW, I never thought you'd compile Chromium itself, I was just trying to get the full picture of Chromium page numbering process when converting to PDF. 
And I believed you could maybe find which new argument, such as PageNumber, could be sent along with the other [Page Properties](https://gotenberg.dev/docs/routes#page-properties-chromium)... :slightly_smiling_face: 

Anyway, I effectively ended up with a few lines of dynamic CSS, using [Margin at-rules](https://developer.mozilla.org/en-US/docs/Web/CSS/@page#margin_at-rules) draft feature  + the Paged.js polyfill to emulate these rules.

I'll share below the essential lines of a working solution, since it seems to be still, in 2024, a tricky feature.

Add the following lines to the head of the HTML or Twig template you want to convert :
```
    <head>
        <script src="https://unpkg.com/pagedjs/dist/paged.polyfill.js"></script>
        <style>
            @media print {
                @page:first {
                }
                @page {
                    counter-increment: page;
                    margin-bottom: 2cm;
                    @bottom-right {
                        content: "#" counter(page);
                        margin-bottom: 14px;
                        text-align: right;
                        vertical-align: bottom;
                    }
                }
            }
        </style>
    </head>
```
Then recursively : 

- convert the first HTML chapter to PDF, with its own header
- grab the PageCount value from its metadata through `POST /forms/pdfengines/metadata/read` route
- write a temporary copy of the next HTML chapter, in which you add the `property counter-set: page N` to `@page:first{}`, where N is the computed first page number of the current chapter (eg. PageCount value + 1 for the second chapter)
- convert the temp copy to PDF, with another header
- ... and so on
- once you get all your chapters converted, merge [them](https://gotenberg.dev/docs/routes#merge-pdfs-route).

The final PDF will have a different header for each chapter, along with a coherent page numbering from 1 to page total.

Thanks for your reactivity and open mindset.

**Comment by gulien** [comment]
Thanks for the feedback @KojoEnch! I hope it will help others!
