### ISSUE TITLE
use of in memory file system

### ISSUE THREAD

**Issue by Simplici** [gotenberg/gotenberg#102]
when we do office file conversion, I guess that there are disk I/O activities.
I think of using a in memory file system like(tmpfs) for following reasons:

1. better performance
2. no document will be stored on disk in any moment

Is this possible and how should I do it?

Thanks in advance.

**Comment by gulien** [comment]
Hello @Simplici 

Indeed there is some I/O activities.
I guess it should be possible to use in memory file system - dunno how to though.

**Comment by tobwen** [comment]
Docker and Podman can do `tmpfs`: https://docs.docker.com/storage/tmpfs/

I've got tons of SVGs, which are needed inside my FODTs. I'm mounting them on `tmpfs`.
