### ISSUE TITLE
Feature: Have gotenberg as a go lib

### ISSUE THREAD

**Issue by ioprea** [gotenberg/gotenberg#1029]
It would be really great to be able to use gotenberg from another go service directly instead of calling the api.

**Comment by dcaraxes** [comment]
Client libraries are used for this purpose. I have just completely updated the client to fully support Gutenberg 8.x, so you can safely use it if this option suits you.

https://github.com/dcaraxes/gotenberg-go-client

**Comment by dcaraxes** [comment]
> It would be really great to be able to use gotenberg from another go service directly instead of calling the api.

Client libraries are used for this purpose. I have just completely updated the Go client to fully support Gotenberg 8.x, so you can safely use it if this option suits you - https://github.com/dcaraxes/gotenberg-go-client

There are clients for other languages in the list https://github.com/gotenberg/awesome-gotenberg

**Comment by sushiltechnex** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by gulien** [comment]
Hello @ioprea,

Gotenberg makes sense as a whole, and I don't want to maintain a library too 😄
