### ISSUE TITLE
Image broken when converting a docx having png image

### ISSUE THREAD

**Issue by HoangViet144** [gotenberg/gotenberg#1030]
We have a word file containing a png image, like this: 
![image](https://github.com/user-attachments/assets/2e588264-0d04-4e8f-b322-ca5b7fa02798)
However, after calling convert to pdf using libreoffice, the image is broken 
![image](https://github.com/user-attachments/assets/47343295-c317-4c8e-9f7a-c0acab8c6a2e)
This issue happened in gotenberg >= 8.8.1

Example curl request
```
curl --location 'https://my-gotenberg/forms/libreoffice/convert' \
--form 'files=@"/file_test.docx"' \
--form 'pdfa="PDF/A-1b"'
```

**Comment by sushiltechnex** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by gulien** [comment]
Hello @HoangViet144,

Does it work with `losslessImageCompression=true`?
