### ISSUE TITLE
Container has to be restarted every day

### ISSUE THREAD

**Issue by vrcompugo** [gotenberg/gotenberg#1032]
Since a couple of day we are facing the issue that the container of Gotenberg has to be restarted at least every day.
Sometimes the PDF creation does not work (lately every day).

At the moment we are reatarting the container frequently, but something seems not to be working correctly.

**Comment by gulien** [comment]
Hello @vrcompugo 👋

Are you using the health check ?

**Comment by vrcompugo** [comment]
Hi @gulien,
what exactly is the health check and how can I use it?

**Comment by gulien** [comment]
Your orchestrator (Docker Compose, Kubernetes, etc.) should have an health check feature that regularly calls a given URL (`GET /health` for Gotenberg) and  automatically restarts the container if the answer is not *200 OK*.

**Comment by dcaraxes** [comment]
> Hi @gulien, what exactly is the health check and how can I use it?

Health check is a separate route to Gotenberg. https://gotenberg.dev/docs/routes#health-check-route

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by sushiltechnex** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
