### ISSUE TITLE
Use different proxy servers for different requests

### ISSUE THREAD

**Issue by sokolnikov911** [gotenberg/gotenberg#1037]
Hello there. 

I have a list of proxy servers, and I want to use different proxy servers for different URLs. 
I see [here the MR](https://github.com/gotenberg/gotenberg/issues/376) about the `--chromium-proxy-server` flag. But as I understand, specifying this flag I can configure the proxy server address on the container launching step only. So all requests will go through this proxy. 

But if  I want to use different proxy servers for different URLs. Is it possible to specify the proxy server address in the POST form field? In this case it will be much more flexible. 

Thank you.

**Comment by gulien** [comment]
Hello @sokolnikov911,

I'm currently relying on a Chromium flag to enable this behavior, but I don't see a native solution with the Chrome DevTool Protocol for a specific proxy server per page.

I could implement a custom solution like https://github.com/gajus/puppeteer-proxy, but that's way more complex 🫤
