### ISSUE TITLE
First request is very slow compared to the next ones

### ISSUE THREAD

**Issue by arenier** [gotenberg/gotenberg#1047]
Hello there,

We use Gotenberg in production and it's working pretty well, we used to call the service through a worker to generate some kind of transcripts on demand, soooo we had no need for fast response.

We have implemented a new feature to download a PDF of this transcript and we detected some kind of strange behavior. First call takes around 30sec, the next ones takes 10x less time (around 3sec). 

We use the endpoint `POST /forms/chromium/convert/html`. Memory request has no impact on this, we tried to increase the memory request.

```
{"bytes_in":-1, "bytes_out":194773, "host":"gotenberg-svc.didaskill:3000", "latency":2.7139176603E10, "latency_human":"27.139176603s", "level":"info", "logger":"api", "method":"POST", "msg":"request handled", "path":"/forms/chromium/convert/html", "referer":"", "remote_ip":"192.168.2.152", "status":200, "trace":"e5bfbe59-363e-4601-b0e1-790f331dccd9", "ts":1.7320954988550153E9, "uri":"/forms/chromium/convert/html", "user_agent":""}
{"bytes_in":-1, "bytes_out":183087, "host":"gotenberg-svc.whatever:3000", "latency":4.430455622E9, "latency_human":"4.430455622s", "level":"info", "logger":"api", "method":"POST", "msg":"request handled", "path":"/forms/chromium/convert/html", "referer":"", "remote_ip":"192.168.2.152", "status":200, "trace":"d87a0a79-5daf-4ac0-bb69-f4b49408052e", "ts":1.7320957554230387E9, "uri":"/forms/chromium/convert/html", "user_agent":""}
{"bytes_in":-1, "bytes_out":174220, "host":"gotenberg-svc.whatever:3000", "latency":2.350850278E9, "latency_human":"2.350850278s", "level":"info", "logger":"api", "method":"POST", "msg":"request handled", "path":"/forms/chromium/convert/html", "referer":"", "remote_ip":"192.168.0.93", "status":200, "trace":"9abb7ed0-df8d-42fc-911c-6dc3e109b6f7", "ts":1.7320958769829226E9, "uri":"/forms/chromium/convert/html", "user_agent":""}
```
Is there any inner behavior of Gotenberg which could justify this and we should know ?

**Comment by gulien** [comment]
Hey @arenier 👋 

If it’s a new instance, using `--chromium-auto-start` will help reduce this delay.

**Comment by arenier** [comment]
Hey @gulien 

Thanks for the quick answer, we are going to implement this option :)

**Comment by spegghy69** [comment]
Hello @arenier did you solve ? I have the same problem
