### ISSUE TITLE
Keywords field in metadata payload does not work as expected

### ISSUE THREAD

**Issue by ABAG603** [gotenberg/gotenberg#1048]
Hi,

Just want to understand if Keywords are actually working when adding metadata to a pdf. As soon as metadata payload has Keywords field and it is an array conversion fails with:

````
{"level":"error","ts":1732175616.8494515,"logger":"api","msg":"convert URL to PDF: write metadata: write PDF metadata with multi PDF engines: write PDF metadata with ExifTool: metadata value not supported","trace":"250a6686-d500-48e8-8dc7-c73c0c2ea97c","remote_ip":"192.168.65.1","host":"localhost:7001","uri":"/forms/chromium/convert/url","method":"POST","path":"/forms/chromium/convert/url","referer":"","user_agent":"curl/8.7.1","status":400,"latency":11249156047,"latency_human":"11.249156047s","bytes_in":793,"bytes_out":126
````

Originally, I thought it's a problem with the payload I'm sending, but then I tried one from the official docs and result is the same. Here's the one I used (from the docs)
````
--form 'metadata={"Author":"Julien Neuhart","Copyright":"Julien Neuhart","CreationDate":"2006-09-18T16:27:50-04:00","Creator":"Gotenberg","Keywords":["first","second"],"Marked":true,"ModDate":"2006-09-18T16:27:50-04:00","PDFVersion":1.7,"Producer":"Gotenberg","Subject":"Sample","Title":"Sample","Trapped":"Unknown"}'
````

Route I'm using is /forms/chromium/convert/url

**Comment by gulien** [comment]
Hey @ABAG603 👋 

Thanks for the heads up! It has been fixed in https://github.com/gotenberg/gotenberg/commit/1b49b35365fdeab773de47261ce1cb5d9f837e2e.

I'll release a new version ASAP.

**Comment by gulien** [comment]
Version `8.14.1` should be available within ~1 hour.

**Comment by ABAG603** [comment]
@gulien  thanks, that was fast. Just to confirm - new Docker image as well in about 1 hour?

**Comment by gulien** [comment]
Yep, the build process takes around 1 hour 😄

**Comment by gulien** [comment]
You can check the progression here: https://github.com/gotenberg/gotenberg/actions/runs/11949860987

**Comment by ABAG603** [comment]
@gulien it works now, thanks. 

However, for the metadata payload below
````json
{"Subject":"test","Keywords":["report","performance"]}
````

Keywords are actually generated as:
````
"report, performance"; test
````

- there are quotes around values provided as keywords
- Subject is added to keywords

Is this by design?

**Comment by gulien** [comment]
@ABAG603 what does the route `POST /forms/pdfengines/metadata/read` tells you? 🤔 

In my case, it works as expected:

```json
{
  "write.pdf": {
    "CreateDate": "2018:12:06 17:50:06+00:00",
    "Creator": "Chromium",
    "Directory": "/tmp/3582ed23-e5f5-4a28-a7be-dbef28aec8b6/2b3e6390-a0aa-4b0c-8ccf-fc53ab1bed4e",
    "ExifToolVersion": 12.57,
    "FileAccessDate": "2024:11:21 12:39:46+00:00",
    "FileInodeChangeDate": "2024:11:21 12:39:46+00:00",
    "FileModifyDate": "2024:11:21 12:39:46+00:00",
    "FileName": "write.pdf",
    "FilePermissions": "-rw-r--r--",
    "FileSize": "212 kB",
    "FileType": "PDF",
    "FileTypeExtension": "pdf",
    "Keywords": [
      "report",
      "performance"
    ],
    "Linearized": "No",
    "MIMEType": "application/pdf",
    "ModifyDate": "2018:12:06 17:50:06+00:00",
    "PDFVersion": 1.4,
    "PageCount": 3,
    "Producer": "Skia/PDF m70",
    "SourceFile": "/tmp/3582ed23-e5f5-4a28-a7be-dbef28aec8b6/2b3e6390-a0aa-4b0c-8ccf-fc53ab1bed4e/write.pdf",
    "Subject": "test",
    "XMPToolkit": "Image::ExifTool 12.57"
  }
}
```

**Comment by gulien** [comment]
Not sure I can do much here. ExifTool is doing the heavy lifting here, and it correctly returns the metadata as specified in the write URL 🫤
