### ISSUE TITLE
Screenshot device size is ignored

### ISSUE THREAD

**Issue by Tera** [gotenberg/gotenberg#1051]
Hi

I'm using latest gotenberg version 8.14.0 deployed on Cloudrun.

I'm trying to produce a jpeg using the screenshot function with a specific image width and height (1280*800)
the HTML I'm sending is responsive and I've attached it. I'm performing this CURL call:

`curl --location 'https://demo.gotenberg.dev/forms/chromium/screenshot/html' \
--form 'files=@"/Users/stefanomassera/Downloads/index.html"' \
--form 'format="jpeg"' \
--form 'quality="100"' \
--form 'width="800"' \
--form 'height="600"' \
--form 'optimizeForSpeed="true"' \
--form 'emulatedMediaType="screen"'`

[index-html.txt](https://github.com/user-attachments/files/17844605/index-html.txt) I've renamed the .HTML into .txt to upload it

The image that is generated is always  3179px*2245px instead of 800*600

It seems that the device size is completely ignored during the image creation.

If I add `clip=true` parameter the image is correctly 800*600 but, of course, it is clipped and that's not what I want, I expected that the screen size parameters would be honoured and the generated image would have the same resolution.

How can I generate an 800*600 image?

Thanks a lot

**Comment by gulien** [comment]
Hey @Tera 👋,

By default, we override the [device screen dimensions](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride):

> Overrides the values of device screen dimensions (window.screen.width, window.screen.height, window.innerWidth, window.innerHeight, and "device-width"/"device-height"-related CSS media query results). 

If you change the `width` value, it outputs a wider (or narrower) screenshot.

When `clip` is set to *true*,  its another functionality of the ChromeDevTools protocol that tells Chromium to only take the given region as a screenshot.

No much I can do here, alas 😄
