### ISSUE TITLE
Generated PDF sizes with v8.x are ~2-3x larger than same generated PDF on v7.x

### ISSUE THREAD

**Issue by RomainTFasst** [gotenberg/gotenberg#1067]
Hi,
When wanting to migrate from v7 to v8, we noticed that a PDF document generated on v8 was 2 to 3 times heavier than the same one generated with v7. We use the endpoint `forms/chromium/convert/html`. 

This case is easily reproducible by instantiating a docker container for each version, we used these image versions: 
`gotenberg/gotenberg:7.10.2`
`gotenberg/gotenberg:8.10.0`

With our html, the PDF in v7 has a size of 286kb, whereas 795kb in v8.

Why such a difference?

Thanks.

**Comment by gulien** [comment]
Hey @RomainTFasst 

I think it’s related to #1058. Does it happens with version `8.9.1`?

**Comment by RomainTFasst** [comment]
Hi, no it doesn't, the PDF siize is globally the same as v7.10 with v8.9.1.
Is this issue will be corrected in future version?
Thanks.

**Comment by gulien** [comment]
Nothing much I can do, looks like an issue with Chromium 🫤

**Comment by RomainTFasst** [comment]
OK, thanks for your feedback!
