### ISSUE TITLE
How should I handle the splitting by pages of a PDF file? 

### ISSUE THREAD

**Issue by starwalkn** [gotenberg/gotenberg#1086]
Does Gotenberg return multiple files if a single name foo.pdf is specified as Gotenberg-Output-Filename? Or is it necessary to save to a zip file if only single file saving is supported on the client side?

I got the question after I saw that the documentation specifies the file extension as PDF, not ZIP, but at the same time Gotenberg comes with ContentType: application/zip:

```
curl \
--request POST http://localhost:3000/forms/libreoffice/convert \
--form files=@/path/to/file.docx \
--form splitMode=pages \
--form splitSpan=1-2 \
--form splitUnify=true \
-o my.pdf
```

**Comment by gulien** [comment]
It really depends if there is only one resulting PDF or many.

In your example, with `splitUnify` = *true*, it will create a single PDF with the selected page range. If you send more than one document, it will output as many PDFs as documents.

**Comment by starwalkn** [comment]
Yes, indeed, I managed to check all the options with the tests. Thank you!
