### ISSUE TITLE
What has changed for PDF/A and PDF/UA in 8.15.0?

### ISSUE THREAD

**Issue by starwalkn** [gotenberg/gotenberg#1087]
Are there any changes in version 8.15.0 that affect the generation of PDF/A and PDF/UA files? After the update tests for pdfaid:part and pdfuaid:part lines in such files stopped passing.

**Comment by gulien** [comment]
Hey @starwalkn 👋 

I did not touch anything regarding PDF/A and PDF/UA 🤔 Is it directly via the `/forms/pdfengines/convert` route?

**Comment by starwalkn** [comment]
> Hey @starwalkn 👋
> 
> I did not touch anything regarding PDF/A and PDF/UA 🤔 Is it directly via the `/forms/pdfengines/convert` route?

No, this is a /forms/chromium/html/convert request with a pdfua form field added.

**Comment by gulien** [comment]
I've introduced a bug indeed, thanks for the heads up!

**Comment by gulien** [comment]
It is fixed by https://github.com/gotenberg/gotenberg/commit/16807bd57fcc7235c0b7e65896de17a2b1d90df3!

I'll release a new version soon! Thanks again!
