### ISSUE TITLE
HTML documents: capture screenshot

### ISSUE THREAD

**Issue by smatyas** [gotenberg/gotenberg#110]
Hi,

I know that this project is about converting different documents to PDF, so maybe it's a long shot, but since you built a great API, I'd really love to use it to capture screenshot of web pages as well, it would be a nice enhancement ;)

I was thinking about using the same endpoints but using different headers, so it would be transparent.

I.e. we could use `Accept: image/png` to let the API know that we want a screenshot.
We could also add custom headers to drive the width/height.

```
$ curl --request POST \
    --url http://localhost:3000/convert/html \
    --header 'Content-Type: multipart/form-data' \
    --header 'Accept: image/png' \
    --header 'Screenshot-width: 800' \
    --header 'Screenshot-height: 600' \
    --form files=@index.html \
    -o result.png
```

I don't know golang so well, but I looked into the `internal/pkg/printer/chrome.go` file, and it seems to be feasible to call `targetClient.Page.CaptureScreenshot(...)` depending on some new options.

What do you think? Would you even consider this feature? (I totally understand if not.)
I can even try to contribute if we can agree on the details.

**Comment by gulien** [comment]
Hello @smatyas 

Thank you for your interest 😄 unfortunately, I prefer to stick to PDF 👍

**Comment by dyorgio** [comment]
Hi @gulien, I tried to use gotenberg to render some dashboards, and have serious issues in rendering... maybe support screenshot output (inside a pdf) will be a good addition ;).

**Comment by umamaistempo** [comment]
Hey there. What if we supported a new endpoint that would use `CaptureScreenshot` to produce page previews/thumbnails ?

That would not deviate Gotenberg from its purpose but would support more use cases. WDYT ?

**Comment by gulien** [comment]
Hello @dyorgio and @umamaistempo,

I'll consider it for v7 :)

**Comment by JacoBezuidenhout** [comment]
Hi Gulien! Awesome project! Thanks a lot!! 

Just posting a +1 on this feature...

**Comment by WilliamGorge** [comment]
this has been implemented here: https://github.com/gotenberg/gotenberg/pull/504 🙏 review

**Comment by gulien** [comment]
Available in v8.
