### ISSUE TITLE
Defining a document title with Merge endpoint

### ISSUE THREAD

**Issue by pdoreau** [gotenberg/gotenberg#117]
I'm currently using ghostcript to merge PDFs and would like to migrate to this nice gotenberg API.

With gs, I use an option to specify the title : 

`'-c \'[ /Title MyTitle /DOCINFO pdfmark\'',`

Is there such a possibility with gotenberg ?

**Comment by gulien** [comment]
Not currently, but it may be interesting to set/update metadata to generated PDFs :)

**Comment by gulien** [comment]
Related:

* #207
* #330
