### ISSUE TITLE
PDF/A conversions

### ISSUE THREAD

**Issue by ResleyR** [gotenberg/gotenberg#120]
Would it be possible to add a environment variable to enable converting to pdf/a instead of pdf 1.5?

It looks like unoconv does this when you specify `-eSelectPdfVersion=1`           
Alternatively you need a prop called "SelectPdfVersion" with value 1 in the `registrymodifications.xcu` generated by LibreOffice.

I tried creating a `gotenberg.yml` config file but it doesn't look like that is being used anymore.

----
Edit: I don't know how to apply labels, so can someone please tag this as a question...

**Comment by gulien** [comment]
Hello @ResleyR 

>Would it be possible to add a environment variable to enable converting to pdf/a instead of pdf 1.5?

Why not, but I'd like to propagate this feature to HTML, URL, Markdown and Merge endpoints too. I guess that PDF generated by them might not use the same version.

**Comment by tobwen** [comment]
I guess, you need to pipe it through `ghostscript` then. Maybe `MuPDF` can also do it?

**Comment by robtrip** [comment]
Hello! We would like this too, we need pdf/a for one of our projects

**Comment by tobwen** [comment]
Unoconv already seems to support this, so just a switch needs to be exposed:

https://ask.libreoffice.org/en/question/2590/convert-files-to-pdfa-on-command-line-headless-mode/

**Comment by tobwen** [comment]
Maybe here?
https://github.com/thecodingmachine/gotenberg/blob/7e69ec4367069df52bb61c9ee0dce241b043a257/internal/pkg/printer/office.go#L103-L104

`--format PDF` as default and `--format PDFA` for PDF/A?

**Comment by ResleyR** [comment]
This should work
