### ISSUE TITLE
Feature Request: Pages resize

### ISSUE THREAD

**Issue by lukichev** [gotenberg/gotenberg#143]
Hey, guys. It could be cool if during PDF merging or even in separate endpoint we can change size of PDF to normal if pages are too big. 

## Expected Behavior
Every page in the document will be resized to "normal" size. Especially big pages. 

## Current Behavior
Currently, nothing changed. 

## Possible Solution
Resize every page in PDF is they are too big.

**Comment by gulien** [comment]
Hello @lukichev 

What do you mean by "change size"? 😄

**Comment by chislin** [comment]
Hello @gulien!
For example, some PDF files might be scanned with inappropriate DPI, and when merging few regular A4 size PDFs bigger pages pop out when rendering them with pdf.js. I think this might be useful to have something like scale all pages to the same size.
