### ISSUE TITLE
how to convert the last 5 pages of a docx to pdf

### ISSUE THREAD

**Issue by Simplici** [gotenberg/gotenberg#164]
I need to convert the last 5 pages of a docx file to pdf.

I have two questions:

1. how to count the total number of pages of a docx file by code?
2. is it possible to tell last 5 pages without knowing the exact number of pages of a docx?

**Comment by gulien** [comment]
Hello @Simplici 

1. Might be possible with another library.
2. Maybe LibreOffice provides a way to do that with its page ranges option, but I'm not sure about that.

**Comment by Simplici** [comment]
@gulien 
I have searched for a library to do that, but nothing found. the reason it that there is a page information in docx xml representation, but that information is not reliable especially when the document is generated by program.

the only way to get the number of pages is to do it when the document have been fully rendered by Word or LibreOffice.

for your 2nd proposition, i have also done some research, but no useful information was found.
