### ISSUE TITLE
Service to service correlation ids

### ISSUE THREAD

**Issue by ecasilla** [gotenberg/gotenberg#170]
Your issue may already be reported!
Please search on the [issue tracker](../../../issues) before creating one.

## Expected Behavior

When making an api call to gotenberg from another service all the request context is
lost because the trace ids are random even though I currently send one within the http headers.
It would be nice if gotenberg would allow the client to send a request_id/trace_id and use that before creating its own.

## Current Behavior

gotenberg trace ids are randomly created which is nice if its the only thing running but not helpful when trying to correlate request in a distributed system.

## Possible Solution

In service to service communication correlation ids can be helpful in stringing together a requests across multiple services. I am thinking maybe gotenberg can add a middleware to check a http header for a string X-TRACE-ID or X-REQUEST-ID or make it configurable on start so that it flexible to most use cases. If the header exists use that value as the string passed to xlog.New otherwise fallback to the current xrand behavior. You also may want to make the actual field the http header is mapped to dynamic also since some companies log requestId, request_id, trace, trace_id etc... as the field it being logged as. Since They're probably searching on that specific field to get the entire request life cycle against all services. So this `l.WithField("trace", trace)` would also need to be dynamic.

Let me know if you think this is the right approach.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by gulien** [comment]
Thanks for this well written issue.

I think you approach definitively make sense 👍
