### ISSUE TITLE
How to use the trace field provided from log?

### ISSUE THREAD

**Issue by soullivaneuh** [gotenberg/gotenberg#180]
Sometimes I have error like this:

```
{"bytes_in":"22190","bytes_out":"49904","host":"pdf.domain.dev","latency":"2978634042","latency_human":"2.978634042s","level":"info","method":"POST","msg":"request handled","op":"context.Context.LogRequestResult","path":"/convert/html","referer":"","remote_ip":"178.170.104.70","status":200,"time":"2020-03-06T22:24:26Z","trace":"2246dyEJKiCmxJW7T540Qc1c6IucrXx5","uri":"/convert/html","user_agent":"GuzzleHttp/6.3.3 curl/7.65.0 PHP/7.3.11"}
{"bytes_in":"9288","bytes_out":"34048","host":"pdf.domain.dev","latency":"2744331022","latency_human":"2.744331022s","level":"info","method":"POST","msg":"request handled","op":"context.Context.LogRequestResult","path":"/convert/html","referer":"","remote_ip":"178.170.104.70","status":200,"time":"2020-03-06T22:26:05Z","trace":"jl5XmA38KllYHzR6LbBcPWv22ws15pkf","uri":"/convert/html","user_agent":"GuzzleHttp/6.3.3 curl/7.65.0 PHP/7.3.11"}
```

Each error as a `trace` field. Is it something usable to get more information about the error? I don't see anything about this on the documentation.

**Comment by gulien** [comment]
Using the `LOG_LEVEL=DEBUG`, it should help you isolating the logs of one request.
That's said, the `trace` field is only useful if you test your requests one by one currently (see #170).

**Comment by soullivaneuh** [comment]
@gulien What is the performance impact of `LOG_LEVEL=DEBUG`? The error happen randomly, I'm not sure wanting to set the debug level on production systems.

**Comment by soullivaneuh** [comment]
@gulien What is the performance impact of `LOG_LEVEL=DEBUG`? The error happen randomly, I'm not sure wanting to set the debug level on production systems.

**Comment by gulien** [comment]
Performance impact should not be heavy but it might increase your logging costs 😄
