### ISSUE TITLE
[Feature Request] Config to call webhook on failure

### ISSUE THREAD

**Issue by sdawka** [gotenberg/gotenberg#181]
## Context
We needed to convert asynchronously, and don't have control over the files. However, we need to account for them, so we needed to handle the case when the conversion fails. In this case, I patched it to POST a failure notification to the webhookURL on conversion error. It would be nice if this was a feature, but since everyone may not need it, it would be nice if it was configurable.

**Comment by dcefram** [comment]
This would really be useful as right now, it just silently fails. I also made a patch on my end, but the team would rather use the official docker images. Is this an enhancement that someone is already working on? Else, we'd like to take a jab at this and submit a PR when ready?

**Comment by gulien** [comment]
@dcefram please do 👍
