### ISSUE TITLE
[question] how to collect logs in files

### ISSUE THREAD

**Issue by zffocussss** [gotenberg/gotenberg#191]
Hi team:
    is there a way to output logs to a file?

**Comment by gulien** [comment]
Hello @zffocussss 

It depends of the Docker orchestrator you're using.

For instance, using Docker you could start the Gotenberg container like that:

```bash
docker run --rm -p 3000:3000 thecodingmachine/gotenberg:6 > logs.txt
```

**Comment by zffocussss** [comment]
> Hello @zffocussss
> 
> It depends of the Docker orchestrator you're using.
> 
> For instance, using Docker you could start the Gotenberg container like that:
> 
> ```shell
> docker run --rm -p 3000:3000 thecodingmachine/gotenberg:6 > logs.txt
> ```

I am using k8s.
