### ISSUE TITLE
[question] How to convert a website that requires javascript to continue rendering? 

### ISSUE THREAD

**Issue by StringKe** [gotenberg/gotenberg#193]
# How to convert a website that requires `javascript` to continue rendering? 
For example, a website written in [Vue](https://github.com/vuejs/vue), some websites need to wait for the page to render specific content due to the use of the framework, otherwise the`dom` structure is empty

**Comment by StringKe** [comment]
`Wait time` is not an optimal choice, can you listen to the javascript method such as` console.log` to output specific content while generating PDF

**Comment by peterzhang41** [comment]
hi @gulien,

wkhtmltopdf, another famous PDFconversion tool, solved this by providing an optional parameter called 
--window-status, which will wait until window.status is equal to a string before rendering a page.
[https://wkhtmltopdf.org/usage/wkhtmltopdf.txt](url)

Maybe we can have something similar to this, like ```--form waitJsRenderStatus='DONE'``` ?

There is a discussion in CDP that creates an eval injection to detect the js render status, which I believe it still requires to add a 17ms delay (60 frames fresh rate) behind the wait function for the web engine actually paint the changes.
https://github.com/mafredri/cdp/issues/116

Have you been already working on this?
if not, I am keen to provide PR for this if you like the idea

**Comment by gulien** [comment]
Hey @peterzhang41!

> wkhtmltopdf, another famous PDFconversion tool, solved this by providing an optional parameter called
--window-status, which will wait until window.status is equal to a string before rendering a page.
https://wkhtmltopdf.org/usage/wkhtmltopdf.txt

I was not aware of the `--window-status` option in wkhtmltopdf, good catch! It would make a lot of sense for Gotenberg to have a similar option 👍 

> Have you been already working on this?
if not, I am keen to provide PR for this if you like the idea

Yes please! 😄Feel free to provide a PR, I'll gladly review it.

**Comment by peterzhang41** [comment]
Hi gulien,

https://github.com/peterzhang41/gotenberg

Sorry for the delay. The PR is almost there. Unfortunately, I don't have time to finish the doc and unit-tests. Could you pick it up and finished it? My company are all-in-aws at this moment. I am working on a lambda puppeteer solution for my project.

Cheers

**Comment by gulien** [comment]
@peterzhang41 thanks for your work. 

I plan to rewrite most of the code for the version 7.0.0 of Gotenberg, I'll take a look at what you did on your fork 👍 
Maybe I'll ask you to do a quick PR so that you'll be considered as a contributor 😄

**Comment by StringKe** [comment]
@gulien 7.0 When will it be released?

**Comment by gulien** [comment]
Early fall, but it could be sooner.
