### ISSUE TITLE
openapi / swagger specs

### ISSUE THREAD

**Issue by PhE** [gotenberg/gotenberg#200]
I didn"t see any openaoi / swagger specifications of the gotenberg API.

It could help client of your API to get a standard description and a great way to discover and test the API. It is just a plain static JSON file to serve.

Do you have plan to integrate such a specs in gotenberg ?

Do you think it would be usefull ?

Do you welcome contribution on this point ?

**Comment by gulien** [comment]
Hello @PhE 

That a great idea and of course contribution are welcome on this point 👍

**Comment by PhE** [comment]
I have some time now to work on it :smile: 

Work in progress [here](https://github.com/PhE/gotenberg/tree/openapi) ...

**Comment by PhE** [comment]
Got a first OpenAPI spec for `/merge` integrated and working in gotenberg :smile:  :

![image](https://user-images.githubusercontent.com/1107924/100585243-8d0cdb00-32ed-11eb-8f0c-0a570c9529b2.png)

**Comment by gulien** [comment]
Closing this in favor of #320 😄
