### ISSUE TITLE
Inject Page number in footer starting with arbitrary number

### ISSUE THREAD

**Issue by pjebs** [gotenberg/gotenberg#205]
I would like to inject the page number into the pdf starting at at arbitrary number (so it doesn't necessarily start at page 1).

Is that possible?

**Comment by pjebs** [comment]
How can I fork the package to add this functionality?

**Comment by pjebs** [comment]
I hope this can be addressed

**Comment by gulien** [comment]
Hello @pjebs 

Sorry for the late answer. Truth is I dunno how to do it..

Do you have a tool in mind that is capable of such task?

**Comment by j2L4e** [comment]
Couldn't you prepend `<div style="page-break-after: always"></div>" for every page-number you want to skip and then use the `nativePageRanges` option to exclude those from printing?

**Comment by pjebs** [comment]
I'll have a try
