### ISSUE TITLE
Run gotenberg without the web-server as a single execution?

### ISSUE THREAD

**Issue by benze** [gotenberg/gotenberg#211]
Is there an API or a run command that I can use to run gotenberg in the container as a single execution, but by passing all the parameters via a command-line execution?  My use case would be to use gotenberg in Fargate in an on-demand basis.  That is, when a request comes in on the AWS API gateway, it would spin up a Gotenberg container, process the conversion, and the container would then exit.

Given the API component to this docker image, the container is always up and running.

Is there a way to trigger a one-off run of gotenberg instead?  Something like
```
docker run --rm -v /mydata:/input thecodingmachine/gotenberg html header=/input/header.html footer=/input/body.html 
```
that would cause gotenberg to do the html->pdf conversion and exit once complete.

**Comment by gulien** [comment]
Currently there is no way to trigger a one-off run.

PS: I did not know you could use a Fargate task "on-demand" 🤔 . How would you do that?

**Comment by benze** [comment]
I haven't tested it out yet, but the theory would be to have the AWS Gateway fire a Lambda which triggers a Fargate task causing the container to spin up.  Once the execution of the PDF generation was complete, it would shut itself off, hence completing the "on-demand" need.

Alternatively, how difficult would it be to extract just the libs necessary in a serverless package to run the html->pdf conversion?

**Comment by gulien** [comment]
IMO the best option for "Serverless container" is Google Could Run at the moment.

If you want an pure AWS solution, you should take a look at https://github.com/puppeteer/puppeteer. Might be easier to integrate within a lambda 👍

**Comment by Simon-SDK** [comment]
@benze, did you get it to work on fargate? Am looking at a similar setup where my files are in S3 and needs to be converted. I use @shelf/aws-lambda-libreoffice at the moment which works ok but believe gotenberg might be a better fit

**Comment by benze** [comment]
@Simon-SDK I never got around to trying it with fargate.  I ended up switching technologies for the moment, and using serverless with puppeteer to convert html to pdf.

**Comment by Simon-SDK** [comment]
Ahh, ok. Not an option for me unfortunately - I have users uploading word files etc. that needs to be converted,  often hundreds at a time.
