### ISSUE TITLE
not working on windows server

### ISSUE THREAD

**Issue by madnadyka** [gotenberg/gotenberg#212]
## Expected Behavior
Expected that gotenberd is started and working on http://localhost:3000

## Current Behavior
localhost:3000 is unreachable. 

## Steps to Reproduce (for bugs)
1. docker run --env LOG_LEVEL=DEBUG --name pdf --rm -p 3000:3000  thecodingmachine/gotenberg:6

## Logs (LOG_LEVEL="DEBUG")

<img width="581" alt="Снимок экрана 2020-06-09 в 12 18 16" src="https://user-images.githubusercontent.com/29851936/84128366-8a71ad00-aa51-11ea-81bb-112bcd6a7073.png">

## Your Environment

* Version used: 6
* Operating System and version: Windows Server 2019 with nested virtualization, only intranet. 
On this server also other web application is working with 'docker run  -p 8080:8080 --name vso-app --restart=always -v ${PWD}/src:/src/ -v ${PWD}/config:/config/ -it vso' - and with this application everything is ok and it is available on http://localhost:8080

**Comment by gulien** [comment]
Sometimes Google Chrome does not start right away. Does it happens ad vitam aeternam?

**Comment by madnadyka** [comment]
It happens every time, no successful start

**Comment by gulien** [comment]
Weird 🤔  

Maybe it is related to insufficient memory? See https://stackoverflow.com/questions/43460770/docker-windows-container-memory-limit
