### ISSUE TITLE
feature request: replace chrome by chromium and provide multi-arch builds

### ISSUE THREAD

**Issue by maltegrosse** [gotenberg/gotenberg#213]
Hello,

are there any plans (and/or limitations) replacing chrome by chromium to support multi-arch builds, e.g. arm64 etc?

As far as I understood the [devtools](https://chromedevtools.github.io/devtools-protocol/) work the same on chrome and chromium.

Debian has prebuild [debs](https://packages.debian.org/en/chromium) for `amd64 arm64 armhf i386`

**Comment by gulien** [comment]
Hello @maltegrosse 

No plans currently but I think it would make sense to support multi-arch Docker images 👍

**Comment by vik-singh** [comment]
An ARM64 image would be very helpful for development now that Apple M1 is out

**Comment by Deninc** [comment]
+1 for arm64

**Comment by gulien** [comment]
👀 WIP v7

<img width="124" alt="Capture d’écran 2021-06-23 à 14 05 34" src="https://user-images.githubusercontent.com/8983173/123093513-16236500-d42c-11eb-90bb-8e8b491fe081.png">

**Comment by toxix** [comment]
If you run current docker images on an raspberry pi with raspian/debian buster this results in an
`standard_init_linux.go:228: exec user process caused: exec format error`
I checked a bit arround and was trying to rebuild the gotenberg docker image on the raspery pi, with no luck, as chrome is not available for this architecture. Switching to chromium actually let the building running past this step. Will open a PR with the change if build is successfull.
