### ISSUE TITLE
Failure when deploying 6.3.0 to Cloud Run

### ISSUE THREAD

**Issue by locnguyen** [gotenberg/gotenberg#221]
It seems like this [change](https://github.com/thecodingmachine/gotenberg/commit/dbdf8871cc2ce2e55c6525bd7485882aff6a8637) to revert PR #129 is preventing deployments to Google Cloud Run. Once I roll it back and create my own image I can successfully deploy. Is there a reason why tini can't be writable by the gotenberg user?

**Comment by gulien** [comment]
Hello @locnguyen 

It was part of a vulnerabilities chain. Now for Cloud Run it looks like it is necessary.
I'll update the documentation with the instructions.

PS: sorry for the inconvenience.

**Comment by karakanb** [comment]
Hi @gulien, did you have a chance to draft some documentation somewhere? I am looking for ways to avoid building an image every time I need to deploy this, although I don't quite understand the problem.

**Comment by gulien** [comment]
Hey @karakanb, alas no documentation yet.

You could build your own Docker image and store it in your registry, so that you don't have to build it everytime.

**Comment by pdoreau** [comment]
Hello everybody. What would you recommend to add to the Docker image ?
```
USER root
RUN chown gotenberg:gotenberg /tini
USER gotenberg
```
Is there something better ?

**Comment by maxstoyanov** [comment]
Just a note for future reference: This issue was originally tracked in #90
