### ISSUE TITLE
tables in markdown

### ISSUE THREAD

**Issue by RobinKamps** [gotenberg/gotenberg#222]
on Win10 tables are not rendered.
i use the example from blackfriday https://github.com/russross/blackfriday

```
Name    | Age
--------|------
Bob     | 27
Alice   | 23 
```

**Comment by gulien** [comment]
@RobinKamps 

Sorry for the late answer. It actually works as expected 🤔 

See: https://github.com/gotenberg/gotenberg/commit/a97f05db3b763cf7d38bb99da1bfb0a3781e0083
Output file: [markdown-table.pdf](https://github.com/gotenberg/gotenberg/files/7040999/markdown-table.pdf)
