### ISSUE TITLE
The handle is invalid.

### ISSUE THREAD

**Issue by pingProMax** [gotenberg/gotenberg#224]
594191415_2871.xlsx: copying data: read ./static/excel/company_33: The handle is invalid.

Why？

**Comment by 344085057** [comment]
c := &gotenberg.Client{Hostname: "http://192.168.3.27:4000"}
		doc, _ := gotenberg.NewDocumentFromPath("1594191415_2871.xlsx", "./static/excel/company_33")
		req := gotenberg.NewOfficeRequest(doc)
		dest := "result.pdf"
		err := c.Store(req, dest)
		if err != nil {
			fmt.Println("cccccc", err)
			return "", err
		}


cccccc 594191415_2871.xlsx: copying data: read ./static/excel/company_33: The handle is invalid.

**Comment by Tongzp** [comment]
i think u should add the full path，eg:
doc, _ := gotenberg.NewDocumentFromPath("1594191415_2871.xlsx", "./static/excel/company_33/1594191415_2871.xlsx")
and "dest ” same as last .
