### ISSUE TITLE
Post "http://localhost:3000/convert/html": dial tcp 127.0.0.1:3000: connect: connection refused

### ISSUE THREAD

**Issue by nitishnm** [gotenberg/gotenberg#225]
Your issue may already be reported!
Please search on the [issue tracker](../../../issues) before creating one.

## Expected Behavior
Running the docker in local machine as following command 
docker run --rm -p 3000:3000 thecodingmachine/gotenberg:6
it started successfully and available on http://localhost:3000
so i am calling the API URL from my code in golang as 
**c := &gotenberg.Client{Hostname: "http://localhost:3000"}
	index, _ := gotenberg.NewDocumentFromPath("file", "index.html")
	req := gotenberg.NewHTMLRequest(index)
	fmt.Println("============================")
	fmt.Println(pdfPath)
	dest := pdfPath
	os.Create(dest)
	c.Store(req, dest)**

and golang code is dockerized.
so i expect it to generate the pdf successfuly which is not coming now.

## Current Behavior
It is failing to generate pdf as connection is refused error

**Comment by gulien** [comment]
@nitishnm If your Golang code is in another container (it should), `localhost` is the `127.0.0.1` address inside your container. You should retrieve the public IP of the Gotenberg container or use Docker Compose.
