### ISSUE TITLE
Print with transparent background

### ISSUE THREAD

**Issue by roben** [gotenberg/gotenberg#226]
It would be great to have some way to generate PDF files from HTML with a transparent background.

It should be possible by setting `Emulation.setDefaultBackgroundColorOverride` in Puppeteer as stated here: https://github.com/puppeteer/puppeteer/issues/2545#issuecomment-423454635

Is there any way to archive this with gotenberg?

**Comment by gulien** [comment]
Hey @roben 

Currently not, but I'll add this to my todo list for upcoming `7.0.0` version 👍

**Comment by josecl** [comment]
Puppeteer  v9.0.0 added the `omitBackground` option to solve this...
https://github.com/puppeteer/puppeteer/issues/2545#issuecomment-922415973

Maybe is time to support it ;) 👍

**Comment by jpl-ivengi** [comment]
Is there an ETA on when this might be available? We would like to switch to gotenberg for PDF rendering but this property is crucial for us.

**Comment by gulien** [comment]
According to this comment https://github.com/puppeteer/puppeteer/issues/2545#issuecomment-944377566, it does not work with the header/footer feature (which is always enabled in Gotenberg).

Solution for future me:

* If no header/footer, set [WithDisplayHeaderFooter](https://github.com/gotenberg/gotenberg/blob/0e1e9b9cf34c0f6ff8f03af61257e150bb6cc613/pkg/modules/chromium/chromium.go#L762) method with `false`.
* If `omitBackground` + header/footer, log a warning.
* Documentation, obviously.

**Comment by gulien** [comment]
Hello @roben, @josecl, @jpl-ivengi,

Could you try with the image `gulnap/gotenberg:chromium-omit-background` ? I've added a new form field `omitBackground`(boolean) that overrides the default brackground with a transparent one.

**Comment by roben** [comment]
Hey Julien, thanks for the update. I have tried the image but as in your case the background was still white. I confirmed having the "hide default white background" message logged but also having a white background when opening the document with inkscape.

**Comment by gulien** [comment]
Thanks for the feedback! It does confirm that it’s not working as expected.

I wonder if it even work with Puppeteer, because I did use exactly the same mecanism in the Chrome DevTools Protocol.

**Comment by gulien** [comment]
Related: https://github.com/chromedp/chromedp/issues/1179

**Comment by roben** [comment]
Ok, so back to this issue: As it turned out, it *does* work.

And out of curiosity I added the following lines to the test script:

```go
WithMarginTop(0.5).
WithMarginBottom(0.5).
WithDisplayHeaderFooter(true).
WithHeaderTemplate(`<div style="font-size:8px;width:100%;text-align:center;"><span class="title"></span> -- <span class="url"></span></div>`).
WithFooterTemplate(`<div style="font-size:8px;width:100%;text-align:center;">(<span class="pageNumber"></span> / <span class="totalPages"></span>)</div>`).
```

which produced this file (bg color is set to green with .5 alpha): [printBG:1,htmlBG:0,override:1.pdf](https://github.com/gotenberg/gotenberg/files/9831681/printBG.1.htmlBG.0.override.1.pdf)

I think that means that you don't need to check if headers or footers are set. That both have a white background still is another issue but maybe this can be worked around.

**Comment by gulien** [comment]
Thanks @roben!

Actually, I won't print a warning or else if you set `omitBackground` at `true` with a header/footer, but now if there are no custom header nor footer, I set `WithDisplayHeaderFooter` at `false`.

The header/footer templates do not share anything with the page (CSS etc.), so it makes sense that the transparent background does not apply to them but only the page.

**Comment by roben** [comment]
Thanks, but could you not set WithDisplayHeaderFooter to false? I think it
works anyways (just with white header and footer backgrounds, though)

Julien Neuhart ***@***.***> schrieb am Fr. 21. Okt. 2022 um
09:55:

**Comment by gulien** [comment]
> Thanks, but could you not set WithDisplayHeaderFooter to false? I think it
works anyways (just with white header and footer backgrounds, though)

Why though? 😄 It should not change anything if you do have a header/footer 🤔

**Comment by roben** [comment]
Oh, I just read the source again. Yes, everything is fine as it is. I swear I read code that disabled headers and footers if omitBackground is set 🙈 But that's obviously not the case...

Thanks very much for your work and help!

**Comment by gulien** [comment]
😄 no problem.

Good to know: Gotenberg will return a `400 Bad Request` if you set `omitBackground` to `true` but not `printBackground`, so that one understand that these form fields work in pair.

**Comment by gulien** [comment]
@roben version `7.7.0` is now available 😉

**Comment by roben** [comment]
Awesome, thank you very much!

**Comment by roben** [comment]
Oh my, it seems they just fixed it in Chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=498892

Not sure if this is already released somewhere, though

**Comment by roben** [comment]
<img width="623" alt="image" src="https://user-images.githubusercontent.com/812205/200829378-e4eefda4-42ce-4dc4-b84a-83ceb674a729.png">
Yep, they fixed it 🤦‍♂️ The left PDF file is from current Chrome Dev Build 109.0.5396.3, right one is from stable 107.0.5304.110.

**Comment by gulien** [comment]
Thanks @roben! I’ll update the Gotenberg image when a new Chrome release is available 👌
