### ISSUE TITLE
[question] Generate and merge with other PDF in one run?

### ISSUE THREAD

**Issue by deedek** [gotenberg/gotenberg#246]
Is it possible to do "convert/html" and "merge" in a single request? I'd like to provide HTML with images, styles etc. and another PDF file and get single PDF in return. I know it's not possible out of the box but is it even possible to do without major changes?

**Comment by gulien** [comment]
@deedek the idea is interesting but I prefer having « dedicated » entry points that are easier to maintain. 

The functionality you’re requesting would raise the question about ordering: which one should be the first PDF (i.e., first pages)?

I could add another form field to handle the ordering according to the user flavor, but it will make the API harder to use for a small benefit ^^
