### ISSUE TITLE
Incorect convert xlsx to pdf

### ISSUE THREAD

**Issue by ruslan4uk** [gotenberg/gotenberg#252]
Hello

I using gotenberg in docker 

when coding, the column height is not calculated correctly, which leads to text overlapping.
I am attaching the original Excel file, and pdf.

[Детализированный отчет_2020-10-19 (1).xlsx](https://github.com/thecodingmachine/gotenberg/files/5399721/_2020-10-19.1.xlsx)

[Детализированный отчет_2020-10-19.pdf](https://github.com/thecodingmachine/gotenberg/files/5399725/_2020-10-19.pdf)

https://i.imgur.com/tIHEOJ0.png

**Comment by ruslan4uk** [comment]
Hello! Help me please

**Comment by gulien** [comment]
Hello @ruslan4uk 

I think that's a limitation of LibreOffice. If you try to convert your XLSX with LibreOffice directly, alas it will output the same result.
