### ISSUE TITLE
Seems not supporting webp images

### ISSUE THREAD

**Issue by naefp** [gotenberg/gotenberg#256]
## Expected Behavior
print background image when referencing a webp image

## Current Behavior
seems only to be supported with png images

## Steps to Reproduce (for bugs)
1. print html with wepb background locally (is working)
2. try convert via gotenberg (no background image)

## Your Environment
* latest version on docker in azure cloud

**Comment by gulien** [comment]
@naefp Sorry for the delay. With the latest version of Google Chrome (`95.x`) in the `amd64` Docker image, it should now work as expected.
