### ISSUE TITLE
Fit paper size to content.

### ISSUE THREAD

**Issue by osos** [gotenberg/gotenberg#258]
Cannot seem to figure out how to have paper size fit the content.

We simply want to render to pdf in the size of the content which however might be different from time to time.

Please advise is this is already doable.

**Comment by gulien** [comment]
Hello @osos,

I don't understand your problem 🤔

**Comment by osos** [comment]
Consider this to render to a pdf sized to only the div container: However, first and secondline dyamically loaded, fonts may differ etc.

```
<html>
<head>
  <style>
    #frame {
      border-radius: 3mm;
      border-width: 0.5mm;
      border-color: black;
      border-style: solid;
      background-color: rgba(255, 255, 255, 0.8);
      min-width: 20mm;
      float: right;
      padding: 2mm;
    }

    #firstpart {
      padding-bottom: 2mm;
      border: 0;
      border-bottom: 0.5mm;
      border-style: solid;
      border-color: black;
    }

    #secondpart {
      padding-top: 2mm;
    }
  </style>
</head>
<body>

  <div id="frame">
    <div id="firstpart">Firstline</div>
    <div id="secondpart">Secondline</div>
  </div>

</body>
</html>

```

**Comment by osos** [comment]
Webkit might have support. See this comment: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1627#issuecomment-725610877

**Comment by osos** [comment]
@gulien can it be done ?

**Comment by gulien** [comment]
As Gotenberg uses Google Chrome, I guess it might work. But I do not have experience on such scenario to be honest.

**Comment by osos** [comment]
But how shall I do it? What must I try?

**Comment by osos** [comment]
Ohh... just found this: https://stackoverflow.com/a/52128129

Will try it out later. If works, I suggest to put it in your documentation.

**Comment by osos** [comment]
It didn't work. gotenberg does not respect the page style.

@gulien, feature request, add support to preferCsspagestyle for papersize.

See puppeteer's api for the same: https://github.com/puppeteer/puppeteer/blob/v5.5.0/docs/api.md#pagepdfoptions

**Comment by keesvanlierop** [comment]
Has there been any update to this issue? We would love to one-page PDFs with gotenberg!

**Comment by hashkazi00** [comment]
If this is an issue being caused by the default margin internally set in gotenberg, 

you can remove the margins by doing `req.Margins(gotenberg.NoMargins)` and then `req.Scale(1)`

Also refer: 

https://github.com/thecodingmachine/gotenberg-go-client/blob/8bbbb1d52dba9b12ebeee68d7c98e8eab4af16bb/html.go
