### ISSUE TITLE
GET support

### ISSUE THREAD

**Issue by ddtxra** [gotenberg/gotenberg#259]
Thanks for this super nice project.
I am just wondering if it would be possible to support GET directly, so there is no need to use CURL and the interface would be much easier to use (IMO).

http://localhost:8855/pdf/{URL-TO-RENDER}
Example:
```
http://localhost:8855/pdf/https://google.com
http://localhost:8855/pdf/https://www.google.com/search?q=gotenberg
http://localhost:8855/pdf/https://facebook.com&marginTop=2
```

I developed a workaround solution here with docker-compose using express:
https://github.com/ddtxra/url-to-pdf-converter/

**Comment by gulien** [comment]
That’s actually a great idea! 🔥

**Comment by gulien** [comment]
@ddtxra I still think it’s a great idea, but I’ll soon ship a new version of Gotenberg with a lot more fields (including ones with JSON values) and I don’t want to maintain two entry points for the same functionality. 

That being said, if someone wants to give a shot, the [Chromium module exposes an interface](https://github.com/gotenberg/gotenberg/blob/v7.2.0/pkg/modules/chromium/chromium.go#L176) that allows another module to take advantage of the conversion functionality. 😉
