### ISSUE TITLE
Unable to access to API, localhost:3000, {"message":"Not Found"}

### ISSUE THREAD

**Issue by Haiderahandali** [gotenberg/gotenberg#268]
Hello, I downloaded and run the Docker image, but it does run, but I can't access the API. 
(it returns {"message":"Not found"} )

I looked into your github/documentation repo, didn't find any issue with similar problems, also the API isn't on the documentation so. I couldn't test it.

OS : MacOS BigSur

**Comment by PureKrome** [comment]
You will need to show us some exact screen shots of what you're trying. 

I just tried this and got the same thing! how, i thought? 

![image](https://user-images.githubusercontent.com/899878/109911128-9d25c380-7cfd-11eb-884c-68de58a4621f.png)

So i checked the docker logs...

![image](https://user-images.githubusercontent.com/899878/109911174-af9ffd00-7cfd-11eb-91fe-63ae0ccc186b.png)


Notice the `%20` at the end of the url? zomg! i had a secret `space` at the end. You can't see it, in the POSTMAN screenshot above (because you cannot see spaces) but it's there, when i removed it, i started getting results back.

**Comment by francois072** [comment]
I also have the same issue.
Also running the docker image and getting `Not Found` error.

**Comment by PureKrome** [comment]
@francois072 did you see my post above (regarding the hidden SPACE / `%20` ?) did that help? can you check the logs and what route it's trying to hit, in the docker image?

**Comment by francois072** [comment]
{"level":"error","ts":1643071135.6523657,"logger":"api","msg":"code=404, message=Not Found","trace":"81522c03-23fe-481d-a3b3-aba3c1df28e6","remote_ip":"172.17.0.1","host":"localhost:3000","uri":"/","method":"GET","path":"/","referer":"","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0","status":404,"latency":149991,"latency_human":"149.991µs","bytes_in":0,"bytes_out":9}

**Comment by francois072** [comment]
Paperless-NG logs:

documents.parsers.ParseError: Error while converting document to PDF: 404 Client Error: Not Found for url: http://localhost:3000/convert/office

**Comment by PureKrome** [comment]
@francois072 ok. a few things here:

- my post was from March 2021. I'm _guessing_ the docker version of Gotenberg was `version 6`. 
- current docker version is `version 7`.
- the API ROUTES are different between old-v-6 and current-v-7

| version | link | api url |
| ------- | ---- | ------- |
| v6 docs | https://gotenberg.dev/docs/6.x/office | /convert/office |
| v7 docs | https://gotenberg.dev/docs/modules/libreoffice | I think it's now this: /forms/libreoffice/convert |

does this help?

**Comment by francois072** [comment]
So I would have to use version 6 until Paperless gets updated.
I'll check if this works.

Is `localhost:3000` supposed to contain anything?

**Comment by PureKrome** [comment]
> So I would have to use version 6 until Paperless gets updated. I'll check if this works.
> 

Give it a go. I also have no idea what Paperless is etc but give that a go.

> Is `localhost:3000` supposed to contain anything?

No idea what you mean by this.

**Comment by francois072** [comment]
> No idea what you mean by this.

Should there be anything visible when I go to `localhost:3000`?

**Comment by PureKrome** [comment]
ah - gotcha. i can't remember. it's been a while since I last used this docker image .. so .. I can't remember.
