### ISSUE TITLE
XLSX print setup ignored in conversions

### ISSUE THREAD

**Issue by andreakappa** [gotenberg/gotenberg#275]
## Expected Behavior
Since I'm setting into the xlsx all the print settings: orientation, paper size, page fitting, breaks, hidden sheets etc.
when opening the file with libreoffice and printing pdf and/or launching from CLI  the conversion , the resulting pdf is ok. I'd expect the pdf printed with gotenberg ..and so with unoconv, is the same of the libreoffice one.

## Current Behavior
In the resulting pdf i see eveything in portrait even if pages are in landscape, hidden sheets are being printed and the fitting policy is not the same as libreoffice.

**Comment by gulien** [comment]
What's the CLI command you've been used for the conversion? Also, what's your LibreOffice version?

**Comment by Likenttt** [comment]
I encountered this problem as well recently. 
```
curl --request POST \
--url 10.38.162.130:30000/convert/office \
--header 'Content-Type: multipart/form-data' \
--form files=@template.xlsx  --form landscape=true \
 --form marginLeft=0 \                                                                                                  
    --form marginRight=0   --form marginTop=0 \
    --form scale=0.01 --form marginBottom=0  -o result.pdf -v
```
But these print settings don't take effect at all. I noticed the settings are indicated under HTML conversion,  are they merely adequate to this ?

**Comment by gulien** [comment]
@Likenttt @andreakappa the new documentation should be more explicit regarding options for Libreoffice.
