### ISSUE TITLE
pictures too?

### ISSUE THREAD

**Issue by labor4** [gotenberg/gotenberg#28]
Hi

is it possible to convert/wrap single/multiple pictures (png|jpg|etc) too?

cheers
manu

**Comment by gulien** [comment]
Hello!

Not currently, but you could use the HTML conversion to handle such case.

**Comment by labor4** [comment]
yes i tried it with a html wrapper. the problem is image specific: usually you dont want any margin framing or splitting on pictures or they need to be scaled proportionally. there is logic needed on the html side too. 
maybe imagemagick would be a way to framework this?
i know IM is quite big. 

m

**Comment by gulien** [comment]
Indeed, let’s mark this as enhancement. 👍

**Comment by yoyomule** [comment]
Yes, this feature is more useful. Is the current pptx document converted to PNG? In addition, whether to consider supporting the conversion of office documents to html5 in the future.

**Comment by tobwen** [comment]
I think, adding _Inkscape_, _Ghostscript_ and _ImageMagick_ to Gotenberg is a goal, we could achieve together and make this tool even more famous.

**Comment by gulien** [comment]
Indeed 😄 but I do not want to have an image > 1GB

**Comment by tobwen** [comment]
Then move away from debian :smile: No, for real, maybe a fork in future... 

A container based conversion service would be a pretty good alternative to all those cloud services, where you don't know what's happening with your documents. But I fully understand if this isn't the way you imagine _Gotenberg_ to go.

**Comment by lukichev** [comment]
I agree with @tobwen on this one. ImageMagick and GS support would be very cool!

**Comment by vegarsti** [comment]
+1 for a request for this, it would be super neat. Is there any way I could help?

**Comment by gulien** [comment]
Maybe it should be possible using Google Chrome?

**Comment by vegarsti** [comment]
Maybe [PDFium](https://pdfium.googlesource.com/pdfium/+/master/README.md)?

**Comment by PhE** [comment]
We have a [friendly fork ](https://github.com/arundo-tech/gotenberg) that can convert several images (png, jpeg, gif) in a single page (svg) ... converted to a PDF :

![image](https://user-images.githubusercontent.com/1107924/105394918-75cbd900-5c1e-11eb-9e2b-a048b423aa9b.png)

with a single APi call : 

```bash
$ curl --request POST \
    --url http://localhost:3000/convert/inkscape \
    --header 'Content-Type: multipart/form-data' \
    --form files=@gotenberg_ter.svg \
    --form files=@image1.png \
    --form files=@image2.gif \
    --form files=@image3.jpeg \
    -o result_images.pdf
```
