### ISSUE TITLE
PDF rendered in portrait orientation even when landscape is requested

### ISSUE THREAD

**Issue by andoks** [gotenberg/gotenberg#285]
In case someone else get the same problem as me, I am posting this for posterity. For me this was caused by a bootstrap issue: https://github.com/twbs/bootstrap/issues/25629

## Expected Behavior

I am trying to make gotenberg render a PDF in landscape orientation of a html-file which uses bootstrap. I have tried using both plain curl (by setting --form landscape=true), and the go client (by setting IsLandscape(true)). 

## Current Behavior

gotenberg renders PDF in portrait orientation even if landscape is requested when bootstrap.css (version 4) is used

## Possible Solution

I have attempted to switch the document width and heights to work around the issue, but this curiously had no effect.

## Steps to Reproduce (for bugs)

1. Download https://github.com/twbs/bootstrap/releases/download/v4.3.1/bootstrap-4.3.1-dist.zip
2. Use "bootstrap.css" in index.html
3. Request gotenberg to render a PDF in landscape mode

## Logs (LOG_LEVEL="DEBUG")

N/A

## Context

Printing a HTML webpage (which uses bootstrap 4) as PDF in landscape orientation.

I am able to work around the issue by switching to the newer bootstrap version 5 (https://github.com/twbs/bootstrap/issues/25629#issuecomment-606619398). But for others who do not have control over the source document, this may not be an option.

## Your Environment

* Version used: thecodingmachine/gotenberg:6 (docker image)
* Operating System and version:  Linux 64bit
* Link to your project: N/A

**Comment by andoks** [comment]
I am mostly posting this to share with others that may have the same issue. Please close this at your leisure

**Comment by gulien** [comment]
Thanks @andoks!

Maybe CSS print properties of Bootstrap 4 override the Chrome print option?

**Comment by andoks** [comment]
@gulien : might be, according to https://github.com/twbs/bootstrap/issues/25629#issuecomment-606619398 this is a known issue with bootstrap 4, but I did not investigate the root cause further, as upgrading to bootstrap 5 is an ok work-around for me.

Worth nothing though that the other work-around they mention that is setting `@page { size: auto; }` did _not_ work for me.

**Comment by CaioDev1** [comment]
> @gulien : might be, according to [twbs/bootstrap#25629 (comment)](https://github.com/twbs/bootstrap/issues/25629#issuecomment-606619398) this is a known issue with bootstrap 4, but I did not investigate the root cause further, as upgrading to bootstrap 5 is an ok work-around for me.
> 
> Worth noting though that the other work-around they mention that is setting `@page { size: auto; }` did _not_ work for me.

Regarding your issue with Bootstrap 4.3.1, I found success by removing the CSS page styles, specifically `@page {size ...}` and `@page {margin: ...}`, and instead using Gotenberg's `pageHeight` and `pageWidth` to define the page size. Additionally, I utilized `marginLeft`, `marginRight`, and other relevant properties to set the margins accordingly.
