### ISSUE TITLE
Merging Issues

### ISSUE THREAD

**Issue by lukichev** [gotenberg/gotenberg#29]
Hello. 
We experiencing some problems with file merging using /merge. 

Result errors: 
`{"message":"dict=markupAnnot entry=IT: unsupported in version 1.5\nThis file could be PDF/A compliant but pdfcpu only supports versions \u003c= PDF V1.7\n"}`

`{"message":"Read: xRefTable failed: parse: duplicate key"}`

`{"message":"Read: xRefTable failed: Free: object #0 not found."}`

Any ideas? 

Thanks.

**Comment by lukichev** [comment]
Seems like this is related to pdfcpu. Please respond.

**Comment by gulien** [comment]
You have to update your PDFs version from 1.5 to 1.7.
Or use another tool like PDFtk. 
I might also consider switching back to PDFtk instead of pdfcpu

**Comment by chislin** [comment]
We chose GhostScript for merging PDFs, it was already installed in our project for ImageMagick. It's definetely a pdfcpu issue.

**Comment by gulien** [comment]
Merge should works with new version (`3.1.2`).

When `pdfcpu` fails to merge PDFs, Gotenberg uses PDFtk instead.

**Comment by zffocussss** [comment]
please use [pdftk 3.0.9-2](https://packages.debian.org/bullseye/pdftk-java).when exceptions come.

Unhandled Java Exception in create_output(): java.lang.ClassCastException: class pdftk.com.lowagie.text.pdf.PdfNull cannot be cast to class pdftk.com.lowagie.text.pdf.PdfDictionary (pdftk.com.lowagie.text.pdf.PdfNull and pdftk.com.lowagie.text.pdf.PdfDictionary are in unnamed module of loader 'app') at com.gitlab.pdftk_java.bookmarks.ReadOutlines(bookmarks.java:237) at com.gitlab.pdftk_java.bookmarks.ReadOutlines(bookmarks.java:270) at com.gitlab.pdftk_java.TK_Session.create_output(TK_Session.java:2773) at com.gitlab.pdftk_java.pdftk.main(pdftk.java:177) There was a problem with pdftk-java.

**Comment by kbdavis07** [comment]
I keep getting error when merging PDF files:

PdfNull cannot be cast to class pdftk.com.lowagie.text.pdf.PdfDictionary 

_"please use pdftk 3.0.9-2.when exceptions come."_

What version of pdftk is Gotenberg currently using? 

Currently I am using Gotenberg 6.3.0

**Comment by gulien** [comment]
I dot not know the exact version. Could you try with `6.3.1`?

**Comment by kbdavis07** [comment]
I will try with 6.3.1 and let you know.

**Comment by kbdavis07** [comment]
I just tried it with 6.3.1 seems to be same issue.

**Comment by kbdavis07** [comment]
Here is the Debug log:


request failed","path":"/merge","method":"POST","bytes_out":"79","user_agent_details":{"os":{"family":"Other"},
"browser":{"family":"Other"},"device":{"family":"Other","category":"Other"}},"uri":"/merge","user_agent":"GotenbergSharpClient","

op":
"context.Context.LogRequestResult","referer":"","trace":"oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4","remote_ip":"127.0.0.1","bytes_in":"0","level":"error","latency":"5404008974",
"latency_human":"5.404008974s",
"host":"******.cluster.local:3000","time":"2020-10-08T15:57:36-06:00","status":500}


"resource directory '/gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4' removed","
op":"resource.Resource.Close","trace":"oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4"

exit status 2","op":"xhttp.mergeHandler: xhttp.convertSync: printer.mergePrinter.Print: xexec.Run",
"trace":"oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4","level":"error","time":"2020-10-08T15:57:36-06:00"}

"command 'pdftk /gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/A_x2rs_data.pdf 
                /gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/B_XA_kfxbpuogtxr0l3dw.pdf 
				/gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_WB_n8dy.pdf 
				/gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_W_x2rs_estimate.pdf 
				/gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/Z_x2rs_end.pdf cat output 
				/gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/zvkKgALHmPTkrO9v1tBBMu3OegSL69fZ.pdf' finished",
				
"op":"xexec.Run","trace":"oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4","level":"debug","time":"2020-10-08T15:57:36-06:00"}
				
{"msg":"including the message above, the version of pdftk-java (3.0.2), and if possible steps to reproduce the error.",

  "op":"stderr.pdftk./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/A_x2rs_data.pdf.
                     /gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/B_XA_kfxbpuogtxr0l3dw.pdf.
					 /gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_WB_n8dy.pdf.
					 /gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_W_x2rs_estimate.pdf.
					 /gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/Z_x2rs_end.pdf.cat.output.
					 /gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/zvkKgALHmPTkrO9v1tBBMu3OegSL69fZ.pdf",
					 
"trace":"oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4","level":"debug","time":"2020-10-08T15:57:36-06:00"}
				
"msg":"https://gitlab.com/pdftk-java/pdftk/issues",
"op":"stderr.pdftk./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/A_x2rs_data.pdf.
/gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/B_XA_kfxbpuogtxr0l3dw.pdf.
/gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_WB_n8dy.pdf.
/gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_W_x2rs_estimate.pdf
./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/Z_x2rs_end.pdf.cat.output.
/gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/zvkKgALHmPTkrO9v1tBBMu3OegSL69fZ.pdf",

"trace":"oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4","level":"debug","time":"2020-10-08T15:57:36-06:00"}
			

{"msg":"There was a problem with pdftk-java. Please report it at",
"op":"stderr.pdftk./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/A_x2rs_data.pdf
./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/B_XA_kfxbpuogtxr0l3dw.pdf
./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_WB_n8dy.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_W_x2rs_estimate.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/Z_x2rs_end.pdf.cat.output./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/zvkKgALHmPTkrO9v1tBBMu3OegSL69fZ.pdf","trace":"oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4","level":"debug","time":"2020-10-08T15:57:36-06:00"}
				
	{"msg":"\tat com.gitlab.pdftk_java.pdftk.main(pdftk.java:177)","op":"stderr.pdftk./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/A_x2rs_data.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/B_XA_kfxbpuogtxr0l3dw.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_WB_n8dy.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_W_x2rs_estimate.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/Z_x2rs_end.pdf.cat.output./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/zvkKgALHmPTkrO9v1tBBMu3OegSL69fZ.pdf","trace":"oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4","level":"debug","time":"2020-10-08T15:57:36-06:00"}
				
	{"msg":"\tat com.gitlab.pdftk_java.TK_Session.create_output(TK_Session.java:2773)","op":"stderr.pdftk./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/A_x2rs_data.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/B_XA_kfxbpuogtxr0l3dw.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_WB_n8dy.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_W_x2rs_estimate.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/Z_x2rs_end.pdf.cat.output./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/zvkKgALHmPTkrO9v1tBBMu3OegSL69fZ.pdf","trace":"oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4","level":"debug","time":"2020-10-08T15:57:36-06:00"}
			
	{"msg":"\tat com.gitlab.pdftk_java.bookmarks.ReadOutlines(bookmarks.java:237)","op":"stderr.pdftk./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/A_x2rs_data.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/B_XA_kfxbpuogtxr0l3dw.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_WB_n8dy.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_W_x2rs_estimate.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/Z_x2rs_end.pdf.cat.output./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/zvkKgALHmPTkrO9v1tBBMu3OegSL69fZ.pdf","trace":"oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4","level":"debug","time":"2020-10-08T15:57:36-06:00"}
			
	{"msg":"java.lang.ClassCastException: class pdftk.com.lowagie.text.pdf.PdfNull cannot be cast to class pdftk.com.lowagie.text.pdf.PdfDictionary (pdftk.com.lowagie.text.pdf.PdfNull and pdftk.com.lowagie.text.pdf.PdfDictionary are in unnamed module of loader 'app')","op":"stderr.pdftk./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/A_x2rs_data.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/B_XA_kfxbpuogtxr0l3dw.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_WB_n8dy.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_W_x2rs_estimate.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/Z_x2rs_end.pdf.cat.output./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/zvkKgALHmPTkrO9v1tBBMu3OegSL69fZ.pdf","trace":"oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4","level":"debug","time":"2020-10-08T15:57:36-06:00"}
			
	{"msg":"Unhandled Java Exception in create_output():","op":"stderr.pdftk./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/A_x2rs_data.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/B_XA_kfxbpuogtxr0l3dw.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_WB_n8dy.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_W_x2rs_estimate.pdf./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/Z_x2rs_end.pdf.cat.output./gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/zvkKgALHmPTkrO9v1tBBMu3OegSL69fZ.pdf","trace":"oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4","level":"debug","time":"2020-10-08T15:57:36-06:00"}
				
	{"msg":"executing command: pdftk /gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/A_x2rs_data.pdf /gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/B_XA_kfxbpuogtxr0l3dw.pdf /gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_WB_n8dy.pdf /gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_W_x2rs_estimate.pdf /gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/Z_x2rs_end.pdf cat output /gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/zvkKgALHmPTkrO9v1tBBMu3OegSL69fZ.pdf","op":"xexec.LogBeforeExecute","trace":"oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4","level":"debug","time":"2020-10-08T15:57:32-06:00"}
				
	{"msg":"merging '[/gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/A_x2rs_data.pdf /gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/B_XA_kfxbpuogtxr0l3dw.pdf /gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_WB_n8dy.pdf /gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/C_W_x2rs_estimate.pdf /gotenberg/tmp/oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4/Z_x2rs_end.pdf]'...","op":"printer.mergePrinter.Print","trace":"oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4","level":"debug","time":"2020-10-08T15:57:32-06:00"}
				
	{"msg":"creating context with '30.00s' of timeout...","op":"xcontext.WithTimeout","trace":"oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4","level":"debug","time":"2020-10-08T15:57:32-06:00"}
			
	{"msg":"options: {WaitTimeout:30}","op":"printer.logOptions","trace":"oOAyJbU47ObJeNvFYXF9TDkq4uwWk1w4","level":"debug","time":"2020-10-08T15:57:32-06:00"}

**Comment by kbdavis07** [comment]
> 
> 
> I do not know the exact version. Could you try with `6.3.1`?

Well I figured it out 6.3.1 is using pdftk-java (3.0.2)


> please use [pdftk 3.0.9-2](https://packages.debian.org/bullseye/pdftk-java).when exceptions come.

So that is higher version than what is recommended before.
