### ISSUE TITLE
Is there a way to not convert the href in the URL page into PDF links?

### ISSUE THREAD

**Issue by AbdoDabbas** [gotenberg/gotenberg#293]
I would like to ask if there's a way, when I provided a URL to be converted to PDF, to set a flag to not consider the `href` inside that URL and convert them into normal text.

**Comment by gulien** [comment]
Hello @AbdoDabbas! 

Best option would be to do some JavaScript black magic in the page to disable the links. 

If you don't have access to the page code, maybe using the [HTML](https://gotenberg.dev/docs/modules/chromium#html) endpoint with, again, some JavaScript black magic might do the work.
