### ISSUE TITLE
multiple headers for pdf

### ISSUE THREAD

**Issue by babugayathri3** [gotenberg/gotenberg#294]
Is it possible to have multiple headers based on the page number.?
Or is it possible to edit the headers based on page number.?

## Expected Behavior
say example, page 1 has header1
page 2 had no header
page 3 and following has a different header2

## Current Behavior
one headers possible for all the pages or none

## Possible Solution
if we know the page number beforhand of pdf generation it might be possible to change headers based on page numbers.?
or atleast if it is possible to execute the .js in the html, we can alter the headers based on the page numbers.

**Comment by hashkazi00** [comment]
need this same feature to solve a similar footer related implementation...

**Comment by gulien** [comment]
As long as Chromium does not have an API for that, your best shot would be using JavaScript libraries like [paged.js](https://www.pagedjs.org/documentation/) 😕
