### ISSUE TITLE
Problem with images in HTML conversion

### ISSUE THREAD

**Issue by jonas-lauber** [gotenberg/gotenberg#311]
I am getting really confused with images in HTML conversion... Some picture work and other not, but I don't get any error in logs, both are HTTPS with valid certificate... I can't figure out what is the difference...

Hier is an HTML sample to reproduce the problem:

```
<html lang="de">
<body>

<img src="https://www.sunrise.ch/content/dam/sunrise/email/header-image-invoice.jpg">

<img src="https://i.pinimg.com/originals/0a/1f/82/0a1f820e29719c7b67e9d5aa44241155.png">

</body>
</html>
```

If you tries to generate a PDF with this sample, you will get the second image, but a broken link for the first one...

Does anybody have an idea what is going on here ?

**Comment by hashkazi00** [comment]
hey jonas, just to solve this issue you should consider doing something like [this.](https://thecodingmachine.github.io/gotenberg/#html.assets)

**Comment by jonas-lauber** [comment]
Hi @hashkazi00,
Thanks for your answer. Yes, I saw this part of the doc, but I want to render an HTML coming from an email and thus not rendered by myself... So I don't have much control on it and it would be quite some effort to have to parse it and replace all ressources...
So my question is more: why **remote** ressources don't work reliably ? As the link you sent me says: 
`You may also use remote paths for Google fonts, images and so on.`
But in my example, only one of the **remote** links works and not the other one, why that ?

**Comment by jonas-lauber** [comment]
I analysed my problem further and found the source of the problem... Some servers doesn't allow downloading resources from headless browsers... In order to do so they check the **user agent**... 
It is possible to set the user agent in chrome with the flag **_--user-agent_**: `chrome --headless --user-agent="XXXX" ....`

It would be great to have a way to override the user-agent through an environment variable !

**Comment by gulien** [comment]
Thanks @jonas-lauber! Let me add this to my TODO list for v7 😄
