### ISSUE TITLE
support access local html file by file:///path/simple.html

### ISSUE THREAD

**Issue by kaiceo** [gotenberg/gotenberg#316]
use file:/// protocal to access local file , load assets like http protocal

**Comment by datocrats-org** [comment]
I would revive this. Perhaps hosting the contents of the source to a web page would get around this without redesign? What limitations would that face, what other approaches do you recommend?

**Comment by gulien** [comment]
Hello @datocrats-org 👋

Do you have an example of a use case in mind?

**Comment by gulien** [comment]
It should be fixed thanks to the following property:

```
--chromium-allow-file-access-from-files bool    Allow file:// URIs to read other file:// URIs
```
