### ISSUE TITLE
OpenAPI documentation

### ISSUE THREAD

**Issue by gulien** [gotenberg/gotenberg#320]
Gotenberg 6.x provided an OpenAPI documentation. So I guess it helped a lot of users to understand the API endpoints.

Alas, I did not find enough time yet to provide the OpenAPI documentation for Gotenberg 7.x 😄

Any help welcome 🚀 

See https://github.com/gotenberg/gotenberg/blob/6.4.4/docs/openapi.yaml.

**Comment by grofoli** [comment]
@gulien if you still need help here, I would try to find some time next week.

**Comment by gulien** [comment]
Thanks @grofoli 🎉

**Comment by grofoli** [comment]
@gulien the pull request is now ready for review ;-)

**Comment by grofoli** [comment]
@gulien I made some changes to the PR according to your feedback few days ago. Can you check the current version, please? :-)

**Comment by gulien** [comment]
Closed by #362.
