### ISSUE TITLE
apparmor error

### ISSUE THREAD

**Issue by araneta** [gotenberg/gotenberg#326]
i got this error message when running the docker

`docker run --rm -p 3000:3000 thecodingmachine/gotenberg:7
Unable to find image 'thecodingmachine/gotenberg:7' locally
7: Pulling from thecodingmachine/gotenberg
Digest: sha256:d70651ad8ff76c1b6f98974dc3a165239ed24a6d110dd39410a950b027d9234e
Status: Downloaded newer image for thecodingmachine/gotenberg:7
docker: Error response from daemon: AppArmor enabled on system but the docker-default profile could not be loaded: running `/sbin/apparmor_parser apparmor_parser -Kr /var/lib/docker/tmp/docker-default263823932` failed with output: apparmor_parser: Unable to replace "docker-default".  Permission denied; attempted to load a profile while confined?

error: exit status 243.
ERRO[0057] error waiting for container: context canceled`

how to fix this, thanks

**Comment by gulien** [comment]
Hello @araneta 

Without AppArmor, it works just fine:

```
docker run --rm -p 3000:3000 thecodingmachine/gotenberg:7
Unable to find image 'thecodingmachine/gotenberg:7' locally
7: Pulling from thecodingmachine/gotenberg
e1acddbe380c: Already exists 
a9d0cfc991e5: Pull complete 
96f1c5e016b0: Pull complete 
f87cb2483a14: Pull complete 
80eb05ee627e: Pull complete 
Digest: sha256:d70651ad8ff76c1b6f98974dc3a165239ed24a6d110dd39410a950b027d9234e
Status: Downloaded newer image for thecodingmachine/gotenberg:7

  _____     __           __               
 / ___/__  / /____ ___  / /  ___ _______ _
/ (_ / _ \/ __/ -_) _ \/ _ \/ -_) __/ _ '/
\___/\___/\__/\__/_//_/_.__/\__/_/  \_, / 
                                   /___/

A Docker-powered stateless API for PDF files.
Version: 7.0.2
-------------------------------------------------------
[SYSTEM] modules: api chromium gc libreoffice logging pdfcpu pdfengines pdftk unoconv unoconv-pdfengine 
[SYSTEM] api: server listening on port 3000
[SYSTEM] gc: application started
```

I have 0 experience with AppArmor, but it looks like it's more related to your system than the Gotenberg's Docker image 🤔

**Comment by araneta** [comment]
may i know what is your linux version?

**Comment by gulien** [comment]
macOS 😅
