### ISSUE TITLE
The sample test on your page does not work

### ISSUE THREAD

**Issue by maxiweb-nouvelle-caledonie** [gotenberg/gotenberg#337]
I tested this function as indicated on your demo page and I get an empty pdf

curl \
--request POST 'https://live-demo-us.gotenberg.dev/forms/chromium/convert/url' \
--form 'url="https://sparksuite.github.io/simple-html-invoice-template/"' \
-o my.pdf

**Comment by gulien** [comment]
Hello @maxiweb-nouvelle-caledonie,

I've just tested it and it works fine:

```bash
curl \
--request POST 'https://live-demo-us.gotenberg.dev/forms/chromium/convert/url' \
--form 'url="https://sparksuite.github.io/simple-html-invoice-template/"' \
-o my.pdf
```

Output:
[my.pdf](https://github.com/gotenberg/gotenberg/files/7111584/my.pdf)

**Comment by gulien** [comment]
That being said, looking at the logs of the demo, there are some 500 related to your issue 🤔 
`handle request: convert URL to PDF: convert to PDF: chromium PDF: navigate to '"https://sparksuite.github.io/simple-html-invoice-template/"': Cannot navigate to invalid URL (-32000)`

Weird.

**Comment by gulien** [comment]
Closing this as the issue did not appear anymore (for whatever reason). Please reopen if you have more details 👍
