### ISSUE TITLE
Support for armhf, i386

### ISSUE THREAD

**Issue by KubikDezimeter** [gotenberg/gotenberg#338]
Hi, I saw that support for arm64 was recently added by using chromium instead of chrome. In issue #213 maltegrosse also mentioned that chromium is also available for armhf. Would it be possible to support armhf, too? I noticed that in commit e923ac4 linux/arm/v7 already got added as a platform to publish.sh / release.sh, but then got removed again with the 7.0.0 release. What was the reason for that?

**Comment by gulien** [comment]
Hello @KubikDezimeter,

The commit you're referring to is related to an MR that was no longer relevant with the v7 codebase.

Regarding `armhf`, is there any use case you have in mind? I don't necessarily want to maintain too many architectures, as it's hard to test them. For instance, GitHub Actions does not provide `amd64` runtime.

**Comment by KubikDezimeter** [comment]
Thanks for the quick response :-) I use an Odroid hc2 as a nas and would like to run paperless-ng on it which depends on gotenberg. If it is to much effort to maintain armhf, I'll have to get a Raspberry Pi instead.

**Comment by kmandalas** [comment]
Hello - I am taking the opportunity to kindly request support also for i386 architecture.

**Comment by gulien** [comment]
@kmandalas @KubikDezimeter 

Could you guys test the image `gulnap/gotenberg:7.0.6-armhf-i386` 😄 ? It supports both `armhf` (arm/v7) and `i386` architectures.

**Comment by kmandalas** [comment]
I just tested it and it seems to be OK! Single test, more to follow soon. A nice closure for a working Friday evening. Thanks @gulien

**Comment by gulien** [comment]
@kmandalas @KubikDezimeter Gotenberg `7.0.7` supports both `armhf` and `i386` architectures 👍

**Comment by gulien** [comment]
Hello @KubikDezimeter,

There is currently an issue with the main branch on `armhf`. Looks like Chromium cannot be installed:

 ```
 301.9 update-alternatives: using /usr/bin/chromium to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
302.0 update-alternatives: using /usr/bin/chromium to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
302.9 Error: Can't open display: 
 ```
 
 I’ve updated the base image to Debian bookworm.
Do you have time to check why it’s not working?
