### ISSUE TITLE
Solve google chromium vulnerability issue

### ISSUE THREAD

**Issue by remoteexception** [gotenberg/gotenberg#344]
Hey @gulien ,
there is a vulnerability issue with the google chromium version that is installed in the current release (7.0.4). The installed version is 92.0.4515.159. The stable chromium version, that solves the issue is 93.0.4577.63 (see https://chromereleases.googleblog.com/2021/08/stable-channel-update-for-desktop_31.html).
Can you please build a new release version with the latest stable chromium? If you do a fresh build (make build), it will have exactly the recommended version of chromium (93.0.4577.63) (tested on my machine ;-) ).

The vulnerability description from Quadis is:
```
Customers are advised to upgrade to latest version 93.0.4577.63
For further details refer to Google Chrome 93.0.4577.63

Patch:
Following are links for downloading patches to fix the vulnerabilities:

Google Chrome 93.0.4577.63
```

It would really be great if you could publish a new release. (and even greater if you'd merge my PRs ;-) )

Best regards
remoteexception

**Comment by gulien** [comment]
It should be fixed in `7.0.5` 👍  thanks for the head-up 😄
