### ISSUE TITLE
Images with file name in camel case fail to render.

### ISSUE THREAD

**Issue by borttrob** [gotenberg/gotenberg#350]
Hey folks,

when using images with file names in camel case they fail to render in the resulting pdf. [Here](https://github.com/borttrob/projectgotenbergimgbug) is a minimal example  to reproduce the problem.

Calling the following in the 'failing' folder doesn't render the image.

```
curl --request POST 'http://127.0.0.1:3000/forms/chromium/convert/html' \
--header 'Content-Type: multipart/form-data' \
--form 'files=@"index.html"' \
--form 'files=@"MyImg.png"' \
--form 'paperWidth="8.27"' \
--form 'paperHeight="11.7"' \
-o my.pdf
```

Whereas calling the following in the working folder works just fine.

```
curl --request POST 'http://127.0.0.1:3000/forms/chromium/convert/html' \
--header 'Content-Type: multipart/form-data' \
--form 'files=@"index.html"' \
--form 'files=@"myimg.png"' \
--form 'paperWidth="8.27"' \
--form 'paperHeight="11.7"' \
-o my.pdf
```

I am using version 7.0.4.

**Comment by gulien** [comment]
@borttrob version `7.0.6` resolves your issue 😄 thanks for the reporting the issue!

**Comment by borttrob** [comment]
Whoah, that was fast! 👍
