### ISSUE TITLE
Rendered html gives darker colors in 7.0.0<

### ISSUE THREAD

**Issue by tibi22** [gotenberg/gotenberg#354]
We recently started using the 7.x version of gotenberg and noticed that rendering from an html file where we have blocks of text that has it's color changed produces much darker colours than expected. Tested with 6.4.4 version and that produces the expected result.

Note: The rendering is done by calling the chromium endpoint in 7.0.0, namely `forms/chromium/convert/html`, with the form containing only the index html file.
While the rendering in the old version is done by calling `/convert/html` with the form containing only the index file.

Is there a way to fix this?

Example html code:

css
```
    .party {
      margin-top: 24px;
      color: #d1d0d0;
      font-size: 14px;
    }

    .party-header {
      font-weight: bold;
    }
```

html
```
    <div class="party"> <span class="party-header"> Seller: Booo<br> </span> Business ID: xadsadsadas<br> VAT ID: asdfsdfsdgsd<br> Address: Bla bla<br> </div>
    <div class="party"> <span class="party-header"> Customer: Foo<br> </span> Payment method: Visa:
      ****1234 </div>
    <div class="party"> lorem ipsulum </div>
  </div>
```

Version 7:
![image](https://user-images.githubusercontent.com/5792523/134011080-eaabd47a-52ea-423f-a5ec-412e2d1f7c0d.png)

Version 6:
![image](https://user-images.githubusercontent.com/5792523/134011272-9897877e-0144-46f6-abc2-a1912930a5b8.png)

Expected result: The text should have the colors rendered as in v6.x example

**Comment by gulien** [comment]
Hmmm 🤔 

Did you test locally? If so, are you on macOS (m1)?

**Comment by tibi22** [comment]
This happens in our deployment in kubernetes, also locally for both me and a colleague.  He is on mac, but Intel I think, and I'm running a debian based os.

**Comment by gulien** [comment]
I don't know why this is happening to be honest. Maybe it occurs with the latest version of Google Chrome?
Do you use the form fields `pdfFormat` or `printBackground `?

**Comment by tibi22** [comment]
No, this is the curl I'm doing locally for testing:
```
curl \
--request POST 'http://localhost:3000/forms/chromium/convert/html' \
--header 'Gotenberg-Trace: debug' \
--form 'files=@"index.html"' \
-o my.pdf
```

**Comment by gulien** [comment]
Could you try to upgrade to `7.0.6` (if not already done) - i.e., `docker pull gotenberg/gotenberg:7`?

**Comment by tibi22** [comment]
yes, actually started from that version and then went down from there, hoping to find a version that worked  :smile: 

A colleague just found this: https://github.com/puppeteer/puppeteer/issues/2685 and a quick local check it seems to work, so it might be that this was added with the new version of Chrome, not sure if there's a good way to fix it at the browser level, but at least their solution offers a quick fix for this.

**Comment by gulien** [comment]
Oh thanks for the debug! I could add a style tag on the fly to make it work smoothly for the users 👍

**Comment by gulien** [comment]
@tibi22 Gotenberg `7.0.7` automatically adds the `-webkit-print-color-adjust: exact;` CSS property for all Chromium endpoints 😄

**Comment by tibi22** [comment]
awesome, thank you :pray:

**Comment by simon-lorenz** [comment]
> @tibi22 Gotenberg `7.0.7` automatically adds the `-webkit-print-color-adjust: exact;` CSS property for all Chromium endpoints 😄 

I assumed that this also makes `-webkit-print-color-adjust: exact;` redundant inside a footer or header, but that does not seem to be the case. Would it be possible to automatically inject `-webkit-print-color-adjust: exact;` into headers and footers too? (https://github.com/gotenberg/gotenberg/issues/132)

**Comment by gulien** [comment]
That would actually be hard to do 🤔 with the « main » page, I am able to do a lot of stuff thanks to the Chrome DevTools Protocol, but for the header/footer it would mean parsing an HTML string (or whatever the user send) which is not ideal.

Also, a user may not have access to a page code base, but the header/footer are always custom (i.e., it’s easy to add additional CSS properties) 😄

**Comment by simon-lorenz** [comment]
Ah, alright. No worries, I was just wondering if this would be an easy thing to do. Manually adding the CSS property is not really a hassle. Thanks for maintaining this cool project!
