### ISSUE TITLE
Chromium HTML route not rendering provided CSS files

### ISSUE THREAD

**Issue by josephdicarlo1** [gotenberg/gotenberg#356]
# Chromium HTML route not rendering provided CSS files

## Expected Behavior

Referencing [the Gotenberg docs](https://gotenberg.dev/docs/modules/chromium#html), I expect this to work:

* I upload files (in my case, index.html, two css files, a png file, a js file, and a woff2 file) to the `http://{hostname}:3000/forms/chromium/convert/html` endpoint
* Gotenberg generates a PDF document using these files, which should look like an invoice with a header including logo, page counters, and a table in the body.

## Current Behavior

* I upload files to the html endpoint
* Gotenberg generates a blank PDF, 879 bytes, every time.

## Investigation

Running Gotenberg with `--log-level debug` yielded these logs:

```json
{
  "level": "debug",
  "ts": 1632156434.8586862,
  "logger": "api.chromium.debug",
  "msg":"[0920/164714.858193:INFO:CONSOLE(0)] \"Access to XMLHttpRequest at 'file:///tmp/9c6c310e-b530-4120-820c-d239dae9df3a/bootstrap.min.css' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-untrusted, https.\", source: file:///tmp/9c6c310e-b530-4120-820c-d239dae9df3a/index.html (0)\n
[0920/164714.858303:INFO:CONSOLE(0)] \"Access to XMLHttpRequest at 'file:///tmp/9c6c310e-b530-4120-820c-d239dae9df3a/printable.css' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-untrusted, https.\", source: file:///tmp/9c6c310e-b530-4120-820c-d239dae9df3a/index.html (0)\n
[0920/164714.858367:INFO:CONSOLE(0)] \"Uncaught (in promise) #<ProgressEvent>\", source: file:///tmp/9c6c310e-b530-4120-820c-d239dae9df3a/index.html (0)\n",
  "trace": "f951bee9-bb1f-4e1a-94ea-303d935df037",
  "webhook": false
}
```

Indeed, this is the same error I get when opening `index.html` locally in Chrome on my PC:

![Same CORS error presented locally](https://i.imgur.com/XaY1ORQ.png)

## Possible Solution

I have two ideas for solutions to this issue:

### Solution 1: Run Chromium with override flag to use old behavior

[After some searching](https://www.codeproject.com/Answers/1195193/How-to-fix-cross-origin-requests-are-only-supporte#answer2), I found that Chromium needs to be run with the flag `--allow-file-access-from-files` to allow CORS, [which is corroborated here](https://peter.sh/experiments/chromium-command-line-switches/#allow-file-access-from-files). Testing this locally in Chrome on my PC did allow the document to render as desired. To me, this is the preferable solution, requiring no additional dependencies.

### Solution 2: Run a small web server inside the Docker container with Gotenberg

If adding an additional flag to Chromium isn't desirable, running a small web server (nginx, etc.) using the `/tmp` directory as the web root would allow presumably allow this to work as well. I have *not* tested this, however.

## Your Environment

* Docker version 20.10.8, build 3967b7d
* Windows Subsystem for Linux (WSL2)
  * Build: 18363
  * Branch: 19h1_release
  * Release: Fedora Remix for WSL
  * Kernel: Linux 5.4.72-microsoft-standard-WSL2

**Comment by gulien** [comment]
Hello @josephdicarlo1 👋 

I just tested the HTML endpoint locally and via a demo URL, and it worked as expected (with these [files](https://github.com/gotenberg/gotenberg/tree/v7.0.6/test/testdata/chromium/html/sample1)).

Could you show me a sample of the `index.html` you're trying to convert 🤔 ?

**Comment by josephdicarlo1** [comment]
> Could you show me a sample of the `index.html` you're trying to convert 🤔 ?

[Sure, here's a (redacted but otherwise unchanged) copy.](https://gist.github.com/josephdicarlo1/06bf33d63cb0c5b8d8bba2270cadd405)

**Comment by josephdicarlo1** [comment]
I also just tested it using `https://live-demo-us.gotenberg.dev` and got an identical result, down to the byte size.

![Result with demo server](https://i.imgur.com/FTcFa5l.png)

The only effective difference I can find between my files and the example files is that I'm using a js file, so I tried removing it and attempting again, which resulted in a much larger file yet still 3 blank pages.

![Result without JS file](https://i.imgur.com/awjxaAm.png)

**Comment by gulien** [comment]
Thanks for the details!

That’s definitely weird though.. I mean, I don’t understand why it works just fine with my sample while with your example it does not work 🤔

Maybe because your CSS/JavaScript files are trying to call other local files?

**Comment by josephdicarlo1** [comment]
> @josephdicarlo1 After some investigations, it seems related to [Paged.js](https://www.pagedjs.org/documentation/02-getting-started-with-paged-js/), which requires `A web server to let the polyfill access your CSS file`.
> 
> I'll add a flag for `--allow-file-access-from-files` 👍

Cool, thanks! I spent a while yesterday trying to dig around for a cause but came up empty, so I'm glad you found an answer. 😄

**Comment by josephdicarlo1** [comment]
BTW, I discovered that the client I was using for testing (Hoppscotch) was breaking the generated PDFs when I saved them, which explains why all the other examples were also showing up blank. 

I did confirm to make sure that the cors issue was still the root cause of the original issue, but yeah, that led me to a lot of extra headache yesterday 🤦‍♂️

Anyway, thanks again!

**Comment by gulien** [comment]
@josephdicarlo1 Gotenberg `7.0.7` has a new flag `--chromium-allow-file-access-from-files` that solves your issue 😄

**Comment by kabobbob-alto** [comment]
I came to this post as we're attempting to use version 8 with pagedjs and we're encountering the dreaded blank pages. Has anyone else raised this issue recently? We've set the `--chromium-allow-file-access-from-files=true` in our configuration, but no change in the results. Any help would be appreciated.
