### ISSUE TITLE
Feature Request: Add a way to compress final pdf size

### ISSUE THREAD

**Issue by spointecker** [gotenberg/gotenberg#359]
The currently generated pdfs look great but could be smaller in size.

If there would be an option/setting to choose the quality (1-100) for the pdf output that would be great.

**Comment by axelvugts** [comment]
I second this! A PDF with 3 photos in it (3x 2MB JPEGs) is 32MB now, which is just a little much

**Comment by janswist** [comment]
Also interested in this!

**Comment by kisamoto** [comment]
I don't know how to implement this in gotenberg unfortunately but for those who find this and need smaller pdfs look at using the `ps2pdf` tool on them in a second step. 

`ps2pdf input.pdf output.pdf` has proven to dramatically shrink file sizes for me.

**Comment by gulien** [comment]
@kisamoto ps2pdf seems to use Ghostscript , which is, alas, not compatible with the Gotenberg license.

**Comment by janswist** [comment]
It's kinda interesting to see that many people need it, but somehow there is no JS native solution

**Comment by a-ayala** [comment]
Does anyone have any recommendations on working optimally with images and the chromium module in Gotenberg?

Similar to @axelvugts I'm rendering a couple of images in my PDF, around 5mb each and the resulting file size is around 12mb. At the moment I'm passing them as file streams.

Is it just the case that we need to compress them before sending them to Gotenberg, and then compress the file again on the way out. Or is there something else we can do?

I wasn't sure if the issue is not with the images themselves but perhaps the options I'm using, currently all defaults.

**Comment by WillCohenInfotrack** [comment]
I think its related to Tagged PDFs - Here is PR https://github.com/gotenberg/gotenberg/pull/818

**Comment by dave-yotta** [comment]
I dont think it's to do with metadata - its to do with the compression algo used when writing images into the PDF.

**Comment by ldlamarc** [comment]
We are trying to switch from wkhtmltopdf to Gotenberg and our resulting pdf's are also much heaver (x3-x5).

**Comment by gulien** [comment]
Could you try to send the resulting PDF to the `/forms/libreoffice/convert` endpoint and play with the images form fields? Pretty sure it may actually work!

**Comment by gulien** [comment]
For future reference: https://stackoverflow.com/a/25715312.

**Comment by gulien** [comment]
So, I did try to implement a solution with QPDF + LibreOffice, but the workflow was breaking to much stuff (e.g., PDF compliance, metadata, etc.).

For now, the best option is using the `/forms/libreoffice/convert` route. I've updated the documentation to reflect this.

Please feel free to reopen this issue if a better (open source) tool  is available!

**Comment by boris-szl** [comment]
And updates on this one? Don't want to incentivise  reopening this. @gulien We are building a reporting engine that includes images in the appendix, where the number of images is dependent on the number of log entries for the report.

**Comment by kburrow-dbs** [comment]
No rush, but also interested in this feature. We want to supply a PDF compression service.

**Comment by gulien** [comment]
Done in https://github.com/gotenberg/gotenberg/commit/1ac1d9887e2b39f673569c3edb0b0fdf2880c2a8.

**Comment by boris-szl** [comment]
@gulien amazing! Thanks for your effort!
