### ISSUE TITLE
Internal Server Error when converting .docx file with comment in header to pdf

### ISSUE THREAD

**Issue by vipr0** [gotenberg/gotenberg#367]
Can't convert .docx to pdf if file has comment in header. 
Here's example file with comment in header ([sample_with_comment.docx](https://github.com/gotenberg/gotenberg/files/7265940/sample_with_comment.docx)) and without comment ([sample.docx](https://github.com/gotenberg/gotenberg/files/7265936/sample.docx)). 
The problem is same as in #249. Also tried with Libreoffice v7.1 and v7.2

## Expected Behavior
Successfully converted to [sample.pdf](https://github.com/gotenberg/gotenberg/files/7266024/sample.pdf) pdf file.

## Current Behavior
Returned `Internal Server Error`

## Steps to Reproduce (for bugs)
Send POST request on `/forms/libreoffice/convert` with attached sample file with comments.

## Logs
`2021/10/01 09:19:15.266 ERROR api handle request: convert to PDF: unoconv PDF: unix process error: exit status 5 {"trace": "dcff3b9a-1195-490a-8748-ec97f6ebb1ad", "remote_ip": "172.17.0.1", "host": "localhost:3000", "uri": "/forms/libreoffice/convert", "method": "POST", "path": "/forms/libreoffice/convert", "referer": "", "user_agent": "PostmanRuntime/7.28.4", "status": 500, "latency": 1627711700, "latency_human": "1.6277117s", "bytes_in": 27738, "bytes_out": 21}`

Also tried to convert directly from unoconv:
`Verbosity set to level 3
Using office base path: /usr/lib/libreoffice
Using office binary path: /usr/lib/libreoffice/program
DEBUG: Connection type: socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
DEBUG: Existing listener not found.
DEBUG: Launching our own listener using /usr/lib/libreoffice/program/soffice.bin.
LibreOffice listener arguments are ['/usr/lib/libreoffice/program/soffice.bin', '--headless', '--invisible', '--nocrashreport', '--nodefault', '--nofirststartwizard', '--nologo', '--norestore', '--accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext'].
LibreOffice listener successfully started. (pid=196)
Input file: sample_with_comment.docx
unoconv: UnoException during import phase:
The document 'file:///home/gotenberg/sample_with_comment.docx' could not be opened.
DEBUG: Terminating LibreOffice instance.
DEBUG: Waiting for LibreOffice instance to exit.`

## Environment
* Gotenberg - 7.0.7
* unoconv - 0.8.2
* Libreoffice - 7.2.0.4 20(Build:4)

**Comment by gulien** [comment]
Hello @vipr0 👋 

Sorry for the delay and thanks for this well written issue! 

I'm not sure I can do much for now; we'll have to wait for the next LibreOffice release I guess 😄

**Comment by muhyilmaz** [comment]
> Can't convert .docx to pdf if file has comment in header. Here's example file with comment in header ([sample_with_comment.docx](https://github.com/gotenberg/gotenberg/files/7265940/sample_with_comment.docx)) and without comment ([sample.docx](https://github.com/gotenberg/gotenberg/files/7265936/sample.docx)). The problem is same as in #249. Also tried with Libreoffice v7.1 and v7.2
> 
> ## Expected Behavior
> Successfully converted to [sample.pdf](https://github.com/gotenberg/gotenberg/files/7266024/sample.pdf) pdf file.
> 
> ## Current Behavior
> Returned `Internal Server Error`
> 
> ## Steps to Reproduce (for bugs)
> Send POST request on `/forms/libreoffice/convert` with attached sample file with comments.
> 
> ## Logs
> `2021/10/01 09:19:15.266 ERROR api handle request: convert to PDF: unoconv PDF: unix process error: exit status 5 {"trace": "dcff3b9a-1195-490a-8748-ec97f6ebb1ad", "remote_ip": "172.17.0.1", "host": "localhost:3000", "uri": "/forms/libreoffice/convert", "method": "POST", "path": "/forms/libreoffice/convert", "referer": "", "user_agent": "PostmanRuntime/7.28.4", "status": 500, "latency": 1627711700, "latency_human": "1.6277117s", "bytes_in": 27738, "bytes_out": 21}`
> 
> Also tried to convert directly from unoconv: `Verbosity set to level 3 Using office base path: /usr/lib/libreoffice Using office binary path: /usr/lib/libreoffice/program DEBUG: Connection type: socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext DEBUG: Existing listener not found. DEBUG: Launching our own listener using /usr/lib/libreoffice/program/soffice.bin. LibreOffice listener arguments are ['/usr/lib/libreoffice/program/soffice.bin', '--headless', '--invisible', '--nocrashreport', '--nodefault', '--nofirststartwizard', '--nologo', '--norestore', '--accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext']. LibreOffice listener successfully started. (pid=196) Input file: sample_with_comment.docx unoconv: UnoException during import phase: The document 'file:///home/gotenberg/sample_with_comment.docx' could not be opened. DEBUG: Terminating LibreOffice instance. DEBUG: Waiting for LibreOffice instance to exit.`
> 
> ## Environment
> * Gotenberg - 7.0.7
> * unoconv - 0.8.2
> * Libreoffice - 7.2.0.4 20(Build:4)

Same problem too ...

**Comment by gulien** [comment]
Closing this. It's an upstream issue, cannot do much there. I'll keep updating LibreOffice, it might resolve this bug someday.
