### ISSUE TITLE
Performance of Libreoffice PDF generation

### ISSUE THREAD

**Issue by HadrienKulik** [gotenberg/gotenberg#373]
We are currently using a Libreoffice + unoconv + api (node) architecture to generate our PDF, and we are considering switching to the more recent, maintained and beautifully coded Gotenberg ;) but we noticed some performance drawbacks.

The doc says `It starts a dedicated LibreOffice instance for each request.`.
This seems to add about 2 to 3s to the generation time, vs. our current architecture where the Libreoffice instance is just constantly idling, waiting for a new request (unoconv in listener mode).

3 additional seconds per conversion feels quite like a long time =/ Is there any way to improve that? Do you envision an option in the future to keep the LibreOffice open for longer than one request? 

Also, it says `It starts a dedicated LibreOffice instance for each REQUEST` but according to our preliminary tests, it seems like it does it for every conversion, not every request : if we make a request with multiple files to convert (and merge), the conversion time seems to just be linear with the number of docs (vs. our expectation of faster conversion for subsequent files once the LibreOffice instance is started for the first one). Do you confirm that's what is happening?

**Comment by gulien** [comment]
Re @HadrienKulik 😄 

> Yes LibreOffice is not able to perform concurrent conversions, but that problem seems to be a bit independent no?

Yes and no (:trollface:); if you have a single long-running LibreOffice instance, you have to provide a sort of lock mechanism to handle concurrent conversions.

A long-running LibreOffice instance also brings the following questions: how do you know if your instance is healthy or not, if there is 0 activity should I stop the instance, etc.

That's why I went for the "easiest" way, with which I'm able to make sure that:

1. Concurrent conversions are not an issue.
2. The application is stateless all the way: no need to worry about health check (I had some bad experiences with Chromium).
3. Maintainability is somewhat straightforward.

Yet, I do agree something can be done to improve the performances 😄 

> Do you think that would be easily doable?

Definitely, and https://github.com/unoconv/unoserver might be a part of the solution.

No ETA though, as I'll be a dad in the few next days and my available time will shrink 🍼

**Comment by gulien** [comment]
Related:

* https://github.com/unoconv/unoserver/issues/7
* https://github.com/unoconv/unoserver/issues/8
* https://github.com/unoconv/unoserver/issues/9

**Comment by gulien** [comment]
@HadrienKulik 

I found some time to work on this issue 😄 

The  Docker image `gulnap/gotenberg:unoconv-listener` starts a LibreOffice instance by default and there are substantial performance improvement (up to x5 on my test case).

I'd love some feedbacks from you; I'll release a new version in the next few days if everything runs smooth 👍

**Comment by sveisvei** [comment]
Btw, it is possible to run multiple instances of libreoffice, but it is a bit quirky  - as you need custom home-directory and a custom port per instance.

**Comment by gulien** [comment]
That’s how the current version is working ^^

**Comment by gulien** [comment]
In the next version, the new default is to start a unoconv listener and handle conversions using it (with a lock mechanism to prevent concurrent access). With the flag `—unocon-disable-listener`, you will still be able to run in stateless mode (i.e., no listener) like the current version.

**Comment by sveisvei** [comment]
Yes, nice! I see now you are already doing it the "correct way".

Keeping a flexible pool of libreoffice processes going, based on demand, and a queue would be really nice. 

```bash
LIBREOFFICE_WORKER_MAX_IDLE_MS=60000
LIBREOFFICE_WORKER_MAX_LIFETIME_MS=15 * 60000
LIBREOFFICE_MAX_WORKERS=4
```

I wrote something similar in a node.js project that processed a lot of document via libreoffice.

**Comment by gulien** [comment]
@sveisvei thanks for the inputs! 😄 

For now, I'd prefer to keep it simple, i.e., a single & always running listener, and let the orchestrator (Docker, Docker Compose, Kubernetes, etc.) do the scaling.

I'd love your feedback about the `gulnap/gotenberg:unoconv-listener` variant as you're able to compare with your existing Node.js solution 👍

**Comment by HadrienKulik** [comment]
Ah great @gulien thanks!! I'll run some performance tests as soon as I catch a break

**Comment by HadrienKulik** [comment]
@gulien I was able to test and yes the performances are waaay better <3

It's actually slightly faster on small docs, and much faster on big docx (x2) than our current set up. The test is not perfectly iso as I have not loaded all the custom fonts we have in our current container, but I don't expect big differences.

The hard thing to test is how it's going to perform on heavier load and over time (random fails, memory leak, etc.) but we are going to start deploying it on some instances and see how it performs!

I also noticed you released Gotenberg-php which looks awesome to clean up a bit our code 👍 

All in all 🤩 🙏

**Comment by gulien** [comment]
Great news @HadrienKulik 🥳

Indeed, performance under (heavy) load and overtime is something that’s harder to test on my side.

I can make an educated guess though regarding the load part: if the queue does not unstack fast enough, more and more requests will end up returning 503 response (timeout).

But the big unknown is how the unconv listener performs overtime 🤔 right now there isn’t a health check associated to it, nor a restart mechanism if unhealthy.

I’d also like some feedbacks about the PHP client 😄

**Comment by gulien** [comment]
@HadrienKulik @sveisvei as I plan to release Gotenberg `7.4.0` this evening, I'm closing this issue in favor of the discussion #391 😄 feel free to add your feedbacks ❤️

**Comment by daviatorstorm** [comment]
If you want a performance you can take a look on Pritset, if you are looking for enterprise solution. For now it have no PDF merge but at least it does conversion work pretty well.
