### ISSUE TITLE
Update chromium to get rid of Vulnerability Issues

### ISSUE THREAD

**Issue by remoteexception** [gotenberg/gotenberg#375]
Hallo @gulien ,
could you please trigger a new release to have the latest chromium included? The current version of Gotenberg (7.1.0) has chromium version 94.0.4606.81 which has several CVEs (see https://chromereleases.googleblog.com/2021/10/stable-channel-update-for-desktop_19.html). The latest version of chromium (95.0.4638.69) will fix them.
Thanks a lot!
Jana

**Comment by gulien** [comment]
@remoteexception release `7.1.1` is now available. Thanks for the heads up!
