### ISSUE TITLE
Support Proxy Server for Chromium Headless

### ISSUE THREAD

**Issue by inzanez** [gotenberg/gotenberg#376]
Hi

Is there any way to support a proxy server for the chromium module? I have tried setting the system proxy, but that doesn't seem to do the trick. So there's still the `--proxy-server` flag for `chromium` but I guess that's not supported, is it?

**Comment by gulien** [comment]
Hello @inzanez 

What's your use case? 😄

**Comment by inzanez** [comment]
@gulien Oh, well, I need to generate PDF's from HTML and that worked fine so far. Now my setup changed and the container cannot access the internet without using a proxy server anymore. And I guess that breaks the PDF generation.

I do have the HTML file locally, and all the rest that's required, but it still seems to need internet access. And setting `HTTP_PROXY` in the container doesn't do the trick.

**Comment by inzanez** [comment]
@gulien Yes indeed, I would think so. But I assume there's no way to specify that currently in Gotenberg, is there? Would it make sense making this accessible through an ENV variable? So people could set it if required, also in a Docker environment or similar?

**Comment by gulien** [comment]
I was thinking about a new module property (`--chromium-proxy-server`), like `--chromium-ignore-certificate-errors`, `--chromium-incognito`, etc. ^^

**Comment by inzanez** [comment]
@gulien How or where would one specify that for a docker container? Or would one just create a custom startup script for the container?
And yes, I guess something along the line makes sense...

**Comment by gulien** [comment]
Docker provides a way to override the default command of a Docker image 😉  See for instance https://gotenberg.dev/docs/get-started/docker#modules-properties (Docker) or https://gotenberg.dev/docs/get-started/docker-compose#modules-properties (Docker Compose).

**Comment by inzanez** [comment]
Sounds reasonable, I will make a PR then,…:-)

**Comment by inzanez** [comment]
@gulien Wow, thats quick! :-) Thanks!

**Comment by gulien** [comment]
Could you test with the Docker image `gulnap/gotenberg:proxy-server`? 😄 It supports the new module property `--chromium-proxy-server`.

**Comment by inzanez** [comment]
@gulien Yes, I will do so and report tonight!:-)

**Comment by inzanez** [comment]
@gulien Good news! It seems that this is working perfectly!
I will do some more tests early next week and give a final feedback, but my initial test did work well! Many many thanks for that quick implementation!

**Comment by gulien** [comment]
Great! 😄

**Comment by inzanez** [comment]
@gulien Sorry for the delay :-) It works perfectly! :-)
