### ISSUE TITLE
Page breaks with merge cells in table

### ISSUE THREAD

**Issue by lucasjdevine** [gotenberg/gotenberg#379]
### Discussed in https://github.com/gotenberg/gotenberg/discussions/378

<div type='discussions-op-text'>

<sup>Originally posted by **lucasjdevine** November  5, 2021</sup>
I am creating tables in HTML and whenever there is a merged cell or column that goes across page breaks, it looks wonky. Is there something I can do to clean those columns and/or rows up across pages?</div>

**Comment by gulien** [comment]
Closing this issue as it is not related to Gotenberg 😊
