### ISSUE TITLE
Header is invisible

### ISSUE THREAD

**Issue by karatekaneen** [gotenberg/gotenberg#387]
First of all, thank you for an AMAZING app!

When we tried to update to the latest version (7.3) our headers disappeared but footers still work properly.

### To replicate:

We used the example files from the documentation with some small modifications for testing. But the originals does not work for  us either.

#### index.html

  ```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>My PDF</title>
  </head>
  <body>
    <h1>Hello world!</h1>
  </body>
</html>
```

#### header.html

  ```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <style>
      body {
        font-size: 8rem;
        margin: 4rem auto;
        color: blue;
        -webkit-print-color-adjust: exact;
      }
    </style>
  </head>
  <body>
    <p>THIS IS MY HEADER <span class="pageNumber"></span> of <span class="totalPages"></span></p>
  </body>
</html>

```

#### footer.html

  ```html
<html>
  <head>
    <style>
      body {
        font-size: 8rem;
        margin: 4rem auto;
        color: blue;
        -webkit-print-color-adjust: exact;
      }
    </style>
  </head>
  <body>
    <p>FOOTER HERE <span class="pageNumber"></span> of <span class="totalPages"></span></p>
  </body>
</html>


```

Then we run the image and the request:

```sh
docker run --rm -p 3000:3000 gotenberg/gotenberg:7` # (This tells us it runs 7.3 when starting up)

curl \
--request POST 'http://localhost:3000/forms/chromium/convert/html' \
--form 'files=@"index.html"' \
--form 'files=@"header.html"' \
--form 'files=@"footer.html"' \
-o my.pdf
```

This results in the following PDF, I highlighted the invisible header to show the problem. When copying and pasting in a text field the correct text shows:

![Skärmavbild 2021-11-30 kl  12 22 02](https://user-images.githubusercontent.com/41196840/144038733-e817c647-ac0c-4bea-81a7-1cbdcc7917d7.png)

**Comment by gulien** [comment]
Hello @karatekaneen!

Looks like a bug, although I did not touch the header/footer feature since version 7.0.0 🤔

What was the previous version that was working for you?

**Comment by gulien** [comment]
Actually, adding `marginTop` to `1` (or at least, more than the default `0.39`) shows the header.

**Comment by karatekaneen** [comment]
Wow, thanks for the amazingly quick response!

We upgraded from 6.4.4 so don't know if 7.0 is OK or not.
