### ISSUE TITLE
Converting an encrypted Excel file

### ISSUE THREAD

**Issue by kayw-geek** [gotenberg/gotenberg#394]
When converting an encrypted Excel file, can you throw an exception to the corresponding information?

**Comment by gulien** [comment]
Hello @kayw-geek!

What error did you see in the Gotenberg logs?

**Comment by kayw-geek** [comment]
I use GuzzleHttp request API to convert encrypted Excel, and I get the HTTP status code of ClientException 4xx.

**Comment by gulien** [comment]
I'll need more information 🤔 

Can you add in this issue the Gotenberg's logs for this request? 😄
