### ISSUE TITLE
Process timeout of more than 29 seconds closes socket instead of returning 503 response code

### ISSUE THREAD

**Issue by gautam-nutalapati** [gotenberg/gotenberg#396]
Hi, Thank you for this awesome tool!!

I am converting docx file to pdf via docker image. I am running image as below:
`docker run --rm -p 3000:3000 gotenberg/gotenberg:7 gotenberg --chromium-disable-routes true --pdfengines-disable-routes true --log-level debug --api-read-timeout 600s --api-process-timeout 30s`
I am testing this tool for big file (2k pages) to analyze processing times.
When I provide api-process-timeout of less than 30s, on timeout, I get 503 response code back as mentioned in docs.
But providing api-process-timeout of 30sec or more causes socket to be closed.

Can we ensure response is sent on timeout before socket is closed?

Update: Response seen in curl:
```
~/Documents/gotenberg % curl -i --request POST 'http://localhost:3000/forms/libreoffice/convert' --form 'files=@"/Users/gautam/Desktop/reinvent/big_file.docx"' --form 'nativePageRanges="1-1"' -o docx-converted-big.pdf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.0M    0     0  100 10.0M      0   171k  0:00:59  0:00:59 --:--:--     0
curl: (52) Empty reply from server
```

**Comment by gautam-nutalapati** [comment]
I was able to fix this by using a value for `--api-write-timeout` which is greater than process timeout value.

**Comment by gulien** [comment]
Hello @gautam-nutalapati,

It seems to be related to the `—api-read-timeout` and `—api-write-timeout` flags 🤔 both are set to 30 seconds by default. The documentation is wrong in such a scenario; the server does not return a `503` response:

> http.WriteTimeout or http.ReadTimeout is used when you dont want to wait for network read/write of request/response indefinitely.

**Comment by gulien** [comment]
Reopening so that I can track the issue 😄 I’ll close it after updating the documentation. Thanks for the heads up @gautam-nutalapati

**Comment by jesseinit** [comment]
When I run
`docker run --rm -p 3000:3000 gotenberg/gotenberg:7 gotenberg --log-level=debug --chromium-disable-routes true --pdfengines-disable-routes true --api-read-timeout 600s --api-process-timeout 30s --api-write-timeout 60s`

I get
```log 
[SYSTEM] modules: api chromium gc libreoffice logging pdfcpu pdfengines pdftk prometheus unoconv unoconv-pdfengine webhook 
[SYSTEM] gc: application started
[SYSTEM] api: server listening on port 3000
[SYSTEM] prometheus: collecting metrics
{"level":"debug","ts":1641996936.2557855,"logger":"api","msg":"form data values: map[]","trace":"2797df6d-05fb-408b-b9a6-497111fccba4"}
{"level":"debug","ts":1641996936.2558823,"logger":"api","msg":"form data files: map[Design Process Workshop by Slidesgo.pptx:/tmp/6af267cc-9ad6-43a2-b882-49fb6b59af56/Design Process Workshop by Slidesgo.pptx]","trace":"2797df6d-05fb-408b-b9a6-497111fccba4"}
{"level":"debug","ts":1641996936.262925,"logger":"api","msg":"print to PDF with: {Landscape:false PageRanges: PDFArchive:false}","trace":"2797df6d-05fb-408b-b9a6-497111fccba4"}
{"level":"debug","ts":1641996936.2766035,"logger":"api.cmd","msg":"start unix process: /usr/bin/unoconv --user-profile ///tmp/b587b96a-4b33-4de0-8c22-f6c5f45de70f --port 41097 --format pdf --output /tmp/6af267cc-9ad6-43a2-b882-49fb6b59af56/cfd03e94-9069-47ac-9823-2b5b4309b6be.pdf /tmp/6af267cc-9ad6-43a2-b882-49fb6b59af56/Design Process Workshop by Slidesgo.pptx","trace":"2797df6d-05fb-408b-b9a6-497111fccba4"}
{"level":"debug","ts":1641996964.961774,"logger":"api.cmd","msg":"unix process killed","trace":"2797df6d-05fb-408b-b9a6-497111fccba4"}
{"level":"debug","ts":1641996965.0490973,"logger":"api","msg":"remove user profile directory '/tmp/b587b96a-4b33-4de0-8c22-f6c5f45de70f'","trace":"2797df6d-05fb-408b-b9a6-497111fccba4"}
{"level":"debug","ts":1641996965.06678,"logger":"api","msg":"'/tmp/6af267cc-9ad6-43a2-b882-49fb6b59af56' removed","trace":"2797df6d-05fb-408b-b9a6-497111fccba4"}
{"level":"error","ts":1641996965.0874858,"logger":"api","msg":"convert to PDF: unoconv PDF: context done: context deadline exceeded","trace":"2797df6d-05fb-408b-b9a6-497111fccba4","remote_ip":"172.17.0.1","host":"localhost:3000","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"PostmanRuntime/7.28.4","status":503,"latency":30142063400,"latency_human":"30.1420634s","bytes_in":8124389,"bytes_out":19}
```

This works fine with small-sized files but file from 5mb and above it returns the above error and give a `503Service Unavailable` error on the client.

@gulien

**Comment by gulien** [comment]
Hello @jesseinit!

Please open a new issue :)
