### ISSUE TITLE
How to change the default date format

### ISSUE THREAD

**Issue by transistive** [gotenberg/gotenberg#402]
Thank you for this amazing tool.

Overall, it works pretty great. But we want to change the default date in the footer to include the Belgian style (day/month/year) instead of (month/day/year).

How do we do this? We have already tried changing the `Accept-Language` header like this:
```php
return $this->gotenberg::send(
    $this->gotenberg::chromium(env('GOTENBERG_BASE_URL'))
        ->extraHttpHeaders([
            'Accept-Language' => 'nl-BE'
        ])
        ->footer(Stream::path(__DIR__ . '/PrinterAssets/footer.html'))
        ->margins(0, 1, 0.39, 0.39)
        ->html(
            Stream::string('my.html', $this->toHtml($orderedContents))
        )
);
```

The HTML for the footer is this:

```html
<html>
<head>
    <style>
        body {
            font-size: 8rem;
            margin-left: 0.39in;
        }
    </style>
</head>
<body>
<p><span class="date"></span></p>
</body>
</html>
```

Yet, the date format is still American style:
![image](https://user-images.githubusercontent.com/16435930/147919001-38ad82cd-9417-45f4-a2d7-95a1f6289212.png)

Is there anything else we can do? Or is this feature non-existent?

**Comment by gulien** [comment]
Hello @transistive,

AFAIK there is no way to change the localization 🤔 out of curiosity, is the date in the correct format when you convert a page to PDF with your Chrome browser?

There is a simple workaround though: generate a HTML string with the current date with PHP directly 😉
