### ISSUE TITLE
Bug 7.4.1 - Context deadline exceeded

### ISSUE THREAD

**Issue by HadrienKulik** [gotenberg/gotenberg#403]
Hi @gulien 
Everything was fine with 7.4.0, but we just upgraded to 7.4.1 and when running the container with these parameters, we are getting this error :

`docker run --rm -d -p xxxx:3000 --name gotenberg xxxxx/gotenberg
 gotenberg --chromium-disable-routes --pdfengines-disable-routes 
--webhook-disable --prometheus-disable-collect 
--prometheus-disable-route-logging`

![image](https://user-images.githubusercontent.com/1494897/147938572-071bd909-10de-44ee-9993-0256e4734f8c.png)

If we downgrade back to 7.4.0 it starts working again (iso parameters). Since the latest release is all about timeout, it seems like a big coincidence ^^

Is this meant btw?
![image](https://user-images.githubusercontent.com/1494897/147938537-bfcfe41e-c0f6-49f2-98c3-5728329a45c0.png)
https://github.com/gotenberg/gotenberg/compare/v7.4.0...v7.4.1#diff-51bc8303a14a97d22bd6cf1de23da23a89d419b96fe2e37972552a0b4cec8f77R393

**Comment by gulien** [comment]
That's actually the expected behavior :trollface: in `7.4.0`, the connexion socket is closed without notice.
It looks like the requests take more than 30 seconds to finish, so Gotenberg just terminates the process and returns a `503` response.

You could try to increase the timeout with `--api-timeout`.

**Comment by HadrienKulik** [comment]
Problem is that in 7.4.0 the request and conversion takes about 2 seconds, not > 30s =/

**Comment by gulien** [comment]
Now that's weird 🤔 could you show the logs a request with `--log-level=debug` ?

**Comment by gulien** [comment]
@HadrienKulik just a quick follow up regarding: 
![](https://user-images.githubusercontent.com/1494897/147938537-bfcfe41e-c0f6-49f2-98c3-5728329a45c0.png)

Yes it may look weird but that's actually for a good reason. There is a custom middleware that returns a `503` response if a request takes more than *x* seconds to finish (`--api-timeout`).  Also,  since `7.4.1`,  timeout = read timeout = write timeout. 

If `server.WriteTimeout` equals the time limit (defined by `--api-timeout`), then the connection socket is closed before the middleware can send the `503` response. 

So, I randomly set `server.WriteTimeout` as two times the time limit, but that's more a "last line of defense" if, for whatever reason, the timeout middleware fails.

**Comment by FabienLucini** [comment]
Hello, 
Please find below some logs :
```
A Docker-powered stateless API for PDF files.
Version: 7.4.1
-------------------------------------------------------
[SYSTEM] modules: api chromium gc libreoffice logging pdfcpu pdfengines pdftk prometheus qpdf unoconv unoconv-pdfengine webhook 
[SYSTEM] api: server listening on port 3000
[SYSTEM] pdfengines: pdfcpu pdftk qpdf unoconv-pdfengine
[SYSTEM] prometheus: collect disabled
{"level":"debug","ts":1641306912.5417416,"logger":"unoconv.usrbinunoconv","msg":"start unix process: /usr/bin/unoconv --listener --user-profile ///tmp/cc647f36-2dd4-4ddc-9535-c1db97c51fe2 --port 37755 -vvv"}
[SYSTEM] unoconv: listener started on port 37755
[SYSTEM] gc: application started
{"level":"debug","ts":1641306912.6045156,"logger":"unoconv.usrbinunoconv.stderr","msg":"Verbosity set to level 3"}
{"level":"debug","ts":1641306926.8869112,"logger":"api.formslibreofficeconvert","msg":"form data values: map[]","trace":"4d42bbe3-797c-4aa0-80e8-5a1b8ab3d22e"}
{"level":"debug","ts":1641306926.8869581,"logger":"api.formslibreofficeconvert","msg":"form data files: map[uJXc3rb1HVSYvL5.docx:/tmp/b9ddda90-af32-4a53-bc22-c81f0aed6cf0/uJXc3rb1HVSYvL5.docx]","trace":"4d42bbe3-797c-4aa0-80e8-5a1b8ab3d22e"}
{"level":"debug","ts":1641306926.8871343,"logger":"api.formslibreofficeconvert","msg":"unoconv lock acquired","trace":"4d42bbe3-797c-4aa0-80e8-5a1b8ab3d22e"}
{"level":"debug","ts":1641306926.887162,"logger":"api.formslibreofficeconvert","msg":"print to PDF with: {Landscape:false PageRanges: PDFArchive:false}","trace":"4d42bbe3-797c-4aa0-80e8-5a1b8ab3d22e"}
{"level":"debug","ts":1641306926.887326,"logger":"api.formslibreofficeconvert.usrbinunoconv","msg":"start unix process: /usr/bin/unoconv --format pdf --port 37755 -vvv --output /tmp/b9ddda90-af32-4a53-bc22-c81f0aed6cf0/2ae0fd0d-e5af-48a3-bb7f-eb85ab002278.pdf /tmp/b9ddda90-af32-4a53-bc22-c81f0aed6cf0/uJXc3rb1HVSYvL5.docx","trace":"4d42bbe3-797c-4aa0-80e8-5a1b8ab3d22e"}
{"level":"debug","ts":1641306926.962208,"logger":"api.formslibreofficeconvert.usrbinunoconv.stderr","msg":"Verbosity set to level 3","trace":"4d42bbe3-797c-4aa0-80e8-5a1b8ab3d22e"}
{"level":"debug","ts":1641306926.9628434,"logger":"api.formslibreofficeconvert.usrbinunoconv.stderr","msg":"DEBUG: Connection type: socket,host=127.0.0.1,port=37755,tcpNoDelay=1;urp;StarOffice.ComponentContext","trace":"4d42bbe3-797c-4aa0-80e8-5a1b8ab3d22e"}
{"level":"debug","ts":1641306927.0150712,"logger":"api.formslibreofficeconvert.usrbinunoconv.stderr","msg":"DEBUG: Existing listener not found.","trace":"4d42bbe3-797c-4aa0-80e8-5a1b8ab3d22e"}
{"level":"debug","ts":1641306927.01526,"logger":"api.formslibreofficeconvert.usrbinunoconv.stderr","msg":"DEBUG: Launching our own listener using /usr/lib/libreoffice/program/soffice.bin.","trace":"4d42bbe3-797c-4aa0-80e8-5a1b8ab3d22e"}
{"level":"debug","ts":1641306956.8893125,"logger":"api.formslibreofficeconvert.usrbinunoconv","msg":"unix process killed","trace":"4d42bbe3-797c-4aa0-80e8-5a1b8ab3d22e"}
{"level":"debug","ts":1641306956.8893828,"logger":"api.formslibreofficeconvert","msg":"unoconv lock released","trace":"4d42bbe3-797c-4aa0-80e8-5a1b8ab3d22e"}
{"level":"debug","ts":1641306956.8898304,"logger":"api.formslibreofficeconvert","msg":"'/tmp/b9ddda90-af32-4a53-bc22-c81f0aed6cf0' removed","trace":"4d42bbe3-797c-4aa0-80e8-5a1b8ab3d22e"}
{"level":"error","ts":1641306956.889879,"logger":"api","msg":"convert to PDF: unoconv PDF: context done: context deadline exceeded","trace":"4d42bbe3-797c-4aa0-80e8-5a1b8ab3d22e","remote_ip":"172.17.0.1","host":"147.135.192.16:8030","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"","status":503,"latency":30004955797,"latency_human":"30.004955797s","bytes_in":77737,"bytes_out":19}
```

I don't understand why because on an other server we have, if I launch the exact same docker for gotenberg everything works fine...

**Comment by gulien** [comment]
Thanks @FabienLucini 

`{"level":"debug","ts":1641306927.0150712,"logger":"api.formslibreofficeconvert.usrbinunoconv.stderr","msg":"DEBUG: Existing listener not found.","trace":"4d42bbe3-797c-4aa0-80e8-5a1b8ab3d22e"}`

This looks like the culprit. Do you see the same kind of line on your working Gotenberg instance?

**Comment by FabienLucini** [comment]
No indeed, on the working instance I don't have this line.
Any idea what could be the cause ?

**Comment by gulien** [comment]
No, not really 😕  I guess the listener did not start or was killed shortly after.

**Comment by gulien** [comment]
LibreOffice versions:

* `7.4.1` = `7.2.4.1 20(Build:1)`
* `7.4.0` = `7.2.3.2 20(Build:2)`

As I'm using the `sid` distribution to get LibreOffice 7.2, the package may not be stable. I could try to use https://packages.debian.org/bullseye-backports/libreoffice instead.

**Comment by gulien** [comment]
@HadrienKulik @FabienLucini could you try with `gulnap/gotenberg:libreoffice-bullseye-backports`?

**Comment by FabienLucini** [comment]
Well, it works with this image.

I found a difference between our 2 servers, one is on debian 9.5 (the problem) and one is on debian 10 (working)
Maybe the docker version or something is making troubles.

I found something unsual, on the instance that doesn't work with gotenberg/gotenberg:latest,
when I enter in the container and type this command : `libreoffice --version`
I got this result : 
`ls: cannot access 'libreoffice': Operation not permitted
/usr/bin/libreoffice: 191: exec: /usr/bin/oosplash: not found`

I have the same behavior with the image you provided : `gulnap/gotenberg:libreoffice-bullseye-backports`
But with this image, libreoffice seems to work anyway and we can convert documents.

On the second server, when I type `libreoffice --version` I got a normal result : `LibreOffice 7.2.4.1 20(Build:1)`


Anyway, I don't know when we will upgrade our server that runs debian 9.5 (this year obviously).
But in the meantime I will stay on gotenberg 7.4.0 unless you release another version.

Let me know if I can helpfurther.

**Comment by gulien** [comment]
Thanks for the details @FabienLucini ❤️ 

That's definitely weird. I think the LibreOffice `sid` package is somehow broken, while the `bullseye-backports` variant (which is stable) is not.

I'll publish a new release.

**Comment by gulien** [comment]
@HadrienKulik @FabienLucini Gotenberg `7.4.2` should resolve your issue. Please reopen if that's not the case ;)

**Comment by renepardon** [comment]
Hi,

my PDF was generated blank/empty. I found a little sentence in the documentation about that one, that my service should not be named "app". So I renamed it. When using url method, i receive the error:

```json
{
  "level":"error",
  "ts":1703211882.089908,
  "logger":"api",
  "msg":"convert URL to PDF: convert to PDF: context deadline exceeded",
  "trace":"1386db11-1a82-4e29-9dc9-bfb6f0dfd8e0",
  "remote_ip":"192.168.160.11",
  "host":"gotenberg:3000",
  "uri":"/forms/chromium/convert/url",
  "method":"POST",
  "path":"/forms/chromium/convert/url",
  "referer":"",
  "user_agent":"GuzzleHttp/7",
  "status":503,
  "latency":30006826722,
  "latency_human":"30.006826722s",
  "bytes_in":1205,
  "bytes_out":19
}
```

My Gotenberg version is 7.10.2.

**Comment by gulien** [comment]
@renepardon see https://gotenberg.dev/docs/troubleshooting#libreoffice

**Comment by renepardon** [comment]
Thank you @gulien 
I use PDF/A-1b already. There are no memory limits for this container on my local dev machine. And usually this should take no longer than a few seconds to complete. It's a 1-2 pages of HTML. If I send HTML, it works but with URL endpoint I get this error. This is how I do it with **gotenberg/gotenberg-php v1.1**:

```php
$request = Gotenberg::chromium('http://gotenberg:3000')
             ->margins(0, 0, 0, 0) // Margins needs to be 0 when using ->url()
             ->preferCssPageSize()
             ->failOnConsoleExceptions() // explicitly fail on chromium error
             ->emulateScreenMediaType() // We want to use default theming because we optimized already for printing
             ->pdfa('PDF/A-1b')
             ->pdfua()
             ->trace('debug', 'my-custom-thing')
             ->outputFilename('my-custom-pdf')
             ->url('http://laravel.test/transform-html-to-pdf'); // This endpoint can be Curl'ed from gotenberg machine without problem!

         try {
             $response = Gotenberg::send($request);
             return $response;
         } catch (GotenbergApiErroed $e) {
             $trace = $e->getGotenbergTrace('my-custom-thing');
             dd($e->getResponse(), $trace);
         }
```

**Comment by gulien** [comment]
> Ensure that the page you are attempting to convert doesn't require resources inaccessible from the Gotenberg instance.

Is `laravel.test` reachable by your Gotenberg container ?

**Comment by renepardon** [comment]
> > Ensure that the page you are attempting to convert doesn't require resources inaccessible from the Gotenberg instance.
> 
> Is `laravel.test` reachable by your Gotenberg container ?

Hi @gulien 

>              ->url('http://laravel.test/transform-html-to-pdf'); // This endpoint can be Curl'ed from gotenberg machine without problem!


Yes, it is :)
