### ISSUE TITLE
Feature request: enable conversion of password protected Office docs

### ISSUE THREAD

**Issue by markusberg** [gotenberg/gotenberg#410]
Would it be possible to allow pdf-conversion of password protected Office documents.

[unoconv](https://github.com/unoconv/unoconv/blob/master/doc/unoconv.1.adoc) has a command line option for the decryption password.

**Comment by gulien** [comment]
No ETA, but let’s add this to the TODO list 😄

**Comment by kaduuuken** [comment]
Is there any update on this? Would love to have this feature

**Comment by gulien** [comment]
Note for self: `unoconv` does not provide a way to do it. The LibreOffice CLI does support the password option but its limited for other stuff we use (paper orientation). The real solution is to use UNO scripting to handle such a scenario in our case.

**Comment by gulien** [comment]
Erratum: it's actually doable with unoconv. Feature added in: https://github.com/gotenberg/gotenberg/commit/b06d7445d96eff88f414ccab02db2574ab49a1f7.
