### ISSUE TITLE
Build new Gotenberg Release to have latest chromium

### ISSUE THREAD

**Issue by remoteexception** [gotenberg/gotenberg#412]
Hi Julien,
can you please initiate a new Release to get the latest version of Chromium? That version solves a lot of even critical CVEs.

CVE-Details:
https://chromereleases.googleblog.com/2022/01/stable-channel-update-for-desktop_19.html

Available Chromium versions:
https://chromium.woolyss.com/#linux

Thank you very much!

**Comment by gulien** [comment]
Thanks @remoteexception, will do 😄

**Comment by gulien** [comment]
On going! Did not know about `ungoogled-chromium`, I need to take look at it for other platforms (`arm64` etc.) 👍

**Comment by remoteexception** [comment]
No, I didn't know it. I just checked it out, very interesting! It could well become a replacement for google-chromium for the Gotenberg container. Should be evaluated.
