### ISSUE TITLE
503 Http status when trying to convert HTML to PDF

### ISSUE THREAD

**Issue by trcoelho** [gotenberg/gotenberg#413]
Hi, I'm having the following issue (extracted from gotenberg container):

> gotenberg    | A Docker-powered stateless API for PDF files.
gotenberg    | Version: 7.4.3
gotenberg    | -------------------------------------------------------
gotenberg    | [SYSTEM] modules: api chromium gc libreoffice logging pdfcpu pdfengines pdftk prometheus qpdf unoconv unoconv-pdfengine webhook
gotenberg    | [SYSTEM] gc: application started
gotenberg    | [SYSTEM] api: server listening on port 3000
gotenberg    | [SYSTEM] pdfengines: pdfcpu pdftk qpdf unoconv-pdfengine
gotenberg    | [SYSTEM] prometheus: collecting metrics
gotenberg    | [SYSTEM] unoconv: listener started on port 34369
gotenberg    | {"level":"error","ts":1643196222.2963061,"logger":"api","msg":"convert HTML to PDF: convert to PDF: chromium PDF: print to PDF: Printing failed (-32000)","trace":"9ab8c620-edcb-444c-8171-81cfce1296b5","remote_ip":"172.18.0.1","host":"localhost:3000","uri":"/forms/chromium/convert/html","method":"POST","path":"/forms/chromium/convert/html","referer":"","user_agent":"Java/1.8.0_312","status":500,"latency":3606906800,"latency_human":"3.6069068s","bytes_in":8240,"bytes_out":21}

When an HTML is being converted to PDF. 

The HTML document is not that big, it has ~3KB size plus footer of ~1KB. 

In addition, I've saw that in gotenberg 6 we had some environment variables, which it looks that was removed from version 7, as follows:

`     - DEFAULT_WAIT_TIMEOUT=300
      - MAXIMUM_WAIT_TIMEOUT=300`

I also have tried to set "--api-timeout=300s" command as per documentation but still got no success.

This is the path that I am using to handle this request:

**POST http://localhost:3000/forms/chromium/convert/html**
I am using version 7.4.3 of gotenberg, which I believe is the latest.

Do we have any fix for this one?

Thanks in advance.

**Comment by trcoelho** [comment]
I 've finally figured out what was the problem.

On my footer I was using some js and css imports using src and href ( as well as I use on index.html), however it got failed to convert it.

I also have changed the log level to debug, as a result to get more info and I found this:


`race":"1ffe64e4-a429-4bdc-832d-6a2c35c90a3f"}
gotenberg    | {"level":"debug","ts":1643198966.8256314,"logger":"api.formschromiumconverthtml.browser","msg":"<- {\"method\":\"CSS.mediaQueryResultChanged\",\"params\":{},\"sessionId\":\"324B532A256C0ADA987B233E63897CBA\"}","trace":"1ffe64e4-a429-4bdc-832d-6a2c35c90a3f"}
gotenberg    | {"level":"debug","ts":1643198966.8256657,"logger":"api.formschromiumconverthtml.browser","msg":"<- {\"method\":\"CSS.mediaQueryResultChanged\",\"params\":{},\"sessionId\":\"324B532A256C0ADA987B233E63897CBA\"}","trace":"1ffe64e4-a429-4bdc-832d-6a2c35c90a3f"}
gotenberg    | {"level":"debug","ts":1643198966.825723,"logger":"api.formschromiumconverthtml.browser","msg":"<- {\"method\":\"CSS.mediaQueryResultChanged\",\"params\":{},\"sessionId\":\"324B532A256C0ADA987B233E63897CBA\"}","trace":"1ffe64e4-a429-4bdc-832d-6a2c35c90a3f"}
gotenberg    | {"level":"debug","ts":1643198966.8257363,"logger":"api.formschromiumconverthtml.browser","msg":"<- {\"method\":\"CSS.mediaQueryResultChanged\",\"params\":{},\"sessionId\":\"324B532A256C0ADA987B233E63897CBA\"}","trace":"1ffe64e4-a429-4bdc-832d-6a2c35c90a3f"}
gotenberg    | {"level":"debug","ts":1643198966.8257415,"logger":"api.formschromiumconverthtml.browser","msg":"<- {\"method\":\"CSS.mediaQueryResultChanged\",\"params\":{},\"sessionId\":\"324B532A256C0ADA987B233E63897CBA\"}","trace":"1ffe64e4-a429-4bdc-832d-6a2c35c90a3f"}
gotenberg    | {"level":"debug","ts":1643198966.8257842,"logger":"api.formschromiumconverthtml.browser","msg":"<- {\"method\":\"Page.frameResized\",\"params\":{},\"sessionId\":\"324B532A256C0ADA987B233E63897CBA\"}","trace":"1ffe64e4-a429-4bdc-832d-6a2c35c90a3f"}
gotenberg    | {"level":"debug","ts":1643198966.825802,"logger":"api.formschromiumconverthtml.browser","msg":"<- {\"method\":\"CSS.mediaQueryResultChanged\",\"params\":{},\"sessionId\":\"324B532A256C0ADA987B233E63897CBA\"}","trace":"1ffe64e4-a429-4bdc-832d-6a2c35c90a3f"}
gotenberg    | {"level":"debug","ts":1643198966.825811,"logger":"api.formschromiumconverthtml.browser","msg":"<- {\"method\":\"CSS.mediaQueryResultChanged\",\"params\":{},\"sessionId\":\"324B532A256C0ADA987B233E63897CBA\"}","trace":"1ffe64e4-a429-4bdc-832d-6a2c35c90a3f"}
gotenberg    | {"level":"debug","ts":1643198966.8258162,"logger":"api.formschromiumconverthtml.browser","msg":"<- {\"method\":\"CSS.mediaQueryResultChanged\",\"params\":{},\"sessionId\":\"324B532A256C0ADA987B233E63897CBA\"}","trace":"1ffe64e4-a429-4bdc-832d-6a2c35c90a3f"}
gotenberg    | {"level":"debug","ts":1643198966.825821,"logger":"api.formschromiumconverthtml.browser","msg":"<- {\"method\":\"CSS.mediaQueryResultChanged\",\"params\":{},\"sessionId\":\"324B532A256C0ADA987B233E63897CBA\"}","trace":"1ffe64e4-a429-4bdc-832d-6a2c35c90a3f"}
gotenberg    | {"level":"debug","ts":1643198966.825915,"logger":"api.formschromiumconverthtml.browser","msg":"<- {\"method\":\"CSS.mediaQueryResultChanged\",\"params\":{},\"sessionId\":\"324B532A256C0ADA987B233E63897CBA\"}","trace":"1ffe64e4-a429-4bdc-832d-6a2c35c90a3f"}`

Looks like this is something related to chromium. Who knows...

Well, hopefully I got some explanation o this.


Thank you.

**Comment by gulien** [comment]
Hello @trcoelho!

Indeed, both the header/footer cannot take remote paths at all 😄 that being said, it's weird that it "blocks" the conversion (it should just ignore the remote paths).

**Comment by trcoelho** [comment]
Thanks @gulien !
