### ISSUE TITLE
Footer and Header are missing from version 7.x

### ISSUE THREAD

**Issue by skhaz** [gotenberg/gotenberg#419]
I upgrade from version 6 to 7 and I noticed that the footer and header are missing from the PDF when using Chromium.

Also, I noticed that this information on documentation of version 7 is missing

```
curl --request POST \
     --url http://localhost:3000/convert/html \
     --header 'Content-Type: multipart/form-data' \
     --form files=@index.html \
     --form files=@header.html \
     --form files=@footer.html \
     -o result.pdf
```

This feature was removed from version 7?

**Comment by gulien** [comment]
You need to add margins top & bottom 😉
See https://gotenberg.dev/docs/modules/chromium

**Comment by skhaz** [comment]
If someone has the same doubt, you need to open the documentation link and click on `Header & Footer`
<img width="546" alt="image" src="https://user-images.githubusercontent.com/46259/153471367-d2c24ee3-c651-469b-8094-2c05a90615dc.png">

**Comment by gulien** [comment]
Oh I thought it was explicit enough 😅
