### ISSUE TITLE
Latest 7.5.0 docker image intermittently crashes

### ISSUE THREAD

**Issue by jash** [gotenberg/gotenberg#420]
Every so often, the latest 7.5 docker image will crash on startup.  Here's the docker logs:

```
pdfgen_1     | 
pdfgen_1     |   _____     __           __               
pdfgen_1     |  / ___/__  / /____ ___  / /  ___ _______ _
pdfgen_1     | / (_ / _ \/ __/ -_) _ \/ _ \/ -_) __/ _ '/
pdfgen_1     | \___/\___/\__/\__/_//_/_.__/\__/_/  \_, / 
pdfgen_1     |                                    /___/
pdfgen_1     | 
pdfgen_1     | A Docker-powered stateless API for PDF files.
pdfgen_1     | Version: 7.5.0
pdfgen_1     | -------------------------------------------------------
pdfgen_1     | [SYSTEM] modules: api chromium gc libreoffice logging pdfcpu pdfengines pdftk prometheus qpdf uno uno-pdfengine webhook 
pdfgen_1     | [SYSTEM] gc: application started
pdfgen_1     | [SYSTEM] api: server listening on port 3000
pdfgen_1     | [SYSTEM] prometheus: collecting metrics
pdfgen_1     | [SYSTEM] pdfengines: pdfcpu pdftk qpdf uno-pdfengine
pdfgen_1     | [FATAL] starting uno: start long-running LibreOffice listener: waiting for the LibreOffice listener socket to be available: context deadline exceeded
```

Is this a timeout issue?  I don't believe the previous docker image (7.4.3) had this issue.

**Comment by gulien** [comment]
Yep, if you check the release note, there is a a new flag `--uno-listener-start-timeout` that allows you to set the time limit for starting the LibreOffice listener.

That being said, the default value is 10 seconds, which should be enough on most systems 🤔 

By chance, do you have any debug logs?

**Comment by jash** [comment]
Well, I ran it again with the default `uno-listener-start-timeout` but with debugging enabled.  It took a few tries before it failed again, but this was the output:

```
pdfgen_1     |   _____     __           __               
pdfgen_1     |  / ___/__  / /____ ___  / /  ___ _______ _
pdfgen_1     | / (_ / _ \/ __/ -_) _ \/ _ \/ -_) __/ _ '/
pdfgen_1     | \___/\___/\__/\__/_//_/_.__/\__/_/  \_, / 
pdfgen_1     |                                    /___/
pdfgen_1     | 
pdfgen_1     | A Docker-powered stateless API for PDF files.
pdfgen_1     | Version: 7.5.0
pdfgen_1     | -------------------------------------------------------
pdfgen_1     | [SYSTEM] modules: api chromium gc libreoffice logging pdfcpu pdfengines pdftk prometheus qpdf uno uno-pdfengine webhook 
pdfgen_1     | {"level":"debug","ts":1644864077.1002023,"logger":"uno.usrliblibreofficeprogramsoffice.bin","msg":"start unix process: /usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/e01ef20b-9cac-4fe0-9402-8d1118733690 --accept=socket,host=127.0.0.1,port=42516,tcpNoDelay=1;urp;StarOffice.ComponentContext"}
pdfgen_1     | [SYSTEM] prometheus: collecting metrics
pdfgen_1     | [SYSTEM] pdfengines: pdfcpu pdftk qpdf uno-pdfengine
pdfgen_1     | [SYSTEM] gc: application started
pdfgen_1     | [SYSTEM] api: server listening on port 3000
pdfgen_1     | {"level":"debug","ts":1644864078.2112298,"logger":"uno.usrliblibreofficeprogramsoffice.bin","msg":"unix process killed"}
pdfgen_1     | {"level":"debug","ts":1644864078.2112[718](https://gitlab.nadadventist.org/adventist-giving/api-server/-/jobs/29054#L718),"logger":"uno","msg":"got exit code 81, e.g., LibreOffice listener first start"}
pdfgen_1     | {"level":"debug","ts":1644864078.2113514,"logger":"uno.usrliblibreofficeprogramsoffice.bin","msg":"start unix process: /usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/e01ef20b-9cac-4fe0-9402-8d1118733690 --accept=socket,host=127.0.0.1,port=42516,tcpNoDelay=1;urp;StarOffice.ComponentContext"}
pdfgen_1     | {"level":"debug","ts":1644864078.213[720](https://gitlab.nadadventist.org/adventist-giving/api-server/-/jobs/29054#L720)6,"logger":"uno","msg":"waiting for the LibreOffice listener socket to be available..."}
pdfgen_1     | [FATAL] starting uno: start long-running LibreOffice listener: waiting for the LibreOffice listener socket to be available: context deadline exceeded
```

Since I don't see any errors, I'm assuming we're just hitting the timeout.  I suppose it's possible something is hung up, and this error would happen even with a longer timeout.  I'll try setting the timeout to 30 seconds and see what happens.

**Comment by gulien** [comment]
> I suppose it's possible something is hung up, and this error would happen even with a longer timeout.

👍 I do agree.

I wonder if the underlying process is not running for whatever reason (i.e., it was killed or else). Dunno what’s your Docker orchestrator here, but a workaround in the mean time would be to have an auto restart strategy (if that’s not already the case).

There are improvements on my side also, like a check on the process state + exit early.

**Comment by jash** [comment]
I changed the timeout to 60 seconds and still experienced the issue.  Yes, I suspect something is dying.

This is in Gitlab CI which is using docker compose.  In our production docker compose configuration we do have restart always which should help.

I agree, it would be helpful to have more debugging output when the fatal timeout gets hit.

Thank you for your help trying to figure this out!  Much appreciated.  By the way, we **love** this service.

**Comment by adetiamarhadi** [comment]
hi, I'm having the same issue. I run this on GCR with latest cloud run image

**Comment by gulien** [comment]
@adetiamarhadi @jash 

You may also disable the long-running listener with the `—uno-listener-restart-threshold=0` flag.

**Comment by adetiamarhadi** [comment]
@gulien thanks for the replay. already tried another version 7.4-cloudrun, and its works!

**Comment by gulien** [comment]
@adetiamarhadi does the `7.5` version crash intermittently or every time on Cloud Run?

**Comment by adetiamarhadi** [comment]
@gulien yes, I always get the same error message as Jash share

**Comment by jash** [comment]
Summary so far from what I've seen:
- Problem happens for us intermittently on image 7.5, but not at all on 7.4.3
- Symptom from the logs is timeout waiting for the LibreOffice listener socket to be available
- Extending the timeout from 10 to 60 seconds doesn't help (most likely not a timing issue).

@gulien - What's the effect of disabling the long-running listener?  Slower service responses since it must spin up LibreOffice on each request?  If it's not reliably spinning up on container start, could the same issue be present when spun up later on demand?

**Comment by gulien** [comment]
@jash yep, slower response time as a dedicated LibreOffice instance is started. 

But I dunno why it would be able to start after if it failed to start at bootstrap 🤔

**Comment by gulien** [comment]
@jash @adetiamarhadi I did not forget your issue. I have worked on a fix that might resolve the issue:

* The long-running LibreOffice listener now starts at the first conversion.
* If the listener crashes on startup, the error is more explicit.

I cannot upload a test Docker image because of my current internet connection, but I could create a branch in this repository from which you would be able to build the Docker image.

**Comment by gulien** [comment]
@jash @adetiamarhadi I did not forget your issue. I have worked on a fix that might resolve the issue:

* The long-running LibreOffice listener now starts at the first conversion.
* If the listener crashes on startup, the error is more explicit.

I cannot upload a test Docker image because of my current internet connection, but I could create a branch in this repository from which you would be able to build the Docker image.

**Comment by gulien** [comment]
@jash @adetiamarhadi could you test with the image `gulnap/gotenberg:no-first-start-libreoffice` ?

**Comment by mferuglio** [comment]
@gulien Hi, I pulled your "no-first-start-libreoffice" and I started many deployments on kubernets with success. No fatal error on startup.

For my side, I tested chromium to convert one url and it's working well for me.
I have not tested libreoffice methods.

**Comment by gulien** [comment]
Thanks @mferuglio! I do think that in most environments, the current version works as expected. The test image won’t change drastically the outcome in your case 😄

**Comment by jash** [comment]
> @jash @adetiamarhadi could you test with the image `gulnap/gotenberg:no-first-start-libreoffice` ?

I'm not able to reproduce the problem with that image.  As it was an intermittent issue, I'm not 100% positive it's fixed, but I tried restarting many times and didn't experience the problem.  All our tests passed.

Thanks much for working on this!

--John

**Comment by gulien** [comment]
@adetiamarhadi any chance to test on Cloud Run?

**Comment by adetiamarhadi** [comment]
hi @gulien already test on Cloud Run, and it works! Great Job!

**Comment by janswist** [comment]
> hi @gulien already test on Cloud Run, and it works! Great Job!

Hi, can you describe how did you make it work on Cloud Run? Can't nail it.
