### ISSUE TITLE
Feature: Ability to print one large full-page PDF from chromium

### ISSUE THREAD

**Issue by rslinckx** [gotenberg/gotenberg#421]
We have our own chromium wrapper that we use to take single-page PDF using the site content size.

We use:
- Emulation.setDeviceMetricsOverride(width=<requested pdf width>, height=<requested pdf height>)
- Page.getLayoutMetrics -> content_width=contentSize.width;  content_height=contentSize.height
- Page.printToPdf(paperWidth=content_width / 96, paperHeight=content_height / 96)

This way the whole website is "printed" inside one page which has the requested dimensions, rather than multiple pages.

I can't use dynamically computed values for paperWidth/Height in the current version of gotenberg. Would this be something that could be implemented ?

**Comment by gulien** [comment]
Hello @rslinckx,

Sure, why not 😄 

From a user perspective, I guess a form field like `onePageLayout=true` would do the trick.

Do you have more details on the implementation? For instance:

* `Emulation.setDeviceMetricsOverride(width=, height=)` - are `width` and `height` the size of the page (e.g., `A4`).
* Page.printToPdf(paperWidth=content_width / 96, paperHeight=content_height / 96) - why are you dividing by `96`?

**Comment by rslinckx** [comment]
The Emulation.setDeviceMetricsOverride width/height are pixel values like 1280 and 800, I see also deviceScaleFactor=1 and mobile=False as parameters, presumably these are the devtools protocol json arguments. I also use Emulation.setEmulatedMedia media=screen.

All this is to emulate a screen with a common resolution viewing the website.

The Page.printToPDF call with /96, I'm not sure why it's done that way, but I suspect this is some kind of conversion between paper DPI and screen resolution in pixels? Does it ring a bell ?

Finally there's also pageRanges="1" as argument to make it single page.

The end result is something that looks like a screenshot of the whole website (at least as far as can be loaded in the imparted time, and ignoring some JS lazy infinite scroll that sometime exist) in a single PDF page which has the same dimensions as the virtual screen.

I'm not sure if this fits exactly the problem space of gotenberg, but I figured it would be a relatively small addition, given that the rest is identical.

Note: I also generate a PNG snapshot using Page.captureScreenshot(format='png', clip={"x": 0, "y": 0, "width": 1280, "height": 800, "scale": 1}), but it seems the image is out of scope for gotenberg? Maybe it would be worth adding support for rendering images in chromium but also converting PDF to images (we use pdftocairo currently to do that)

**Comment by oiBio** [comment]
I would love to see this feature. This is exaclty what came up today at my side :-)
Could it also be useful to define the values of Emulation.setDeviceMetricsOverride via (optional) parameters? Just in case someone wants to use some other values than 1280/800.

**Comment by gulien** [comment]
Good to know: during my experiments (see https://github.com/gotenberg/gotenberg/issues/349), I've found that `Emulation` is only working with image outputs, not PDF.

For converting PDF to images, it could be interesting, but right now there are still a lot of stuff to be done regarding PDFs 😄

**Comment by rslinckx** [comment]
Right, it might be that the Emulation thing was only done because we are both taking an image output and a PDF output.

**Comment by rslinckx** [comment]
There seem to be now support for full-page image screenshots of websites, but digging into the code it seems to use a different method than the PDF conversion. The screenshot route uses https://github.com/gotenberg/gotenberg/blob/main/pkg/modules/chromium/tasks.go#L98 a special WithCaptureBeyondViewport option, not sure if it's available on the pdf variant?

**Comment by gulien** [comment]
@rslinckx alas no, that's two separate things :/

**Comment by matthiscock** [comment]
One page PDF flag, or something would be really useful

From docs, ideally you could use pageWidth and pageHeight for this: e.g.

pageHeight: fitContent
pageWidth: 10

Most people use PDFs for exporting, but not actually printing (as in using physical paper) so pages are actually rarely used.

**Comment by gulien** [comment]
Thanks for the input @matthiscock!

**Comment by matthiscock** [comment]
Just to add, tested, documentation has been updated (not by me) and all in all awesome!
