### ISSUE TITLE
Cyrillic filenames are not supported

### ISSUE THREAD

**Issue by gulien** [gotenberg/gotenberg#427]
### Discussed in https://github.com/gotenberg/gotenberg/discussions/426

<div type='discussions-op-text'>

<sup>Originally posted by **RuslMag** February 15, 2022</sup>
When sending a docx document with a Cyrillic name for conversion, a 500 error occurs. If i change the file name to English characters, the conversion works. Can this be fixed?

`{"level":"error","ts":1644935281.9760299,"logger":"api","msg":"convert to PDF: unoconv PDF: unix process error: wait for unix process: exit status 6","trace":"e9bc6dab-b1ed-450f-ab39-0fa25a9024c2","remote_ip":"172.172.0.1","host":"localhost:3000","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"PostmanRuntime/7.28.4","status":500,"latency":257080100,"latency_human":"257.0801ms","bytes_in":7370437,"bytes_out":21}`</div>

**Comment by gulien** [comment]
@RuslMag do you have an exemple of filename?

**Comment by RuslMag** [comment]
> @RuslMag do you have an exemple of filename?

For example - Пример.docx, измененный.docx

**Comment by yoyomule** [comment]
I also found that Chinese file names are not supported.For example - 测试中文.docx

**Comment by gulien** [comment]
Hmm:

* Cyrillic / Chinese characters are not installed in the OS.
* LibreOffice / unoconv don't know how to open such filenames.

I don't have much time for experimenting, but if you find a solution do not hesitate to post it there 😄

**Comment by yoyomule** [comment]
> 

Installing fonts doesn't seem to solve the problem either.

**Comment by edthorne** [comment]
We're migrating from 6.4.0 and noticed this issue as well. It wasn't happening in that release.

It's our experience that any non ASCII/ISO-8859-1 character likely causes the problem. In one of our cases a simple Unicode hyphen was culprit. This [blogger](https://www.taogenjia.com/2022/04/06/Gotenberg-Tutorial/#Error-file-name-contains-Chinese-characters) suggests encoding the filename using UTF-8 as a solution.

**Comment by arjay2539** [comment]
It works after downgrading to 6.4.0.

**Comment by gulien** [comment]
I've updated the documentation according to @edthorne feedback.

I've also checked the differences between Gotenberg's versions `6.4.x` and `7.x`, and the process is almost mostly the same (the only drastic difference being the version of LibreOffice).

Do not hesitate to reopen this issue if find the culprit 👍
