### ISSUE TITLE
performance problem on azure webapp

### ISSUE THREAD

**Issue by cedrichelloasso** [gotenberg/gotenberg#437]
Hello,

Has anyone tested gotenberg 7.X on the Azure WebApp Container? I notice a big performance problem.
I am using the chromium module.

Example: 
the page **www.google.com** with an azure webapp :
`{"level":"info","ts":1647275737.2735093,"logger":"api","msg":"request handled","trace":"0ebb7e78-81cc-460a-a237-68976cb0e5ef","remote_ip":"217.128.58.80:44078","host":"XXXXX.azurewebsites. net", "uri":"/forms/chromium/convert/url", "method": "POST", "path":"/forms/chromium/convert/url", "referer":"", "user_agent": "curl/7. 74.0","status":200,"latency":5003025615,"latency_human":"5.003025615s","bytes_in":962,"bytes_out":99785}`

on the other hand, locally or on a VM : 
`{"trace": "a5426090-3b6f-4362-9897-5b0538e94e81", "remote_ip": "172.17.0.1", "host": "localhost:3000", "uri": "/forms/chromium/convert/url", "method": "POST", "path": "/forms/chromium/convert/url", "referer": "", "user_agent": "curl/7. 74.0", "status": 200, "latency": 2263561023, "latency_human": "2.263561023s", "bytes_in": 962, "bytes_out": 99785}`

We go from 2 to 5 sec. 
With the parameters (at random) :
`--form 'url="https://www.google.com"' --form scale=0.8 --form marginTop=0 --form marginBottom=0 --form marginLeft=0 --form marginRight=0 --form landscape=0 --form paperWidth=8.5 --form paperHeight=11 -o test.pdf`

do you have an idea?

**Comment by gulien** [comment]
[IMO, the culprits are the CPU/memory. You can check the [demo](https://gotenberg.dev/docs/get-started/live-demo) for a better idea.

**Comment by cedrichelloasso** [comment]
Thanks for the feedback, I've already tested putting more resources, it doesn't improve the performance.
I'll try again on the azure webapp container with version 6 : **www.google.com** + same parameters.
`{"bytes_in":"968","bytes_out":"87672","host":"XXXXX.azurewebsites.net","latency":"1400119342","latency_human":"1.400119342s","level":"info","method":"POST","msg":"request handled","op":"context.Context.LogRequestResult","path":"/convert/url","referer":"","remote_ip":"XXXXX","status":200,"time":"2022-03-15T10:57:17Z","trace":"9UJwxmqHNIXrWCChAYIfw9HVApkO4HHu","uri":"/convert/url","user_agent":"curl/7.74.0"}`

There is a difference between the 2 versions (1.40 sec vs 5sec). We are using version 6 in production and we want to migrate to version 7, but we have big performance problems.
Are there any good practices to know when using the chromium module?
One solution is not to use azure webapp container but we want to test anyway.

**Comment by gulien** [comment]
The big difference is that Gotenberg v6 has a long-running Chrome instance, but there are memory leaks overtime. Gotenberg v7 starts and stops a specific Chrome browser per conversion.

That would explain the performance difference between the two versions. 

To mitigate the Chrome bootstrap time, you cannot do a lot alas. But having a good CPU/SSD certainly helps.

On the demo, converting the same URL takes between 3-5s.

**Comment by cedrichelloasso** [comment]
Thanks for the feedback.
