### ISSUE TITLE
Use gotenberg7.5.2 and gotenberg-go-client7.2.0 to report an error. 

### ISSUE THREAD

**Issue by chenlixiang0430** [gotenberg/gotenberg#448]
Use gotenberg7.5.2 and gotenberg-go-client7.2.0 to report an error. 

The error information is as follows:
{"level":"error","ts":1650336152.0338593,"logger":"api","msg":"code=404, message=Not Found","trace":"c76cdbfd-fd0d-4d67-b743-5df9111f2d0a","remote_ip":"111.58.46.48","host":"120.77.12.126:3000","uri":"/convert/html","method":"POST","path":"/convert/html","referer":"","user_agent":"Go-http-client/1.1","status":404,"latency":67755,"latency_human":"67.755µs","bytes_in":10733,"bytes_out":9}

The following is my test code：
`func GeneratePdf()  {
	// create the client.
	client := &gotenberg.Client{Hostname: "http://127.0.0.1:3000"}

	// prepare the files required for your conversion.

	// from a path.
	htmlStr := `<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title></title>
	</head>
	<body>
	<img src="img.png" width="100px">
		 <div class="botm">
		 	<div class="botm-text"> <text>简历</text></div>
		 </div>

		 <div class="botm-1">
		 	<div class="botm-text2"> <text>南宁职业技术学院</text></div>
		 </div>
		 <div class="botm-2">
		 	<div class="botm-text3"> <text><b>软件技术</b> </text></div>
		 </div>
		 <div class="botm-3">
		 	<div class="botm-text4"> <text>mysql，微信小程序，java程序设计，文件结构</text></div>
		 </div>
		 <div class="botm-4">
		 	<div class="botm-text5"> <text>学历:专科</text></div>
		 </div>
		 <div class="botm-5">
		 	<div class="botm-text6"> <text>爱摸鱼</text></div>
		 </div>
	</body>
</html>
`
	cssStr := `.botm{
			background-color: antiquewhite;
		}
		.botm-text{
			font-size: 30px;
		}
		.botm1{
			background-color: antiquewhite;
		}
		.botm-text2{
			font-size: 30px;
			color: bisque;
		}
		.botm{
			background-color: antiquewhite;
		}
		.botm-text3{
			font-size: 30px;
		}
		.botm{
			background-color: antiquewhite;
		}
		.botm-text{
			font-size: 30px;
		}`

	index, _ := gotenberg.NewDocumentFromString("index.html", htmlStr)
	style, _ := gotenberg.NewDocumentFromString("index.css", cssStr)

	//img, _ := gotenberg.NewDocumentFromPath("img.png", "upload/img/2018/08/02/2c32dea5-1f6a-450f-8550-2d7310aebdb0.png")

	req := gotenberg.NewHTMLRequest(index)
	req.Assets(style/*, img*/)
	req.PaperSize(gotenberg.A4)
	req.Margins(gotenberg.NoMargins)
	req.Scale(0.75)

	// store method allows you to... store the resulting PDF in a particular destination.
	err := client.Store(req, "upload/attach/test.pdf")
	if err != nil {
		fmt.Println("生成pdf出错-store："+err.Error())
	}
}`

I don't know what's going on. What should I do?

**Comment by gulien** [comment]
The Gotenberg `go` client is not compatible with Gotenberg v7 😅
