### ISSUE TITLE
Add final documents to tests

### ISSUE THREAD

**Issue by WeeSee** [gotenberg/gotenberg#46]
To get a better impression of the final images, could you please add the generated documents in the tests to the repo?

I have read the docs but seeing final results could give a better first impression.

For example I'd like to see:

* header an footer styles
* a complex microsoft word document converted to pdf

What are the limits to the conversion process, e.g. when rendering footnotes, sections, ...?

**Comment by tobwen** [comment]
The representation is dependent on the LibreOffice version. Unfortunately the quality of LibreOffice varies. Some things don't work properly, like embedded SVG files from new Microsoft Office or EPS files as older files. But most stuff is really fine for most needs.

To get an idea, you can download versions 4, 5 and 6 of LibreOffice. Currently Gotenberg uses version 5.

**Comment by gulien** [comment]
Thanks to the [live demo](https://gotenberg.dev/docs/get-started/live-demo),    users may now test their particular user cases.
