### ISSUE TITLE
forms/libreoffice/convert Error

### ISSUE THREAD

**Issue by hanzzbriant** [gotenberg/gotenberg#462]
Image launch log:
```
A Docker-powered stateless API for PDF files.
Version: 7.5.2
[SYSTEM] modules: api chromium gc libreoffice logging pdfcpu pdfengines pdftk prometheus qpdf uno uno-pdfengine webhook
[SYSTEM] gc: application started
[SYSTEM] uno: long-running LibreOffice listener ready to start
[SYSTEM] pdfengines: pdfcpu pdftk qpdf uno-pdfengine
[SYSTEM] prometheus: collecting metrics
[SYSTEM] api: server listening on port 8088

```
When trying to make a request to remote Gotenberg docker: 
`curl --request POST 'http://192.168.1.4:8088/forms/libreoffice/convert' --form 'files=@"C:\Users\user\blank.docx"' -o my2.pdf`

This happens: 
`{"level":"error","ts":1653572720.2345355,"logger":"api","msg":"code=404, message=Not Found","trace":"1ea0e53a-f27a-46e4-adec-cce84a7d6be5","remote_ip":"192.168.1.21","host":"192.168.1.4:8088","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"curl/7.81.0","status":404,"latency":65412,"latency_human":"65.412µs","bytes_in":13033,"bytes_out":9}`

But same request works normaly on localhost:3000

**Comment by hanzzbriant** [comment]
This example works properly:
`curl --request POST 'http://192.168.1.4:8088/forms/chromium/convert/url' --form 'url="https://sparksuite.github.io/simple-html-invoice-template/"' -o my.pdf`

Maybe something wrong with libreoffice module?

Trying port 3000 doesn't help.

**Comment by gulien** [comment]
Hello @hanzzbriant,

Huh weird lol, the URL seems good. Maybe a hidden character?

**Comment by hanzzbriant** [comment]
Problem solved

**Comment by meakbiyik** [comment]
Same here. @mvlach were you able to solve it?

**Comment by egarkavy** [comment]
Guys we were all pranked. The example from off docs has a clear flag to disable LibreOffice routes
My command looked like 
docker run --rm -p 8081:80 gotenberg/gotenberg:8 gotenberg --api-port=80 --api-timeout=10s --libreoffice-disable-routes --log-level=debug
--libreoffice-disable-routes ....

**Comment by Trevato** [comment]
@egarkavy thanks for this. i got pranked too :(

**Comment by gulien** [comment]
Which documentation? 🤔
