### ISSUE TITLE
Feature request: Limit the queue size for stateful mode LibreOffice conversions

### ISSUE THREAD

**Issue by NathanLamSeekasia** [gotenberg/gotenberg#463]
The stateful mode LibreOffice conversion is nice because it is faster than stateless mode.
I tried some performance tests by launching multiple instances (stateful mode) with a load balancer in the front.

### Problem
The conversion queue size in Gotenberg looks unlimited.
So Gotenberg will keep accepting a new request no matter how many pending conversion is. 

End up the instances may:
- Be easily overloaded if there is a spike or unbalanced traffic
- Most of the requests will keep being timeout (loop in client side: timeout->retry->timeout->retry...)
- The overloaded instances cannot be recovered even scale up more instances after a while
- A possibility that Gotenberg started a conversion but the API request just timed out at the same time (wasted conversion)

### Suggestion
It would be good if having an option to limit the queue size of LibreOffice stateful mode.
And it will **throttle/reject the new request immediately** (avoid too many requests waiting for timeout) when there are a lot of pending conversions (based on `libreoffice_listener_queue_length`).

Then, client side can monitor easily and based on the rejected number to scale up more instances

Thanks and appreciated! 🙏

**Comment by gulien** [comment]
Hello @NathanLamSeekasia,

Thanks for the well written issue!

It make sense, alas, I don't have much time to implement a solution right now. PR welcome though 😄

**Comment by timgrohmann** [comment]
I think I can look into this and create a PR. We're also running into the issue of "old" Gotenberg instances only responding with timeouts, even if no documents are sent for a long time.

If I understand the code correctly, the queue is not specific to the LibreOffice module, so adding a parameter to set a maximum queue size would influence all modules.

Would that be acceptable?

**Comment by gulien** [comment]
Hey @timgrohmann 👋

Both the Chromium and LibreOffice modules have their own queue length, although they are both using the supervisor struct. I guess one could implement a solution in the [Run](https://github.com/gotenberg/gotenberg/blob/975a9f53444173a695eac7640b9fba7cf5fa46e2/pkg/gotenberg/supervisor.go#L169) method, for instance, returning an error immediately if the queue size is above a threshold.
