### ISSUE TITLE
Support for conversion of documents inside ZIP files

### ISSUE THREAD

**Issue by halcy** [gotenberg/gotenberg#466]
I'm trying to figure out what the best way to add some form of support for ASIC-E files to paperless-ngx. ASIC-E is a signed container format - it's effectively a zip file that stores one or more documents and cryptographic signature metadata for the files. It's a standardized format, but mostly used in Estonia, where it is the default for any kind of contract or such that needs signing (electronic signatures are legally recognized and fairly common here). A simple way to support this format would be if the importer - using Gotenberg - could just transparently convert the document (or documents, though typically it is just one) inside of the asic-e zip archive.

**Comment by gulien** [comment]
Hello @halcy,

That's a really specific feature 😄 it should be feasible, but, right now, I do not have enough time to prioritize it, alas.

**Comment by gulien** [comment]
Closing this as this is a really specific use case and I don't have the time to prioritize it and implement it.
