### ISSUE TITLE
Cloud run and Kubernetes documentation

### ISSUE THREAD

**Issue by gregor-srdic** [gotenberg/gotenberg#467]
I can not express enough how frustrating the documentation on deploying this docker image on Kubernetes or cloud run is. Is it that hard or time-consuming for someone with efficient knowledge to write a "step-by-step" installation guide?
I am a front-end developer and I am not familiar with server-side approaches - but I honestly believe this is a quite "repetitive" task and could easily be well documented for someone like me.

**Comment by gregor-srdic** [comment]
[this](https://stackoverflow.com/questions/66316490/how-to-pull-docker-hub-image-to-google-cloud-run) helped me to understand the procedure
- install [gcloud cli](https://cloud.google.com/sdk/gcloud)
- install [docker desktop](https://www.docker.com/products/docker-desktop/)
- open google cloud shell (gcloud cli) and 
> - run `gcloud auth configure-docker`
> - run `docker pull gotenberg/gotenberg:7-cloudrun`
> - run `docker tag gotenberg/gotenberg:7-cloudrun gcr.io/<MY_PROJECT_ID>/gotenberg`
> - run `docker push gcr.io/<MY_PROJECT_ID>/gotenberg`
> - run `gcloud run deploy --image=gcr.io/<MY_PROJECT_ID>/gotenberg --port=3000 --region=europe-west3 --allow-unauthenticated --platform=managed --command=gotenberg gotenberg`

Probably I also had to select the cloud project <MY_PROJECT_ID> to be used or log into google cloud account somewhere along the way :)

Hope this helps someone with the same frustration.

**Comment by janswist** [comment]
Didn't worked for me. Seems like something changed in the meantime.

https://github.com/gotenberg/gotenberg/issues/90#issuecomment-1255100700

**Comment by cobraz** [comment]
I would love to write out some documentation on how to deploy it on Kubernetes and Cloud Run once we land

**Comment by janswist** [comment]
@cobraz found the solution. There is one thing to change in what @gregor-srdic listed.

Instead of:
`docker pull gotenberg/gotenberg:7-cloudrun` (I personally use `latest-cloudrun`)

You use this:
`docker pull --platform linux/amd64 gotenberg/gotenberg:7-cloudrun`

So the difference is to add `--platfrom linux/amd64` param to make sure we pull the image Google Cloud Run can deploy.
