### ISSUE TITLE
Support for transferMode: ReturnAsStream for larger PDFs from chromium?

### ISSUE THREAD

**Issue by AndrewJDR** [gotenberg/gotenberg#474]
Gotenberg currently has the issue of errors like `Too large write data is pending: size=725124416, max_buffer_size=268435456` when outputting large PDFs using chromium. Puppeteer fixed [this issue](https://github.com/puppeteer/puppeteer/issues/4563) by using the `transferMode: "ReturnAsStream"` option of the Page.printToPDF chromium call. Here's a reference to the puppeteer change:
https://github.com/puppeteer/puppeteer/pull/4587/files

And a reference to the relevant issue comment https://github.com/puppeteer/puppeteer/issues/4563#issuecomment-500686119 -
> In other words, DevTools protocol messages are limited to 256Mb in DevTools->Clients direction.
> The limit will go away once we teach Chromium to return PDFs as streams: https://crbug.com/748956

Are there plans to have gotenberg use streams as well to overcome this limitation?

**Comment by gulien** [comment]
Last time I checked, it was not working properly, but I can give it a try again 👍

**Comment by jasoncodes** [comment]
FYI I implemented streaming with minimal effort on our fork of Gotenberg 6.x: https://github.com/ennova/gotenberg/commit/24e596fcda38aee9b923a3db3d087ba7158f185b. It has been very reliable for us.
