### ISSUE TITLE
Gotenberg-generated PDF is much larger than print-view-generated one

### ISSUE THREAD

**Issue by thokari** [gotenberg/gotenberg#479]
Hello, 

I am evaluating Gotenberg, and I observed that the resulting PDF generated via Gotenberg is about 5 times the size of the seemingly identical PDF generated via the print view in Chrome. (~250KB vs. ~ 1.2MB)

What could be the reason for this and how could I debug this?

**Comment by gulien** [comment]
What platform are you using (`amd64`, `arm64`, ?) ?

What’s your Chrome version?

**Comment by thokari** [comment]
I observed this on a Windows 10 machine, running latest version of Chrome.

**Comment by gulien** [comment]
Hello @thokari,

Not sure why it's happening. Do you also see you see this difference using the demo?

**Comment by gulien** [comment]
Thanks for the feedback!
