### ISSUE TITLE
Hanging chromium processes

### ISSUE THREAD

**Issue by makarychev13** [gotenberg/gotenberg#480]
**Version**
Gotenberg 7.5.3
go 1.18.3

**Description of the problem**
Child chromium processes keep running after pdf conversion. And these processes die only after restarting the application. This problem was "fixed" in [this PR](https://github.com/gotenberg/gotenberg/issues/103). 

There is a similar open issue in [chromedp](https://github.com/chromedp/chromedp/issues/752).

**Code example**
```go
package main

import (
	"bytes"
	"context"
	"io"
	"mime/multipart"
	"net/http"
	"os"
)

func main() {
	var buf bytes.Buffer

	//read html from disk
	html, err := os.ReadFile("index.html")
	if err != nil {
		panic(err)
	}

	//prepare http request
	w := multipart.NewWriter(&buf)

	fw, _ := w.CreateFormFile("files", "index.html")
	if _, err := io.Copy(fw, bytes.NewReader(html)); err != nil {
		panic(err)
	}

	if err = w.Close(); err != nil {
		panic(err)
	}

	req, err := http.NewRequestWithContext(context.Background(), http.MethodPost, "http://127.0.0.1:3000/forms/chromium/convert/html", &buf)
	if err != nil {
		panic(err)
	}
        req.Header.Set("Content-Type", w.FormDataContentType())

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		panic(err)
	}

	//save pdf to disk
	var pdf bytes.Buffer
	if _, err = io.Copy(&pdf, resp.Body); err != nil {
		panic(err)
	}

	if err := os.WriteFile("index.pdf", pdf.Bytes(), 0666); err != nil {
		panic(err)
	}
}
```

**Effects**
![image](https://user-images.githubusercontent.com/15948628/180788360-8092b754-dd90-40ab-933b-f72588c078f4.png)

**Comment by ismurov** [comment]
Hi, @gulien. 👋

We found the problem. We just redefine ENTRYPOINT of Docker container while using in K8S by [command](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/) property instead using arguments. And Tini was not used in our pods. Ha-Ha!

We apologize for the trouble.
