### ISSUE TITLE
Does libreoffice api support scale setting?

### ISSUE THREAD

**Issue by tair-rhyme** [gotenberg/gotenberg#483]
Hello,

Is there a way to pass API scaling mode of sheets as below. It gives a chance to fit big cells into page.

<img width="755" alt="scaling mode" src="https://user-images.githubusercontent.com/2725761/182567669-4f3cd4d8-4cff-49f3-9ab4-bd6781d19815.png">

**Comment by gulien** [comment]
Not at the moment 😅 no ETA either

**Comment by gulien** [comment]
It does not seem to exist as a PDF export option: https://help.libreoffice.org/latest/en-US/text/shared/guide/pdf_params.html
