### ISSUE TITLE
Gotenberg can't process rather big files with unoconv (>7MB)

### ISSUE THREAD

**Issue by mrexox** [gotenberg/gotenberg#490]
Hey! I run Gotenberg in Cloud Run. I noticed that handling big files (like 4-7MB) results with `503`, which is the following error indeed:

```
{"level":"error","ts":1661960854.0608382,"logger":"api","msg":"convert to PDF: unoconv PDF: context done: context deadline exceeded","trace":"42e955cc-6d63-49a1-9f0c-fe707f4d61da","remote_ip":"172.24.0.1","host":"localhost:7890","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"got (https://github.com/sindresorhus/got)","status":503,"latency":120133426341,"latency_human":"2m0.133426341s","bytes_in":4076515,"bytes_out":19}
```

It doesn't work locally too, when I set `--api-timeout=120s`. I wonder, what can be the reason unoconv takes so long to process? Usually I need just the first page:

```
{"level":"debug","ts":1661960736.527761,"logger":"api.formslibreofficeconvert.usrbinunoconv","msg":"start unix process: /usr/bin/unoconv --no-launch --format pdf --port 40805 -vvv --export PageRange=1-1 --output /tmp/588094bf-0c00-4173-9ddb-6fd4d2be14e2/414618c3-86ae-48e3-9cbf-1356dafb12dc.pdf /tmp/588094bf-0c00-4173-9ddb-6fd4d2be14e2/file.pptx","trace":"42e955cc-6d63-49a1-9f0c-fe707f4d61da"}
```

I have a limit of 1GB in Cloud Run and locally I have 700-1000MB free RAM. Maybe this is not enough?

Cloud Run: `gotenberg:7.4.3-cloudrun`
Locally: `gotenberg:7`

**Comment by gulien** [comment]
Hello @mrexox,

It might be related to https://github.com/gotenberg/gotenberg/issues/474.

**Comment by mrexox** [comment]
@gulien, it might be, but I use LibreOffice endpoint, not Chromium. And my files are much smaller than 256MB. Everything works fine with 20-30KB files :thinking: I guess there is a problem related to unoconv, but I'm not sure.

**Comment by gulien** [comment]
Sorry, totally missed the point 😅

Best option for now is to increase the timeout I guess. You may also take look at this issue https://github.com/gotenberg/gotenberg/issues/464 for the stateless mode.

**Comment by mrexox** [comment]
Yes, I already use stateless mode. I'll try it out. 
But it is sad that a few meg file might take more than 2min extracting just the first page :confused:

**Comment by gulien** [comment]
I know, but LibreOffice is the limiting factor here 😕 You could try the latest version (`7.5.4`), with some luck it might work better.

**Comment by gulien** [comment]
@mrexox Here are some related issues:

* https://github.com/gotenberg/gotenberg/issues/459
* https://github.com/gotenberg/gotenberg/issues/407
* https://github.com/gotenberg/gotenberg/issues/465
* https://github.com/gotenberg/gotenberg/discussions/492

A "solution" seems to also increase the CPU/Memory available to Gotenberg.

**Comment by gulien** [comment]
Closing this for now.
