### ISSUE TITLE
Scenario: Using webhook to upload generated PDF to a pre-signed AWS S3 URL.

### ISSUE THREAD

**Issue by gulien** [gotenberg/gotenberg#495]
Scenario: Using webhook to upload generated PDF to a pre-signed AWS S3 URL.

The webhook middleware provides a `Content-Disposition` header. However, when I specify one via `Gotenberg-Webhook-Extra-Http-Headers` it is not considered. The webhook client processes the extra headers first and then internally generated headers, thus it appears not to be possible to override Gotenberg's content disposition headers.

See:

https://github.com/gotenberg/gotenberg/blob/d4c47cecf2ca1c35dc504073ce818862aa1bb180/pkg/modules/webhook/client.go#L46-L49

and

https://github.com/gotenberg/gotenberg/blob/d4c47cecf2ca1c35dc504073ce818862aa1bb180/pkg/modules/webhook/client.go#L72-L74

I can understand the rationale for preventing `Gotenberg-Webhook-Extra-Http-Headers` to override the client's headers. However, this precludes specifying a `Content-Disposition` when uploading to a service like `AWS S3`

_Originally posted by @gstark in https://github.com/gotenberg/gotenberg/discussions/494_

**Comment by gulien** [comment]
Hello @gstark,

Indeed, I did not want the user to mess with « default » headers, but it seems that in some cases it may actually be required.

Out of curiosity, what’s wrong with the `Content-Disposition` header from Gotenberg?

**Comment by gstark** [comment]
The `Content-Disposition` header from Gotenberg uses a UUID filename.

I dug a little deeper and it does appear that setting `Gotenberg-Output-Filename` applies and sets the `filename` part of the content-disposition header I care most about. With this, I have no need to update the header.

It might help to make a documentation update to `/docs/modules/webhook` to refer back to `/docs/modules/api#output-filename-multipart` to detail how the `Content-Disposition` header is generated and how it might be modified.

**Comment by gulien** [comment]
Thanks for the heads up @gstark, I've updated the documentation.
