### ISSUE TITLE
Long-running Chrome instance

### ISSUE THREAD

**Issue by gulien** [gotenberg/gotenberg#498]
Like LibreOffice, it could be interesting to have this behavior performance wise with some restart mechanism to avoid memory leaks.

**Comment by janswist** [comment]
I noticed that after couple of days of not using the instance on Google Cloud Run usually the first call returns 503 Service Unavailable error.

What I found in logs I paste below:
![image](https://user-images.githubusercontent.com/5583954/196454322-e0d7d63d-6132-4792-a4b5-f8871836e78c.png)

**Comment by gulien** [comment]
Closing this as it has been implmented.
