### ISSUE TITLE
Cloud Run error 'failed to load /usr/bin/tini'

### ISSUE THREAD

**Issue by janswist** [gotenberg/gotenberg#505]
https://github.com/gotenberg/gotenberg/blob/main/build/Dockerfile.cloudrun seems like it should work out of the box, but it's not. 

Getting this error: 
`terminated: Application failed to start: Failed to create init process: failed to load /usr/bin/tini: exec format error`

What can I do about it?

**Comment by cobraz** [comment]
I'm having this issue too.

**Comment by gulien** [comment]
Hello @janswist, @cobraz,

It should indeed work out of the box, but I do not use Cloud Run at all so I may not be able to help. Keep me in the loop if you find something.

**Comment by cobraz** [comment]
I can try without `tini`, just to see if we can assume that is the cause or if we need to widen the search.

**Comment by gulien** [comment]
@cobraz also consider that Tini is required to reap zombie processes. On a short lived instance it should be OK though, but still.

**Comment by janswist** [comment]
> I can try without `tini`, just to see if we can assume that is the cause or if we need to widen the search.

How do you that?

**Comment by janswist** [comment]
> Hello @janswist, @cobraz,
> 
> It should indeed work out of the box, but I do not use Cloud Run at all so I may not be able to help. Keep me in the loop if you find something.

Who added Cloud Run part? Maybe we can tag that person and ask how they did it

**Comment by gulien** [comment]
I did, based on this comment: https://github.com/gotenberg/gotenberg/issues/90#issuecomment-543551353.

**Comment by janswist** [comment]
Hmm, whether it was tested or not - probably Google might have changed something.

I looked through https://gotenberg.dev/docs/get-started/cloud-run docs but nothing really on how to run it without this error. Any chance for an update in that matter?

**Comment by janswist** [comment]
Tried deploying with `gotenberg` command and this time got error with `gotenberg` instead of `tini`: `/usr/bin/gotenberg: exec format error`
<img width="249" alt="image" src="https://user-images.githubusercontent.com/5583954/192114931-c4b2555d-a7f0-465b-ae8a-7b95fb19c0c8.png">

**Comment by gulien** [comment]
`Tini` is now installed via `apt`, not via GitHub anymore. But it’s still here 😉

**Comment by janswist** [comment]
It's quite interesting that installing version 6.x is still working well. @gulien any ideas I could research to make version 7.x work?

**Comment by janswist** [comment]
> > It's quite interesting that installing version 6.x is still working well
> 
> Didn't it failed because of a permission error?

No, and the container I deployed with version 6.x a year ago is still going also. So old container and fresh container (both 6.x) are working fantastic.

> > any ideas I could research to make version 7.x work?
> 
> The only relevant issue I have found so far: https://stackoverflow.com/questions/66127933/cloud-run-failed-to-start-and-then-listen-on-the-port-defined-by-the-port-envi

I have none of the errors mentioned there. I have permission issue.

> > GCP does mention on this [page](https://cloud.google.com/run/docs/reference/container-contract) here that Executables in the container image must be compiled for Linux 64-bit. Cloud Run specifically supports the Linux x86_64 ABI format.
> 
> Which is obviously the case with Gotenberg:
> 
> <img alt="Capture d’écran 2022-09-26 à 16 26 11" width="1189" src="https://user-images.githubusercontent.com/8983173/192302048-0318df2b-535b-45b0-8a05-4bf536448391.png">
> 
> Yet, as you can see, someone somehow downloaded the `linux/arm64` variant. I wonder if it's your case (dunno how though, because CloudRun should select the image with the correct platform).

That's actually interesting. How do I check what version got actually deployed on Google Cloud Run?

P.S. Sorry for late response, was out of a couple of days

**Comment by janswist** [comment]
Can I actually pull this specific `7.6.0-cloudrun` version? I never seen it before

**Comment by janswist** [comment]
So after deploying `latest-cloudrun` I got this error:
![image](https://user-images.githubusercontent.com/5583954/193454622-2b7aead9-7923-40ad-800c-c6f39de7ced9.png)

Based on this procedure: https://github.com/gotenberg/gotenberg/issues/467#issuecomment-1155596176 (so port is set to 3000 and command run is `gotenberg`)

**Comment by janswist** [comment]
Thanks to @gulien's clue and [this answer](https://stackoverflow.com/a/60116565/2570350) I found the solution:

`docker pull --platform linux/amd64 gotenberg/gotenberg:latest-cloudrun`

This is the image you want to pull to make sure you got the one that Cloud Run can deploy.
