### ISSUE TITLE
Converter doesn't work properly with DOCX files

### ISSUE THREAD

**Issue by ahmad2702** [gotenberg/gotenberg#506]
Hello! 

I run Gotenberg 7.6.0 in k8s. I noticed that handling small DOCX files (~200-500KB) fails with status 503 and with following error message: 
`{"level":"error","ts":1663864359.1665294,"logger":"api","msg":"convert to PDF: unoconv PDF: context done: context deadline exceeded","trace":"16a6c3a6-61e9-4e42-bda6-94aa43d3f46f","remote_ip":"172.17.0.1","host":"localhost:3000","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"Apache-HttpClient/4.5.10 (Java/1.8.0_202)","status":503,"latency":600003005400,"latency_human":"10m0.0030054s","bytes_in":295267,"bytes_out":19}`

I have also applied all suggestions from https://gotenberg.dev/docs/get-started/kubernetes. The combination of the following parameters doesn't help:
- --uno-listener-start-timeout=60s
- --uno-listener-restart-threshold=0

Finally, I created one single dummy [Test.docx](https://github.com/gotenberg/gotenberg/files/9628130/Test.docx) file and started gotenberg in docker on my local machine (CPU i9 + 16GB RAM) with the following command:
`docker run --rm -p 3000:3000 gotenberg/gotenberg:7.6.0 gotenberg --api-disable-health-check-logging --uno-listener-restart-threshold=0 --api-timeout 1200s`
With the "curl" I tried to convert my dummy file:
`curl --noproxy '*' --request POST 'http://localhost:3000/forms/libreoffice/convert' --form 'files=@"Test.docx"' -o Test.pdf`
After 20 minutes, I didn't get my PDF file.

Why is it not able to convert the file, which is so small? Or maybe I'm doing something wrong?

**Comment by gulien** [comment]
Hello @ahmad2702,

LibreOffice does struggle to convert `.docx` file for reasons I don't know. It works relatively well for "small" size files, but it's another story when they become bigger.

Out of curiosity, could you try to convert your test file with the LibreOffice software directly?

**Comment by ahmad2702** [comment]
@gulien, thank you for your comment.
I have tried to convert my test file using LibreOffice and... the same problem!

Can you give any tips on how to work around this problem?

**Comment by gulien** [comment]
@ahmad2702 alas, I do not have real workarounds. Still, you may try one of the following:

* Downgrade to version 6 (which contains an earlier version of LibreOffice).
* Convert your `docx` files to a `odt`.
* Use the Chromium module, meaning converting your templates to HTML.
* Switch to some paid services.

**Comment by gulien** [comment]
@senath999 please post your issue in https://github.com/yumauri/gotenberg-js-client.

**Comment by gulien** [comment]
Closing this as there is 0 known solution on my side.
