### ISSUE TITLE
Generate QR codes from HTML and Markdown

### ISSUE THREAD

**Issue by quinncomendant** [gotenberg/gotenberg#515]
Does Gotenberg have a feature that can generate a QR code into the PDF? 

Currently, I'm using [mPDF](https://mpdf.github.io/what-else-can-i-do/barcodes.html) which will generate a QR code if the HTML contains this markup:

```html
<barcode code="Your message here" type="QR" class="barcode" size="0.8" error="M" />
```

mPDF is difficult to use and CSS support is limited, so I prefer to use Gotenberg.

**Comment by gulien** [comment]
Hello @quinncomendant,

Best option is to try to convert an HTML document with this markup. Gotenberg uses Chromium to di the heavy lifting, so if Chromium handles it, Gotenberg does too 😉
