### ISSUE TITLE
Segmentation Fault Parsing .docx

### ISSUE THREAD

**Issue by stumpylog** [gotenberg/gotenberg#518]
When attempting to convert a fairly simple .docx file into a PDF, I seem to decently often get a segmentation fault logged by the Docker container.

The file can be found here: https://github.com/paperless-ngx/paperless-ngx/tree/dev/src/paperless_tika/tests/samples

Container Logs: 
  - https://github.com/paperless-ngx/paperless-ngx/actions/runs/3211765042/jobs/5250163966#step:28:17
  - https://github.com/paperless-ngx/paperless-ngx/actions/runs/3211597486/jobs/5249878747#step:24:16

When the second run was re-run, the same file conversion happened without issue: https://github.com/paperless-ngx/paperless-ngx/actions/runs/3211597486

Initial runs above were with 7.4, I have not seen it with 7.6 after updating the action's image version, so it seems fixed, though it's infrequent enough I'm not yet positive the version update fixed it.

**Comment by gulien** [comment]
Hello @stumpylog,

Alas, LibreOffice is not as stable as one would expect. I cannot do much here, but keeping the Gotenberg image up-to-date may help (or not, heh).

**Comment by stumpylog** [comment]
I haven't seen this yet with 7.6, so in my view, this is resolved by the upgrade.  We'll have to keep more in sync with our versions.
