### ISSUE TITLE
Gotenberg generates larger PDFs than Chromium, AthenaPDF and Firefox

### ISSUE THREAD

**Issue by wouterj** [gotenberg/gotenberg#521]
We recently switched from AthenaPDF to Gotenberg, as AthenaPDF is unmaintained. We noticed a significant increase of file size in the generated PDFs. This unfortunately broke our integration with other tools, which enforce a file size limit for our PDFs.

I noticed this was reported before (#479), but the suspected issue (*"I suspect it has something to do with images that are being repeated on every page, like in a header for example."*) is incorrect.

When run using the demo instance of Gotenberg, using the "https://sparksuite.github.io/simple-html-invoice-template/" test input from the docs:

<details>
<summary>Old (slightly wrong) results</summary>

| Tool | File size | File |
| --- | --- | --- |
| Gotenberg | 104 KB | [gotenberg.pdf](https://github.com/gotenberg/gotenberg/files/9754951/gotenberg.pdf) |
| Chromium ("Print as PDF" in Brave Browser) | 85 KB | [chromium.pdf](https://github.com/gotenberg/gotenberg/files/9754959/chromium.pdf) |
| AthenaPDF | 52 KB | [athenapdf.pdf](https://github.com/gotenberg/gotenberg/files/9754963/athenapdf.pdf) |
| Firefox | 26 KB | [firefox.pdf](https://github.com/gotenberg/gotenberg/files/9754993/firefox.pdf) |

</details>

| Tool | File size | File |
| --- | --- | --- |
| Gotenberg | 104 KB | [gotenberg-1.pdf](https://github.com/gotenberg/gotenberg/files/9756285/gotenberg-1.pdf) |
| Chromium | 85 KB | [chromium-1.pdf](https://github.com/gotenberg/gotenberg/files/9756288/chromium-1.pdf) |
| AthenaPDF | 60 KB | [athenapdf-1.pdf](https://github.com/gotenberg/gotenberg/files/9756297/athenapdf-1.pdf) |
| Firefox | 33 KB | [firefox-1.pdf](https://github.com/gotenberg/gotenberg/files/9756292/firefox-1.pdf) |

I don't have any knowledge about the PDF format nor communicating with Chromium instances, so I'm afraid I can't really help debugging this further.

**Comment by dkarlovi** [comment]
Gotenberg embedded Arial here, Athena embedded Liberation Sans.

**Comment by wouterj** [comment]
Hmm, good catch. I've double checked our real production PDFs (which unfortunately contain consumer data, so I can't share them here) and they do embed the same fonts. However, the difference is 30 KB vs 264 KB between AthenaPDF and Gotenberg there.

**Comment by gulien** [comment]
Hello @wouterj,

I wonder if the header/footer feature is the root cause here. If you don't specify a header/footer, [I use an empty HTML template for both](https://github.com/gotenberg/gotenberg/blob/main/pkg/modules/chromium/chromium.go#L225). The more pages, the more difference in size.

**Comment by wouterj** [comment]
Hi @gulien, thanks for the quite response here.

I've tried passing empty file as header/footer and tried commenting `WithHeaderTemplate()`/`WithFooterTemplate()` locally and building Gotenberg. In both cases, it seems like cdproto defaults to a header/footer with default information - increasing the file size of that one page to 116 KB. Passing an incomplete HTML document as header & footer results in the same file size as original.

Is there something specific I should test regarding the header/footer?

**Comment by wouterj** [comment]
Something different that I did notice when comparing the resulting PDFs in Inkscape: AthenaPDF renders no background, whereas Gotenberg and Chromium render a white background (even when passing `--form 'printBackground="false"'`). So this does not explain the difference between Gotenberg and Chromium, but it might explain a bit of the big difference with AthenaPDF.

**Comment by gulien** [comment]
Actually, the [WithDisplayHeaderFooter](https://github.com/gotenberg/gotenberg/blob/0e1e9b9cf34c0f6ff8f03af61257e150bb6cc613/pkg/modules/chromium/chromium.go#L762) method may be the culprit, but I’m not so sure anymore.

Indeed, I’m using the Chrome DevTool Protocol, so I tried to look for similar issues with `puppeteer` and it seems to be related to the [background](https://github.com/puppeteer/puppeteer/issues/458#issuecomment-378903025) or [images](https://github.com/puppeteer/puppeteer/issues/458#issuecomment-711167965).

AFAIK, AthenaPDF is not using a Chromium based browser, so comparing the two may be difficult. Regarding the differences between Brave versus Gotenberg (+ Chromium), I have no idea 😅

**Comment by gulien** [comment]
Related: https://github.com/gotenberg/gotenberg/issues/226

**Comment by wouterj** [comment]
@gulien thanks for the information. If you want, I can try to write a contribution using your suggestions in https://github.com/gotenberg/gotenberg/issues/226#issuecomment-1275841549 tomorrow

**Comment by wouterj** [comment]
I've tried some more things and unfortunately, `WithPrintBackground(false)` and `WithDisplayHeaderFooter(false)` don't make any difference in the file size. Opening the result PDF in Inkscape, I can also still see the white background path. However, this seems to be a Chromium bug as printing from the browser without header/footer and bg also still generates the white background.

But, I did find another very interesting issue: https://github.com/puppeteer/puppeteer/issues/3939 When using web fonts, it seems like the file size increases by a lot. Installing the custom font locally in the docker container saves a massive amount of file size (49% in a real sample):
* With Google web font: 264 KB
* With locally installed version of that font: 131 KB

I guess for now, creating a custom container build with the font installed will be good enough for us. But feel free to ping me if you need any testing about the background feature, if you get to writing it.

**Comment by gulien** [comment]
Re @wouterj.

Regarding the background, it's actually a different thing than `WithPrintBackground` 😄, i.e., I have to override the default background color with a transparent one (see [the puppeteer implementation](https://github.com/puppeteer/puppeteer/blob/87c08fd86a79b63308ad8d46c5f7acd1927505f8/packages/puppeteer-core/src/common/Page.ts#L1414)).

Good catch with the fonts! See also https://gotenberg.dev/docs/customize/fonts for your custom Docker image 😉

**Comment by wouterj** [comment]
> Good catch with the fonts! See also https://gotenberg.dev/docs/customize/fonts for your custom Docker image :wink: 

Oh, I completely missed this article. Sorry for taking your time about something that was already documented! :facepalm: 

I propose cross-referencing the font article in Chromium: https://github.com/gotenberg/gotenberg.dev/pull/5 (I know it's mentioned in "Header & footer" already, but I didn't see that one as I'm not interested in headers & footers)

**Comment by gulien** [comment]
> Oh, I completely missed this article. Sorry for taking your time about something that was already documented!

It may actually explain the differences between a local Chromium browser and Gotenberg, so thanks for making it obvious 😄 

I wonder if the transparent background will change much, but maybe it explains the differences between AthenaPDF and Gotenberg.

**Comment by wouterj** [comment]
> I wonder if the transparent background will change much, but maybe it explains the differences between AthenaPDF and Gotenberg.

I honestly doubt this. Printing the sample invoice using Firefox gives an even smaller file size, but it does contain the white background. However, the difference in PDF engines is even harder to investigate :smiley: 

Interestingly, AthenaPDF uses Electron, which also uses Chromium (and its Skia PDF back-end, but apparently an older version). So something must have changed in Chromium/Skia over the past years that increased file size, but I don't want to go even deeper in the PDF file size rabbit hole than I already am.

Closing this issue, as I think there is not much of an action left anymore.

**Comment by HulkOz** [comment]
I used fork: https://github.com/Vrex123/gotenberg-ghostscript and file size of PDFs is smaller than this repo.

Example: "https://youtube.com" to PDF:
This repo - 
![image](https://user-images.githubusercontent.com/37548413/196280119-925999e8-5e74-40f2-8289-7758a7f952a8.png)

gotenberg-ghostscript repo -
![image](https://user-images.githubusercontent.com/37548413/196280282-813068be-26ff-4cd1-9e83-94a3b895e921.png)

My POST request BODY for gotenberg-ghostscript:
![image](https://user-images.githubusercontent.com/37548413/196280919-bcbda6c3-d096-4856-9061-a931b89cca80.png)

**Comment by gulien** [comment]
@HulkOz I'm pretty sure that GhostScript is doing some optimization when you ask it to convert to `PDF/A-3b`. I would love to have it in the "standard" version of Gotenberg, alas (for us), its licensing does not allow it.

**Comment by wouterj** [comment]
Yes, Ghostscript can reduce the file size even more (which is to be expected from a compression engine :wink: ). In a 300 page test, we went from 27 MB (webfont) to 12 MB (local font) to 1.1 MB (Ghostscript compression).

(btw, isn't the unofficial module also violating the agpl license?)

**Comment by gulien** [comment]
Yes the MIT license is not compatible 😅
