### ISSUE TITLE
Websocket Timeout Reached

### ISSUE THREAD

**Issue by deyanginev** [gotenberg/gotenberg#524]
We are using Gotenberg to convert HTML to PDF in stages by generating chunks of PDFs which afterwards are merged to a single PDF file. For larger files (4-5 MBs) we're getting the following error:

"msg":"convert HTML to PDF: convert to PDF: chromium PDF: websocket url timeout reached".

Here's a sample log:

```
{"bytes_in":-1, "bytes_out":21, "host":"html-to-pdf:8080", "latency":2.0628581388E10, "latency_human":"20.628581388s", "level":"error", "logger":"api", "method":"POST", "msg":"convert HTML to PDF: convert to PDF: chromium PDF: websocket url timeout reached", "path":"/forms/chromium/convert/html", "referer":"", "remote_ip":"10.36.0.149", "status":500, "trace":"5846d289-55f2-42af-824c-afacd2832933", "ts":1.6655944616615608E9, "uri":"/forms/chromium/convert/html", "user_agent":"node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"}
```
Any help will be appreciated!

**Comment by gulien** [comment]
Hello @deyanginev!

It looks like there is a default timeout in `chromedp` (library for interacting with the Chrome DevTool Protocol) that I've totally missed:

> Chrome will sometimes fail to print the websocket, or run for a long
> time, without properly exiting. To avoid blocking forever in those
> cases, give up after a specified timeout.

And this timeout default value is 20 seconds, which seems to correlate with what you have in your logs.

I guess for *large" file, it is not enough. 

I need to make it work with the timeout mechanism from Gotenberg.

**Comment by gulien** [comment]
@deyanginev could you test with `gulnap/gotenberg:websocket-timeout-reached` ?

**Comment by deyanginev** [comment]
Hi @gulien,

Thanks for the fast reaction!

We will perform some tests and will let you know how things are looking on our side.

**Comment by gulien** [comment]
Yep, `—api-timeout` is the property I use across the application to handle the maximum duration of a request. 

In our case, I set the websocket timeout by comparing the time between now and when the maximum duration will end (if that make sense).

**Comment by deyanginev** [comment]
@gulien - this seems to fix the issue on our side. We will continue testing and I will get back to you in case we notice something unexpected.

Thank you!

**Comment by gulien** [comment]
Thanks for the feedback!

**Comment by deyanginev** [comment]
@gulien - sorry for writing again - this is going into the next version I suppose. Do you have a timeframe. It's not urgent, just to make sure we update when possible.

**Comment by gulien** [comment]
Version `7.6.2` is available 😉
