### ISSUE TITLE
error after startup: long-running LibreOffice listener unhealthy (with almost no calls)

### ISSUE THREAD

**Issue by janswist** [gotenberg/gotenberg#529]
I deployed new fresh instance on Cloud Run and that's what I got on the first call:
![image](https://user-images.githubusercontent.com/5583954/197334186-1068c266-606f-4e77-b12d-b12c5c03bb47.png)

How is that even possible? It wasn't up even for couple of minutes and it's already down?

![image](https://user-images.githubusercontent.com/5583954/197334274-02a4b6e1-73ad-41a8-b39a-dbf68a6e15ce.png)
Same configuration as other instance (just different region, but it shouldn't matter at all). Completely confused, other two instances are working just fine.

P.S. Also, how to restart an instance without redeploying it?

**Comment by gulien** [comment]
I don't know @janswist. A failed health check should restart Gotenberg AFAIK (via your orchestrator.)

**Comment by mmahalwy** [comment]
yeah getting this quite often too :(

**Comment by janswist** [comment]
> I don't know @janswist. A failed health check should restart Gotenberg AFAIK (via your orchestrator.)

I did couple of health checks and it didn't do much. Is there any specific command to make sure it always restarts after finishing an operation? It's kinda unreliable so far on Cloud Run.

**Comment by janswist** [comment]
> yeah i deployed the normal docker to render and it works fine. for some reason cloudrun doesn't play nicely

Wondering the issue. I can only suspect cold starts, but I had similar issue with on-going instance (that is more expensive).

**Comment by mmahalwy** [comment]
yeah - i wonder if it's the cloundrun image? On Render, i deployed the regular image. Also on dev, using the regular image 🤷

**Comment by janswist** [comment]
> yeah - i wonder if it's the cloundrun image? On Render, i deployed the regular image. Also on dev, using the regular image 🤷

from what I know cloudrun image is just different operation system, not sure if there are actual changes in code (I suppose not or otherwise it would be hell to maintain the codebase). Wondering if @gulien will even have time to actually research that topic a little bit

**Comment by gulien** [comment]
I plan to take some time next week to find a solution or at least improve the LibreOffice management!

**Comment by mmahalwy** [comment]
@gulien that'd be awesome! fwiw, it works well on dev and on render, but not on cloud run :(

**Comment by janswist** [comment]
> @gulien that'd be awesome! fwiw, it works well on dev and on render, but not on cloud run :(

Same here. Localhost it just works brilliantly and blazing fast.

**Comment by mmahalwy** [comment]
Even on dev, seems like if I don't hit LibreOffice routes for a few mins, it will return internal server error on first one

**Comment by mmahalwy** [comment]
yeah can replicate this @gulien on your render.com instance too.

**Comment by ekeuus** [comment]
We have this issue as well since upgrading from 7.0.7 to 7.7.0. It seems the health check is not able to detect that the instance is bad and thus the bad instance is kept alive. We're using Cloud Run.

**Comment by gulien** [comment]
No ETA on a solution for this issue.

Yet, if you want a workaround (or the same behavior as earlier 7.x versions), you should go stateless with the property `—uno-listener-restart-threshold=0` (see https://gotenberg.dev/docs/modules/libreoffice).

**Comment by janswist** [comment]
> No ETA on a solution for this issue.
> 
> Yet, if you want a workaround (or the same behavior as earlier 7.x versions), you should go stateless with the property `—uno-listener-restart-threshold=0` (see https://gotenberg.dev/docs/modules/libreoffice).

@gulien like this? I'm not sure if I do it correctly:
![image](https://user-images.githubusercontent.com/5583954/200197075-403dc445-d246-40ec-bd90-5452a7feb0ee.png)

**Comment by gulien** [comment]
@janswist yes, exactly 😉

**Comment by jankrikava** [comment]
> No ETA on a solution for this issue.
> 
> Yet, if you want a workaround (or the same behavior as earlier 7.x versions), you should go stateless with the property `—uno-listener-restart-threshold=0` (see https://gotenberg.dev/docs/modules/libreoffice).

@gulien Hey Julien, thanks for the workaround. Is there also a similiar env variable for running Gotenberg as docker container?

**Comment by gulien** [comment]
No env variables, only flags (aka properties).

**Comment by janswist** [comment]
> No env variables, only flags (aka properties).

Sorry if that sounds silly, but how to do that? Never heard of it before nor I know how to put that flag on (so to speak)

**Comment by janswist** [comment]
@gulien in the meantime: which cloud provider do you know and recommend that is working 100% as intended? I just might move there until we know how to play Cloud Run. Thanks in advance!

**Comment by jankrikava** [comment]
@janswist I'm running it as App Service on Azure if that's an option for you. Here are my settings under Deployment Center:
![Azure App Service Deployment Center Settings](https://i.imgur.com/43Fejsk.png)

**Comment by janswist** [comment]
Hi @gulien just wondering if you maybe had time to peek into the Cloud Run problem - seems like a lot of people still choose it as their go-to provider

**Comment by janswist** [comment]
Tried `7.3.2-cloudrun` now, but I'm getting `Internal Server Error`

**Comment by gulien** [comment]
@janswist @jankrikava  @mmahalwy @ekeuus could you try the image gulnap/gotenberg:libreofficefix? It's using a downgraded version of LibreOffice (7.0.4) but with the Gontenberg 7.7.1 codebase.

**Comment by jankrikava** [comment]
@gulien Thanks for the quick fix 🙏 The first test runs are again running fast as usual. If something unexpected comes up, I'll let you know here the next few days.

**Comment by gulien** [comment]
@jankrikava Thanks for the feedback!

**Comment by mmahalwy** [comment]
@jankrikava @gulien whats the setup you have for cloudrun?

**Comment by gulien** [comment]
@mmahalwy I don't have a CloudRun setup, but it seems that the root cause for most issues related to the LibreOffice instability is related to its version.

**Comment by janswist** [comment]
> gulnap/gotenberg:libreofficefix

Don't know why I didn't get the email notification so sorry for the delay. Just deployed and so far it works brilliantly! Many thanks to you 🙏

**Comment by jankrikava** [comment]
@mmahalwy Tested locally and on Microsoft Azure as App Service. As @gulien described it shouldn't be affected by the environment nor PaaS being used.

**Comment by gulien** [comment]
Release `7.7.2` is now available with the fix. Please open a new issue if the problem still persist 😄
