### ISSUE TITLE
Styling issues with libreoffice conversion through gotenberg

### ISSUE THREAD

**Issue by rockyweng** [gotenberg/gotenberg#542]
Hi all,

I have styling issue with the weird dots on table of content for converting word to pdf from LibreOffice through Gotenberg.

Gotenberg version:

<img width="824" alt="gotenberg" src="https://user-images.githubusercontent.com/14155587/200734633-e1387693-daf1-46fb-96b9-74b7dd3bea77.png">

LibreOffice Headless conversion:

![LibreOffice_Headless](https://user-images.githubusercontent.com/14155587/200734934-89010ca0-a759-4496-bbe3-b7a34920d7e4.png)

Issues:
- There is no dot in the original word document however gotenberg conversion is printing dot
- No page number showing on the gotenberg version but it is showing on the direct conversion from libreoffice headless through CLI

Please let me know if I am missing something.

Thank you.

**Comment by gulien** [comment]
Related #541

**Comment by gulien** [comment]
Closing this for now. Feel free to reopen this issue if it happens on the latest Gotenberg version.
