### ISSUE TITLE
Merge not always working

### ISSUE THREAD

**Issue by vincentdurufle** [gotenberg/gotenberg#544]
Hello, 

I'm having two issues with the merge routes on the latest gotenberg version.
First one is the ordering of files with this.
```
    const formData = new FormData();
    for (const pdf of pdfs) {
      const idx = pdfs.indexOf(pdf);
      const image = await getPreSignedUrl(pdf.filename, 'pdf');
      const file = await axios.get(image, {
        responseType: 'arraybuffer',
      });
      formData.append('files', file.data, `pdf-${idx}.pdf`);
    }
``` 

When the loop hits the 10th index the pdf is merged with the tenth being after the index 1.
I'm currently using a workaround by adding 100 to the index so that it sort correctly.

Secondly I'm having an issue that is not always happening but seems to occur a lot when the instance has been running for a long time.
Basically it fails with a 500. Here is the log 
```
{"level":"error","ts":1667996857.9176066,"logger":"api","msg":"merge PDFs: merge PDFs with multi PDF engines: merge PDFs with PDFcpu: Read: xRefTable failed: pdfcpu: can't find last xref section; merge PDFs with PDFtk: unix process error: wait for unix process: exit status 1; merge PDFs with QPDF: unix process error: wait for unix process: exit status 2; merge PDFs with unoconv: method not available","trace":"abea84bd-5809-4205-a67a-c96961495d5e","remote_ip":"xxx.xxx.x.x","host":"gotenberg:3000","uri":"/forms/pdfengines/merge","method":"POST","path":"/forms/pdfengines/merge","referer":"","user_agent":"axios/0.26.0","status":500,"latency":294464611,"latency_human":"294.464611ms","bytes_in":-1,"bytes_out":21}
```

I have no problem generating pdfs otherwise.
After going through issues I tried setting the `"--uno-listener-restart-threshold=0"` in my docker-compose command but it doesn't seem to work.

Let me know if I can provide any further informations.

**Comment by gulien** [comment]
Hello @vincentdurufle,

Regarding the ordering issue, you should switch to letters (alphabetical ordering). See for instance https://github.com/gotenberg/gotenberg-php/blob/main/src/Index.php.

For the 500 failures, the restart threshold flag has 0 impact 😅 in your case, all PDF engines are failing. I suspect there is some issue with your PDF, but I cannot prove it either.

**Comment by vincentdurufle** [comment]
Thanks it was indeed a problem with a pdf not being correctly rendered causing all the merge to fail ! I switch to another lib for merging that enabled to load each pdf one by one and check if one is at fault before trying to merge enabling me to remove the faulty one (for anyone wondering I used pdf-lib). Thanks for the great work with gotenberg we are still using it to create PDF and it rocks !

**Comment by ytilotti** [comment]
I had a problem like this. It is necessary that the mime type is a pdf.

**Comment by DonCallisto** [comment]
We have the same problem but with file names with letters. When we overtake ten files, merging order is broken.

**Comment by DonCallisto** [comment]
> We have the same problem but with string file names. When we overtake ten files, merging order is broken.

Sorry, the issue seems to be into a library wrapper we use to communicate with server.
