### ISSUE TITLE
webgl is not supported?

### ISSUE THREAD

**Issue by robiXxu** [gotenberg/gotenberg#546]
Hey guys.
I'm trying to create a pdf of a page that contains webgl content (a map with some stuff on top of it)
![Screenshot 2022-11-14 at 11 42 05](https://user-images.githubusercontent.com/1962141/201627185-ace65bc3-5c7e-420d-929e-977d1dda998f.png)

It doesn't work with the normal current flags. I'm getting 
```
trimblemaps-3.4.0.js:35 Error: Failed to initialize WebGL
```
I've checked `chrome://gpu` and `WebGL` `WebGL2` is disabled.
<img width="555" alt="Screenshot 2022-11-14 at 11 47 27" src="https://user-images.githubusercontent.com/1962141/201632232-c3f1b4eb-2e17-4cf4-a6a4-77d033d42ca8.png">
(I've set the `headless` flag to false so i could see the window through xquartz and debug easier)

I've opened an [issue on chromedp](https://github.com/chromedp/chromedp/issues/1190) because I initially assumed it was on their side

Made a playground to experiment different flags (mainly `--use-gl` & `--use-angle`).
https://github.com/robiXxu/chromedp-playground

**The goal was to get WebGL working with `swiftshader` (since gotenberg is running in a docker container and don't have access to a gpu)**

A contributer (Zekelu) pointed in the right direction and I was able to render webgl content inside my playground 

I tried to do the same thing in gotenberg however I'm not able to get webgl supported with the same flags.

I assumed that we need to install something and tried including mesa-utils & related packages in the Dockerfile as it was sugested by people on other packages which encountered the same issue
( eg https://github.com/DevExpress/testcafe/issues/2116 , https://github.com/accetto/headless-drawing-g3/blob/master/docker/xfce/README.md#using-openglwebgl-and-hw-acceleration )
```
    apt-get install cmake pkg-config mesa-utilslibglu1-mesa-dev freeglut3-dev mesa-common-dev libglew-dev libglfw3-dev libglm-dev libao-dev libmpg123-dev -y &&\
```

But after a lot of trial and error I've figured that it might be time to open an issue and ask others if they found themselves in the same situation and how they overcome it?

**Comment by AlexanderMatveev** [comment]
Faced not working WebGL on macOS. I went through all the issues, but did not find a solution.

**Comment by robiXxu** [comment]
We found a workaround which works in a docker container.
We use a Xvfb to start a X virtual framebuffer which implements X11 display server protocol

**Dockerfile** changes:
```
RUN apt-get update -qq
RUN apt-get install -y xvfb ca-certificates tzdata
...

ENV DISPLAY=:99
ENV XVFB_WHD=1920x1080x16
ENV TINI_SUBREAPER=true
...
COPY /entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
...
ENTRYPOINT ["/entrypoint.sh"]
CMD [ "gotenberg" ]
```

**entrypoint.sh**
```
#!/bin/sh
echo "Starting X virtual framebuffer using: Xvfb $DISPLAY -ac -screen 0 $XVFB_WHD -nolisten tcp"
Xvfb "$DISPLAY" -ac -screen 0 "$XVFB_WHD" -nolisten tcp & sleep 3

echo "Executing main command"
/usr/bin/tini -- "$@"
```

**Comment by gulien** [comment]
Thanks for the details @robiXxu!
I think it is kind of overkill for the standard version of Gotenberg, but now I can redirect people to this thread if necessary 👍

**Comment by yhc44** [comment]
> We found a workaround which works in a docker container. We use a Xvfb to start a X virtual framebuffer which implements X11 display server protocol
> 
> **Dockerfile** changes:
> 
> ```
> RUN apt-get update -qq
> RUN apt-get install -y xvfb ca-certificates tzdata
> ...
> 
> ENV DISPLAY=:99
> ENV XVFB_WHD=1920x1080x16
> ENV TINI_SUBREAPER=true
> ...
> COPY /entrypoint.sh /entrypoint.sh
> RUN chmod +x /entrypoint.sh
> ...
> ENTRYPOINT ["/entrypoint.sh"]
> CMD [ "gotenberg" ]
> ```
> 
> **entrypoint.sh**
> 
> ```
> #!/bin/sh
> echo "Starting X virtual framebuffer using: Xvfb $DISPLAY -ac -screen 0 $XVFB_WHD -nolisten tcp"
> Xvfb "$DISPLAY" -ac -screen 0 "$XVFB_WHD" -nolisten tcp & sleep 3
> 
> echo "Executing main command"
> /usr/bin/tini -- "$@"
> ```
> 
> We also had to play a little bit with chromedp flags in `browser.go` (`func (b *chromiumBrowser) Start`)
> 
> ```
>     chromedp.Headless,
>     // chromedp.DisableGPU,
>     chromedp.NoSandbox,
>     chromedp.Flag("use-gl", "angle"),
>     chromedp.Flag("use-angle", "swiftshader"),
>     chromedp.Flag("enable-webgl", true),
>     chromedp.Flag("enable-threaded-compositing", true),
> ```

Thank you very much for this solution. It helped us a lot :)
