### ISSUE TITLE
Generating with Chromium is actually LibreOffice

### ISSUE THREAD

**Issue by NiklasBr** [gotenberg/gotenberg#548]
When sending an API request to `POST 'http://localhost:3000/forms/chromium/convert/url'` I expected the renderer to be Chromium and not LibreOffice. 

Is there a way to force usage of Chromium?

![image](https://user-images.githubusercontent.com/279826/203113101-fe3e34c1-f659-4179-81e1-d5f71b6e45da.png)

**Comment by gulien** [comment]
I guess you’ve requested a special format like `PDF/A-1` ? It’s LibreOffice that handles such a conversion AFTER the initial PDF conversion from Chromium.

**Comment by NiklasBr** [comment]
That noise you heard was me face-palming too hard. Thanks!
