### ISSUE TITLE
Status code is not considered when calling the webhook

### ISSUE THREAD

**Issue by doriandekoning** [gotenberg/gotenberg#550]
Currently it seems like the HTTP status code is not checked after a call to the webhook is made. Therefore if the server responds with a non 2xx status code this is not logged making it hard to monitor and debug. But I might be overlooking something.

The code where the response seems to be handled can be found in https://github.com/gotenberg/gotenberg/blob/main/pkg/modules/webhook/client.go#L76 here only `err` as return value is checked but `resp.Status` is never used.

If you're open to it I'd happily open a merge request with a small change to ensure it returns an error if the status code is >=400 to ensure the calling function can log it.

**Comment by gulien** [comment]
Hello @doriandekoning,

Good catch, feel free to open a PR. Just in case, could you also check the `client.do` method? It might also return an error on non `2xx` response.

**Comment by doriandekoning** [comment]
Good one, as far as I know it doesn't but I'll double check to be sure!

Hopefully I have some time tomorrow or monday to write a patch :)

**Comment by gulien** [comment]
Thanks @doriandekoning!
