### ISSUE TITLE
`print to PDF: Printing failed (-32000)` with 500 status code

### ISSUE THREAD

**Issue by patilpankaj212** [gotenberg/gotenberg#559]
Hello Team,

We are using gotenberg:7 to convert html to pdf.

While testing conversion of large html  to pdf we observed this failure a few times. And we were also able reproduce this issue with a few concurrent requests to convert small to moderate size html to pdf.

We couldn't find the root cause of the failure looking at the debug logs. Can you please let me know what is causing this issue?

Debug logs - 

[logs.txt](https://github.com/gotenberg/gotenberg/files/10138714/logs.txt)

**Comment by gulien** [comment]
Hello @patilpankaj212!

Looks like more an error from Google Chrome than Gotenberg. In your logs, it looks like your web page somehow crashed. 
Do you have enough memory for your instance?

**Comment by patilpankaj212** [comment]
Hello @gulien,

Thank you for your reply. 

We first encountered this issue with an instance with 1 CPU and 2 GB ram, when testing conversion of a large html to pdf (about 300 pages of tabular data). After that we encountered this issue when we tried some concurrent requests with smaller html files (about 50 pages of tabular data).

We thought it was a memory issue, and when we halved the instance configuration, we observed this issue occurring with smaller files as well (single request).

Is there any guide on how much memory and cpu the instance should be configured with (like memory consumed by gotenberg based on the size of the payload)? It would be of great help.

**Comment by gulien** [comment]
Hello @patilpankaj212,

There are, alas, no guides or else regarding the CPU/memory an instance should be configured with. I guess it also depends a lot of the use case.

I ran [some load testing scenarios](https://github.com/gotenberg/gotenberg/tree/6.4.4/loadtesting) back in version 6 though.

**Comment by patilpankaj212** [comment]
Thank you @gulien, the tests with k6 helps.
