### ISSUE TITLE
HTTP target url status code

### ISSUE THREAD

**Issue by vdeville** [gotenberg/gotenberg#561]
Hello

Is possible to detect non 200 status of the requested URL page when use chromium processer ?

```php
$response = Gotenberg::send($pdf);
$response->getStatusCode() // Get the API status code, not the URL used to generate pdf file
```

Thanks

**Comment by gregor-srdic** [comment]
> Do you mean the status code of the web page you're trying to generate? It is not possible atm.
> 
> You might use `failOnConsoleExceptions` as a workaround: https://github.com/gotenberg/gotenberg-php#fail-on-console-exceptions.

How can I use this "failOnConsoleExceptions" parameter in form data call from axios in node.js?
I am invoking the **https://.../forms/chromium/convert/url** URL and so far I have
```
const formData = new FormData();
formData.append("url", url, textPlainHeader);
formData.append("failOnConsoleExceptions", "true", textPlainHeader);
```
but it does not seem to work. Thanks!

**Comment by sww314** [comment]
We are going to try to use gotenberg to generate PDFs for many pages in our system. 

The issue we have seen is that there will be failures (401, 50x) and the PDF generation returns a 200 with an PDF of the error page. 

Going to look into the `failOnConsoleExceptions`, but just adding context that this would be very helpful addition.

**Comment by gulien** [comment]
Closing this in favor of #613.
