### ISSUE TITLE
support of .dotx and .xltx

### ISSUE THREAD

**Issue by ra-coder** [gotenberg/gotenberg#567]
dotx is supported by Libre Office. I can open these files using LibreOffice 4.4.1.2.

but not listed at supported extensions here
https://gotenberg.dev/docs/modules/libreoffice#route

Pls support .dotx and  .xltx

**Comment by gulien** [comment]
@ra-coder could you add those to this list https://github.com/gotenberg/gotenberg/blob/main/pkg/modules/libreoffice/uno/uno.go#L409 and check if it works as expected?

**Comment by gulien** [comment]
@ra-coder version 7.8.0 is now available!

**Comment by ra-coder** [comment]
thanks, will check if all works for us in new wersion

**Comment by ra-coder** [comment]
All works fine, thanks
