### ISSUE TITLE
Service stop working after some minutes iddle.

### ISSUE THREAD

**Issue by mdsantos1979** [gotenberg/gotenberg#568]
Hi, I have download docker container Version: 7.7.1

After running it, it works fine, I did like 20 ou 30 conversions to PDF  (always same file) with success, but if I stop using the service, lets say for 15 min, it doesn't work any more. I get a Internal Server Error.

The logs have this information:
2022-12-30 09:11:33 {"level":"error","ts":1672391493.3013377,"logger":"api","msg":"convert to PDF: unoconv PDF: unix process error: wait for unix process: exit status 6","trace":"c7315c8f-9d68-4df7-a4c6-92c355d381f2","remote_ip":"172.17.0.1","host":"bentley:3000","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"PostmanRuntime/7.30.0","status":500,"latency":262561800,"latency_human":"262.5618ms","bytes_in":47103,"bytes_out":21}

I'm running the container with this command:
docker run --rm -p 3000:3000 thecodingmachine/gotenberg:7

**Comment by mdsantos1979** [comment]
Tried in other server with docker, same issue.

**Comment by gulien** [comment]
Could you try with version `7.4.3`?

**Comment by mdsantos1979** [comment]
Hi, it did the trick! it seems to be working. What is the issue? Libre office version used? I also have issues when converting tiff files to PDF, I guess it's also a libreoffice problem.
Thank you very much.

**Comment by gulien** [comment]
> What is the issue? Libre office version used?

That's my best guess for now 😅

**Comment by mdsantos1979** [comment]
Hi, 

See this example if you don't mind. In the ZIP file we have the original TIF and the output PDF file. 
[Decreto-Lei-n.384-B-99(4).zip](https://github.com/gotenberg/gotenberg/files/10332436/Decreto-Lei-n.384-B-99.4.zip)

Thanks in advance!

**Comment by gulien** [comment]
@mdsantos1979 could you open a new issue or a discussion for the TIFF files?

**Comment by gulien** [comment]
@mdsantos1979 could you try the image `gulnap/gotenberg:libreofficefix`? It's using a downgraded version of LibreOffice (`7.0.4`) but with the  Gontenberg `7.7.1` codebase.

**Comment by craigh** [comment]
@gulien I was just working with this as you fixed and closed it. 😆 

I was going to tell you that I am using the arm64 build and was having the same issue with libreOffice except that it only seemed to work **once**, and then require a restart before working again.

I tried the `gulnap` branch and it seems to fix the `libreOffice` issue but since it is an amd64 build, it isn't rendering any of my chromium pages. 😢 

Hopefully your fix will be released soon (and for arm64) and it will solve the problem!

**Comment by gulien** [comment]
Hello @craigh, the release is underway, ETA ~1 hour 😄

**Comment by gulien** [comment]
Release `7.7.2` is now available with the fix. Please open a new issue if the problem still persist 😄
