### ISSUE TITLE
.odg file support?

### ISSUE THREAD

**Issue by MatthiasLohr** [gotenberg/gotenberg#573]
Hi,

this is my first contact with gotenberg, so please excuse me if this issue might be unnecessary.

I tried to convert an `.odg` ([Libreoffice Drawing](https://www.libreoffice.org/discover/what-is-opendocument/)) file to PDF using the public API:
```
curl --request POST https://demo.gotenberg.dev/forms/libreoffice/convert --form 'files=@test.odg' -o test.pdf
```
As result, I'm getting the error
```
Invalid form data: no form file found for extensions: [.bib .doc .xml .docx .fodt .html .ltx .txt .odt .ott .pdb .pdf .psw .rtf .sdw .stw .sxw .uot .vor .wps .epub .png .bmp .emf .eps .fodg .gif .jpg .jpeg .met .odd .otg .pbm .pct .pgm .ppm .ras .std .svg .svm .swf .sxd .sxw .tif .tiff .xhtml .xpm .odp .fodp .potm .pot .pptx .pps .ppt .pwp .sda .sdd .sti .sxi .uop .wmf .csv .dbf .dif .fods .ods .ots .pxl .sdc .slk .stc .sxc .uos .xls .xlt .xlsx]
```
The same result also when running locally using docker.

Interestingly, `.otg` support (just the template version of an `.odg` file) is supported. I just renamed the file to test.otg and conversion worked. However, according to #248, .odg should be supported anyways.

Am I missing something here or is .odg missing in the file extension white list or something similar?

Best regards
Matthias

**Comment by gulien** [comment]
Hello @MatthiasLohr,

I do think it is missing from the supported extensions 😉 and

**Comment by MatthiasLohr** [comment]
... and? Looks like your reply is incomplete :D

**Comment by MatthiasLohr** [comment]
Go go go... :D I would offer to create a pull request, but when I see it right, that would just affect a single line, so much more overhead for you.

**Comment by gulien** [comment]
@MatthiasLohr version 7.8.0 is now available!
