### ISSUE TITLE
extraLinkTags doesn't seem to load the stylesheet

### ISSUE THREAD

**Issue by tomasruud** [gotenberg/gotenberg#575]
Whenever I try to attach some custom styles for the URL I'm rendering, using the `extraLinkTags` parameter, the CSS doesn't seem to be applied. Is this a bug?

Here is the command I'm running

```shell
curl --request POST \
  --url http://localhost:3000/forms/chromium/convert/url \
  --header 'Content-Type: multipart/form-data' \
  --form url=https://google.com/ \
  --form marginTop=0 \
  --form marginBottom=0 \
  --form marginLeft=0 \
  --form marginRight=0 \
  --form 'extraLinkTags=[{"href":"https://gist.githubusercontent.com/tomasruud/d49b7c4418bd3caea281954690f83989/raw/1ce962f10dafa54f2af7fcfc6575afacefa16cf5/show.css"}]' \
  --form printBackground=true
```

**Comment by gulien** [comment]
Hello @tomasruud,

Using the `--log-level= debug` property, you should see in the Gotenberg logs if the page is loading your gist or not (caution, its quite verbose!).

**Comment by tomasruud** [comment]
I see some lines regarding the link tag, like this for instance:

`{"level":"debug","ts":1673004631.750335,"logger":"api.formschromiumconverturl.browser","msg":"-> {\"id\":61,\"sessionId\":\"EB7FBCF861E358E417D1A755EAEA7FA0\",\"method\":\"Runtime.evaluate\",\"params\":{\"expression\":\"\\n(() =\\u003e {\\n\\tconst link = document.createElement('link');\\n\\tlink.href = 'https://gist.githubusercontent.com/tomasruud/d49b7c4418bd3caea281954690f83989/raw/1ce962f10dafa54f2af7fcfc6575afacefa16cf5/show.css';\\n\\tlink.rel = 'stylesheet'\\n\\tdocument.head.appendChild(link);\\n})();\\n\",\"returnByValue\":true}}","trace":"15d91858-90fe-40c1-afaa-a5527e80217c"}`

But I can't really see that it does anything to the page. I've also tried loading a script that sets `window.isLoaded = true` when it loads, but the `waitForExpression` function is not picking this up either. So I assume the script is not exectued either.

Are there any specific log lines you need from me to further investigate?

**Comment by gulien** [comment]
Ok, the last log is actually the one I was looking for. It tells us that Chromium is performing a request to retrieve your Gist. 

So now the questions are:

* Is the request successful? - In my opinion yes, because otherwise you would have seen an error log (https://github.com/gotenberg/gotenberg/blob/main/pkg/modules/chromium/events.go#L22).
* Is your CSS interpreted (i.e., no cors issue etc.)? - One way to check it is by using the form field `failOnConsoleExceptions ` so that if there are errors on the Chromium consoles, you should see them.

**Comment by tomasruud** [comment]
I can't see anything in the logs to indicate that the request didn't succeed. I tried enabling `failOnConsoleExceptions`, but it doesn't give any error messages.

**Comment by gulien** [comment]
I do confirm it does not work as expected 🤔 I also see the CSS / JavaScript loaded but not interpreted for whatever reason (page already loaded?).

**Comment by gulien** [comment]
Closing this for now. I silently removed this feature, as it was not working at all (my bad).

**Comment by signalwerk** [comment]
@gulien sorry for resurrecting this ticket. I'm currently looking for an option to include additional JavaScript-Code for pdf-generation. Do you know an alternative how I could do that? My use case; I would like to add [pagedjs](https://pagedjs.org/) to a page before printing. I was thinking about misuse `waitForExpression` but not sure if that could work.

**Comment by gulien** [comment]
I don’t think it would work. Ideally you should « inject » the script somehow before sending the content to Gotenberg, i.e. do the work on the client side.

**Comment by signalwerk** [comment]
@gulien yes thank you. hmm... i might setup some proxy-thingy between the page and my renderer. not ideal but I will find a solution. Thank you for all your work 🤩🥳
