### ISSUE TITLE
Chromium: make the paper size unit configurable

### ISSUE THREAD

**Issue by gulien** [gotenberg/gotenberg#591]
See https://github.com/gotenberg/gotenberg-php/pull/14.

**Comment by gulien** [comment]
Difficult to implement properly, for instance because of https://github.com/gotenberg/gotenberg/blob/bf5056f8fe21943b1d20f5345fabd95e6dff2138/pkg/modules/chromium/tasks.go#L33.

In most if not all scenarios, the default "inch" paper size unit is enough, and the available paper formats are widely known. For edge cases, a quick conversion on the client side is actually better.

**Comment by FrankHeijden** [comment]
Thanks for the quick reply! Maybe my understanding of that piece of code is wrong, but would defaulting that piece of code to `${value}in` work?

**Comment by gulien** [comment]
See https://github.com/gotenberg/gotenberg/discussions/838#discussioncomment-8804246.

**Comment by gulien** [comment]
Done in https://github.com/gotenberg/gotenberg/commit/eb054146d27aadbe8824e2f11c39bfaf030ecdbd.
