### ISSUE TITLE
Suggestion for font handling

### ISSUE THREAD

**Issue by alerque** [gotenberg/gotenberg#602]
I'm one of the developers on the [SILE](https://sile-typesetter.org/) typesetter, and one of the things we provide is a Docker container. I just ran across this project and was poking around the docs and noticed the [section on fonts](https://gotenberg.dev/docs/customize/fonts) suggests that you would *have to* build a Docker image to get more fonts inside the container.

I would like to suggest that this is simply not true. You can *run* docker with `--volume source:target` arguments such that a source directory from your host system can be mounted inside the container at a target location. This can be used to mount a host system's fonts in a place that the container could see them, potentially exposing all the host fonts to all the software in the container.

This might be a useful trick to document since it should be possible already with no changes on your end, just `docker run -it --volume "/usr/share/fonts:/usr/local/share/fonts"` or something like that depending on the host system.

**Comment by gulien** [comment]
Hello @alerque,

Indeed, you could mount a volume to do the job. That being said, I do think it's a better option (for production runtime) to have a single Docker image with everything you need.

**Comment by gulien** [comment]
Done in latest documentation version.
