### ISSUE TITLE
PDF/A conversion: Whitespaces randomly appearing and disappearing

### ISSUE THREAD

**Issue by MatthiasLohr** [gotenberg/gotenberg#608]
Hi,

I have a very strange problem. I'm using gotenberg to make PDF files PDF/A compatible. During the conversion process, randomly a whitespace is inserted - sometimes.

This is part of the input file (original attached):

![image](https://user-images.githubusercontent.com/781926/222542543-53f1a541-79c8-4f07-876e-7b21b30d26d4.png)

Now, part of the conversion result:

![image](https://user-images.githubusercontent.com/781926/222542818-5a3cb62c-4490-47fe-a324-7f941b9991dc.png)

Interestingly, there is a new whitespace in `registerD[ ]ispute` at the bottom of the diagram.

Besides that, the money bags are moved a bit.

Any idea what's happening here???

Attachments:
  * [pre-convert.pdf](https://github.com/gotenberg/gotenberg/files/10875480/pre-convert.pdf)
  * [post-convert.pdf](https://github.com/gotenberg/gotenberg/files/10875481/post-convert.pdf)

**Comment by gulien** [comment]
Hello @MatthiasLohr 👋

Currently, it’s the LibreOffice module that handles the PDF archive conversions ; it might outputs slightly different PDF as its parser is:

1. Definitely not the best out there.
2. Different from the original PDF writer.

 Not much I can do with Gotenberg, alas.
