### ISSUE TITLE
landscape not working with libreoffice/convert xls -> pdf

### ISSUE THREAD

**Issue by yan-hic** [gotenberg/gotenberg#612]
How can one tell if landscape option is effectively being used by libreoffice ? I don't see any indication in the logs (cloud run image) and as a matter of fact, landscape is never applied.

See file attached for testing - instead of getting one page in landscape, I get 3 which is not usable.
[landscape.xlsx](https://github.com/gotenberg/gotenberg/files/10975499/landscape.xlsx)

Also, what tells the paper size to use ? I see it's defaulted (hard-coded ?) to `Letter` but ideally I rather pick `Legal` or `A3` to show even more on one page. `convertapi` uses libreoffice too and provides a lot of options, but is slow and single-processing, hence the goal to host our own converter.

**Comment by gulien** [comment]
Changing the paper size is current not available in the LibeOffice module.
Regarding the landscape, it is not available for all document types. For instance, it works with `.docx` document. I'll update the documentation about this limitation.

What's `convertapi`?

**Comment by yan-hic** [comment]
@gulien my bad, I meant the commercial service [here](https://www.convertapi.com/xlsx-to-pdf) - see the advanced options. It converts/transforms very well, offers a generous free plan but is too slow for our use. 
However, it seems to use `openoffice` instead, which is surprising as quite old and not actively maintained.

**Comment by gulien** [comment]
I guess it interacts directly with the UnoAPI (in Java), which is not the case of Gotenberg alas. Not sure I can do much, for now.

**Comment by yan-hic** [comment]
Interesting finding: for xlsx: you can set whatever page properties in the xlsx itself in another tool and libreoffice will "print" to pdf as per these settings i.e. paper size, orientation, area, scale,...
Tested with Excel but there are open source packages out there that can effect the same as preprocessing step e.g. `openpyxl` if Python.

**Comment by cuipengfei** [comment]
> Interesting finding: for xlsx: you can set whatever page properties in the xlsx itself in another tool and libreoffice will "print" to pdf as per these settings i.e. paper size, orientation, area, scale,... Tested with Excel but there are open source packages out there that can effect the same as preprocessing step e.g. `openpyxl` if Python.

Hi @yan-hic ,  did you eventually find out a way to increase the width of the pdf that was converted from excel file?

**Comment by yan-hic** [comment]
> Hi @yan-hic , did you eventually find out a way to increase the width of the pdf that was converted from excel file?
I set with the xl library the orientation to landscape and papersize to tabloid which is 11x17, before converting to pdf. The pdf retains the paper size.
