### ISSUE TITLE
Propagating error in chromium module

### ISSUE THREAD

**Issue by TheRealPaco** [gotenberg/gotenberg#613]
Hi, 

In the chromium module, we are using a microservice that generate html files. Sometime it throws exceptions and right now, gotenberg return a pdf with the exception message as content. in those cases, we would want gotenberg to respond with an error so we can handle it on our side. 

Is it something you could add in the futur?
Thanks!

**Comment by gulien** [comment]
Hello @TheRealPaco,

Could the following form field works for you?

```
failOnConsoleExceptions bool  Return a 409 Conflict response if there are exceptions in the Chromium console (default false)
```

**Comment by TheRealPaco** [comment]
No, it doesn’t work. the chromium instance render the error message and we still receive a 200 and an image version of the chromium error viewer in the pdf. The exceptions occurs during the rendering of the html in our dotnet backend, not in the javascript

**Comment by gulien** [comment]
I mean, it makes sense because Gotenberg renders whatever the page is.

**Comment by gulien** [comment]
@jmvezic @TheRealPaco what kind of status code should I consider as successful?

**Comment by gulien** [comment]
I guess Chromium does, but I'll need to check!
