### ISSUE TITLE
Allow changing port via Environment Variables

### ISSUE THREAD

**Issue by pnutmath** [gotenberg/gotenberg#620]
Currently, the application only allows changing the port number by passing a command-line parameter when launching the application. However, some users may not have access to this parameter switch, and as a result, they are unable to change the port number.

To make the application more flexible and accessible, I propose adding support for changing the port number via environment variables. This will enable users to specify the port number without having to pass command-line parameters.

The implementation of this feature will involve adding a new configuration option that checks for the value of an environment variable, and if present, uses it as the port number. If the environment variable is not set, the application will default to the current behavior of using the command-line parameter.

We believe this change will improve the usability and accessibility of the application for all users.

Suggested change:

Just setting default value `PORT` to `api-port-from-env` should work 

````go
fs.String("api-port-from-env", "PORT", "Set the environment variable with the port on which the API should listen - override the default port")		
````
https://github.com/gotenberg/gotenberg/blob/888f3feafff201aa6b39054d223df24c04f688b6/pkg/modules/api/api.go#L165

**Comment by gulien** [comment]
Hello @pnutmath,

I'm not against the idea, but do you have an exemple of a provider / infrastructure that does not allow the setting of a command flag? 😄

**Comment by pnutmath** [comment]
Our internal layer on top of Kubernetes does not support `args` and does not allow changing the targetPort at the service level as of now. Change request is also taking time than expected.

It would be helpful to support environment variables for port selection using the standard `PORT` variable. This would definitely improve usability.

**Comment by gulien** [comment]
Sorry for the delay 😅

Problem is that, if the flag `api-port-from-env` is set, Gotenberg will check if the environment variable exists and has a usable value (e.g., an int within a certain range). I did this in order to give an immediate feedback to the user if something is missing.

Best option for you would be to create your own Dockerfile:

```dockerfile
FROM gotenberg/gotenberg:8

CMD [ "gotenberg" , "--api-port-from-env=PORT"]
```
