### ISSUE TITLE
How to produce PDF/UA with LibreOffice

### ISSUE THREAD

**Issue by giamma** [gotenberg/gotenberg#621]
LibreOffice supports the creation of PDF/UA (accessible PDF documents) when the input docx file contains appropriate accessibility information (e.g. alternative text for images and so on).

Is it possible with Gotenberg to pass the appropriate conversion option to LibreOffice?
When exporting from the LibreOffice GUI the relevant options are those highlighted in the picture below. Based on the documentation, I belive that Gotenberg allows requesting a PDF/A output, but does not provide an option for PDF/UA. 

<img width="786" alt="immagine" src="https://user-images.githubusercontent.com/1883946/228464035-ee2a1f62-ecad-49bc-98ed-f6341b79b2eb.png">

**Comment by giamma** [comment]
It looks like the appropriate export options to pass to LibreOffice are:

 EnableTextAccessForAccessibilityTools=true
 UseTaggedPDF=true

so until gotenberg provides a way to pass such options, I created a derived docker image that replaces unoconv with a shell script that invokes unoconv and always specifies such options:

```
FROM gotenberg/gotenberg:7

USER root
RUN mv /usr/bin/unoconv /usr/bin/unoconv2
RUN echo '#!/bin/bash\n/usr/bin/unoconv2 -e EnableTextAccessForAccessibilityTools=true -e UseTaggedPDF=true "$@"' > /usr/bin/unoconv && \
    chmod 755 /usr/bin/unoconv
USER gotenberg
```

**Comment by gulien** [comment]
@giamma thanks for the details!

**Comment by giamma** [comment]
One additional comment: if you need your accessible PDFs to be in PDF/A format, make sure to use the "nativePdfFormat" option (which I believe uses LibreOffice), instead of "pdfFormat" (which I believe uses unoconv) because the latter strips some accessibility information from the PDF document produced by LibreOffice (e.g. alternative text for pictures).
