### ISSUE TITLE
Converting HTML to PDF is very slow

### ISSUE THREAD

**Issue by regnerisch** [gotenberg/gotenberg#623]
Hello,

we currently facing a performance issue with gotenberg (inside docker). We generate our credits with gotenberg which takes on 1GB RAM and 1vCPU (at Digital Ocean) round about 15 seconds. We use the gotenberg-php client with following code:

```php
        $request = Gotenberg::chromium(config('services.gotenberg.url'))
            ->paperSize(8.27, 11.7)
            ->header(Stream::path(resource_path('assets/AuthorAccounting/Credits/creditPdfHeader.html')))
            ->footer(Stream::path(resource_path('assets/AuthorAccounting/Credits/creditPdfFooter.html')))
            ->margins(1, 1.4, 0.39, 0.39)
            ->assets(
                Stream::path(resource_path('assets/AuthorAccounting/Credits/creditPdf.css')),
            )
            ->html(Stream::string('creditPdf.html', $html));
```

We do not use any custom fonts or something like that. 

Upgrading to 1vCPU and 2GB RAM reduces generation time to 8 seconds, another upgade gave us another 2 seconds. Still quite "long" for a simple 1 to 2 pages PDF.

I would like to get some help how we could reduce generation time or what we can do to reach a better performance. Also if we do a bulk generation (sending e-mails to customers with PDF attachments) the API crashes completly and we get error logs with message `convert HTML to PDF` (which is no helpfull message at all).

**Comment by gulien** [comment]
Hello @regnerisch,

15 seconds seems a lot: how long does it take on the [demo](https://gotenberg.dev/docs/get-started/live-demo)?

Do you happen to have a lot of remote assets ?

> the API crashes completly and we get error logs with message convert HTML to PDF (which is no helpfull message at all)

What's the exact log message?

Anyway, there is currently no limitation to the number of requests, i.e., if you send X requests, Gotenberg will start X Chrome instances. Some options:

1. Reduce back pressure by managing the number of concurrent requests your client is sending to Gotenberg.
2. Have a scale up / scale down strategy.

**Comment by regnerisch** [comment]
Hello @gulien,

thanks for your answer.

> 15 seconds seems a lot: how long does it take on the [demo](https://gotenberg.dev/docs/get-started/live-demo)?

It just took 3 seconds 🥇.

> Do you happen to have a lot of remote assets?

No, the css is the only asset we have (+header and footer inline css). It's webpack minified TailwindCSS, reduced to only the classes we need inside our html.

> What's the exact log message?

```json
{"level": "error", "logger": "api", "msg": "convert HTML toPDF: chromium PDF: chrome could not dial , \"ws://127.0.0.1:22942/devtools/browser/.../\": context: deadline exceeded", "host": "et-api-staging-gotenberg", "uri": "/forms/chromium/convert/html", "method": "POST", ...}
```

and

```json
{"level": "error", "logger": "api", "msg": "convert HTML toPDF: chromium PDF: context deadline exceeded", "host": "et-api-staging-gotenberg", "uri": "/forms/chromium/convert/html", "method": "POST", ...}
```

and

```json
{"level": "error", "logger": "api", "msg": "convert HTML toPDF: chromium PDF: websocket url timeout reached", "host": "et-api-staging-gotenberg", "uri": "/forms/chromium/convert/html", "method": "POST", ...}
```

also I get something like: `Could not bind NETLINK socker: Permission denied (12) [...] ERROR:file_path_watcher_inotify.cc(823)] Failed to read /proc/sys/fs/inotify/max_user_watches`

**Comment by gulien** [comment]
I don't know what's going on with Digital Ocean, but my Render instance is very small (512MB of RAM and 0.5 vCPU) 🤔 

As far as I know, it all seems related to your infrastructure

1. 15 seconds is way too long for a single request.
2. With concurrent requests, the logs tell that your requests reached the timeout duration (at different steps in the process), which makes sense with point 1.
3. `Failed to read /proc/sys/fs/inotify/max_user_watches` ?? Your Digital Ocean instance has some steep limitations lol
