### ISSUE TITLE
macOS '*.pages' conversion

### ISSUE THREAD

**Issue by AvnerCohen** [gotenberg/gotenberg#635]
Apologies if this was raised in the past, I see that pages is not supported, what would it take to add such support?

Invalid form data: no form file found for extensions: [.bib .doc .xml .docx .fodt .html .ltx .txt .odt .ott .pdb .pdf .psw .rtf .sdw .stw .sxw .uot .vor .wps .epub .png .bmp .emf .eps .fodg .gif .jpg .jpeg .met .odd .otg .pbm .pct .pgm .ppm .ras .std .svg .svm .swf .sxd .sxw .tif .tiff .xhtml .xpm .odp .fodp .potm .pot .pptx .pps .ppt .pwp .sda .sdd .sti .sxi .uop .wmf .csv .dbf .dif .fods .ods .ots .pxl .sdc .slk .stc .sxc .uos .xls .xlt .xlsx]

I am refering to the output file of https://www.apple.com/pages/

**Comment by gulien** [comment]
Hello @AvnerCohen,

Is it supported by LibreOffice?
