### ISSUE TITLE
Support Adobe LiveCycle [XFA] PDFs?

### ISSUE THREAD

**Issue by nonprofittechy** [gotenberg/gotenberg#636]
I'm working on a nonprofit PDF-related project where we work with a lot of court forms in PDF format. Even though Adobe LiveCycle/XFA forms aren't in the standard, they are everywhere in the wild for court forms.

There don't seem to be many free options to convert from XFA to standard PDF. Mozilla's pdf.js supports them, but the only way to convert with that library is to open it in a browser and then to select print to PDF.

It seems like the existing HTML->PDF engine could be slightly modified to include pdf.js rendering of XFA forms. Is this of interest?

Here is my manual process, but I'd be happy to ditch it for something with better support:

https://www.nonprofittechy.com/2022/01/05/batch-convert-adobe-livecycle-xfa-forms-into-ordinary-pdfs/

**Comment by gulien** [comment]
Hello @nonprofittechy,

I guess it's already doable 🤔 

1. Create a web server that serves your content +  `pdf.js`
2. Ask to convert via https://gotenberg.dev/docs/modules/chromium#url
