### ISSUE TITLE
Extract header and footer in html based on html id or class tag

### ISSUE THREAD

**Issue by abdalem** [gotenberg/gotenberg#637]
Hi ! 

It could be great to generate a pdf from html that already have a footer and header based on id tag. I am doing it with puppeteer right now by extracting the footer and header content from an html link that have a dynamic footer and header. 
I am stuck with puppeteer because gotenberg does not provide a solution for this behaviour.

**Comment by gulien** [comment]
I feel like this is too much of an edge case. Closing it.
