### ISSUE TITLE
wait for event DomContentEventFired: context deadline exceeded

### ISSUE THREAD

**Issue by PierreSchwang** [gotenberg/gotenberg#638]
Hey!

We are currently facing the issue that *some* actions against gotenberg are failing due to whatever circumstances. I don't have any starting point to reproduce the issue. What I can at least say, the payload sent to Gotenberg isn't that large (at least it handles much larger HTML documents). As seen in the log entry, the `--api-timeout` of `60s` is correctly applied and awaited.

```json
{
   "level":"error",
   "ts":1683033915.8010466,
   "logger":"api",
   "msg":"convert HTML to PDF: convert to PDF: chromium PDF: wait for events: wait for event DomContentEventFired: context deadline exceeded",
   "trace":"24bcba63-8aef-4d78-b0ef-a77d2dce512a",
   "remote_ip":"172.20.0.12",
   "host":"converter:3000",
   "uri":"/forms/chromium/convert/html",
   "method":"POST",
   "path":"/forms/chromium/convert/html",
   "referer":"",
   "user_agent":"ReactorNetty/1.0.17",
   "status":503,
   "latency":60017381303,
   "latency_human":"1m0.017381303s",
   "bytes_in":-1,
   "bytes_out":19
}
```

The image used is `gotenberg/gotenberg:7.7.2`

**Comment by gulien** [comment]
Hello @PierreSchwang,

This is one of the Chromium's events Gotenberg is waiting for to make sure that the page has entirely loaded before trying to print it to PDF.

In your case, I have no idea why it's not fired though 🤔
