### ISSUE TITLE
unoconv PDF: unix process error: wait for unix process: signal: segmentation fault (core dumped)

### ISSUE THREAD

**Issue by PierreSchwang** [gotenberg/gotenberg#639]
Seemingly LibreOffice segfaults - not sure if that's anything that can be rescued by gotenberg itself. I guess it's just another instability of LO itself?

```json
{
   "level":"error",
   "ts":1682589868.6889822,
   "logger":"api",
   "msg":"convert HTML to PDF: convert PDF: convert PDF to 'PDF/A-1a' with multi PDF engines: convert PDF to 'PDF/A-1a' with PDFcpu: method not available; convert PDF to 'PDF/A-1a' with PDFtk: method not available; convert PDF to 'PDF/A-1a' with QPDF: method not available; convert PDF to 'PDF/A-1a' with unoconv: unoconv PDF: unix process error: wait for unix process: signal: segmentation fault (core dumped)",
   "trace":"deb4a7ef-184a-4f80-bbe1-f2654d310b25",
   "remote_ip":"172.20.0.88",
   "host":"converter:3000",
   "uri":"/forms/chromium/convert/html",
   "method":"POST",
   "path":"/forms/chromium/convert/html",
   "referer":"",
   "user_agent":"ReactorNetty/1.0.17",
   "status":500,
   "latency":1898941311,
   "latency_human":"1.898941311s",
   "bytes_in":-1,
   "bytes_out":21
}
```
The image used is `gotenberg/gotenberg:7.7.2`

**Comment by PierreSchwang** [comment]
> Hello @PierreSchwang, @pieterocp
> 
> 
> 
> > I guess it's just another instability of LO itself
> 
> 
> 
> I guess so.
> 
> 
> 
> AFAIK, `PDF/A-1a` is nothing fancy, just some metadata added to the PDF itself. One day I could implement some sort of Go solution directly.

Sadly, PDF/A-1a is quite a bit more to be really conform. Of course, you can set specific headers in the PDF itself - which displays that the PDF file is a PDF/A-1a file, but most validators will fail. You'd have to do a few more things like embedding fonts and stuff. But I'd be glad to help you there - even tho I'm missing a bit of experience in the general pdf format.

**Comment by gulien** [comment]
Thanks for the details!

**Comment by PierreSchwang** [comment]
Maybe there should be some kind of logic to handle those errors, destroys LO instances and retries the action (up to x times)?

**Comment by giamma** [comment]
I am also experiencing this issue during a performance test with 220 simulated users and 15 gotenberg replicas. The file subject to conversion is always the same, yet a small percentage of conversions fail with this error. Any chance to add an automatic retry into gotenberg as suggested in [this comment](https://github.com/gotenberg/gotenberg/issues/639#issuecomment-1565350880)
