### ISSUE TITLE
images won't load

### ISSUE THREAD

**Issue by NamioL** [gotenberg/gotenberg#640]
Hello, thank you for the nice tool.

I`m facing a little issue, while I am generating pdf from URL images won't load. 

Its my configuration: 
    image: gotenberg/gotenberg:7
    command:
      - "gotenberg"
      - "--chromium-allow-insecure-localhost=true"
      - "--chromium-ignore-certificate-errors=true"
      - "--chromium-disable-web-security=true"
      - "--chromium-allow-file-access-from-files=true"
      - "--api-timeout=60s"
      - "--chromium-disable-javascript=false"
      - "--log-level=debug"
      
I searched a lot but I could not find any possible solution. Do I misconfigure something?

Thank you.

**Comment by gulien** [comment]
Hello @NamioL,

It may be related to the network configuration of your infrastructure. Where are the images hosted?

**Comment by NamioL** [comment]
Sorry for disturbing, issue was on my side, Gotenberg works perfect ( thank you for that ).

I had a lazy loaded images on rendering time all of the images were not loaded.

Thank you for your answer.
