### ISSUE TITLE
Error margin when convert docx to PDF/A

### ISSUE THREAD

**Issue by gabrielNetto94** [gotenberg/gotenberg#641]
Hi everyone!
When i send the request below, i get the expected result.

```curl
curl --request POST \
  --url http://192.168.203.96:3002/forms/libreoffice/convert \
  --header 'content-type: multipart/form-data' \
  --form 'files=@C:\Users\gabriel\Downloads\test.docx'
```
![image](https://user-images.githubusercontent.com/33572929/235983219-0c10f240-68f2-4807-bd82-38ef9345ef22.png)

But if i send the request with pdfFormat to PDF/A  (1a, 2b or 3b), the right margin loses its format, as you can see below.
Am I doing something wrong?

```curl
curl --request POST \
  --url http://192.168.203.96:3002/forms/libreoffice/convert \
  --header 'content-type: multipart/form-data' \
  --form 'files=@C:\Users\gabriel\Downloads\test.docx' \
  --form pdfFormat=PDF/A-1a
```
![image](https://user-images.githubusercontent.com/33572929/235983361-6fcf6f42-49ef-4e26-9874-965d53ec3ca5.png)

Here's the file I used for the test:
[test.docx](https://github.com/gotenberg/gotenberg/files/11384908/test.docx)

**Comment by gulien** [comment]
Hello @gabrielNetto94,

Does it works when you use the `nativePdfFormat` form field instead of `pdfFormat`?
