### ISSUE TITLE
gotenberg.dev top banner links to 6.x docs, not 7.x

### ISSUE THREAD

**Issue by dragon-dxw** [gotenberg/gotenberg#643]
The top banner links to 6.x:

<img width="972" alt="image" src="https://github.com/gotenberg/gotenberg/assets/85497046/378103a2-72a7-4d57-83a7-65c542408d96">

clicking through complains about not being up to date:

<img width="504" alt="image" src="https://github.com/gotenberg/gotenberg/assets/85497046/298225a1-b281-44f7-ab1d-23cf318a64da">

**Comment by gulien** [comment]
Hello @dragon-dxw,

This link is for accession the Gotenberg 6.x documentation, which is still used by many projects.
For the 7.x documentation, there is a "Documentation" link in the left of the menu bar.
