### ISSUE TITLE
@page margin being used even when preferCssPageSize is false

### ISSUE THREAD

**Issue by david-wolgemuth** [gotenberg/gotenberg#651]
when using `@page { margin }`, it does not use margins passed, even when `preferCssPageSize bool` 

> preferCssPageSize bool    Define whether to prefer page size as defined by CSS (default false)
> https://gotenberg.dev/docs/modules/chromium#routes

## minimal example:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>My PDF</title>
    <style>
        @page {
            margin: 2mm;
        }
        body {
            border: 1px dashed red;
        }
    </style>
  </head>
  <body>
    <h1>Hello world!</h1>
  </body>
</html>
```

```sh
curl \
--request POST 'http://localhost:3300/forms/chromium/convert/html' \
--form 'files=@"index.html"' \
--form 'marginTop="1"' \
--form 'marginBottom="1"' \
--form 'marginLeft="1"' \
--form 'marginRight="1"' \
#  --form 'preferCssPageSize="false"' \  (defaults to false, does not work with / without...)
-o test.pdf
```

### visual outputs

expected:

(only works without `@page { margin }` set)

<img width="1083" alt="Screenshot 2023-05-31 at 1 14 21 PM" src="https://github.com/gotenberg/gotenberg/assets/11606807/e7a02298-60e4-487b-a618-9f6f7210d4d2">

actual 

<img width="849" alt="Screenshot 2023-05-31 at 1 14 57 PM" src="https://github.com/gotenberg/gotenberg/assets/11606807/3ac6493b-04a5-442d-a81f-6020d3be71d3">

**Comment by gulien** [comment]
Hello @david-wolgemuth,

It seems to be an issue with Chrome itself, rather than a bug in Gotenberg. For instance, puppeteer has also the issue: https://github.com/puppeteer/puppeteer/issues/393.
