### ISSUE TITLE
  Source name doesn't look like file name

### ISSUE THREAD

**Issue by janswist** [gotenberg/gotenberg#652]
I got this error:  `Error: Source name "ces La esencia del cristianismo Dios es persona (jÃ³venes).docx" doesn't look like file name`

edit: Seems like the issue is not with the name, but that there is [hard cap limit of name length](https://github.com/yumauri/gotenberg-js-client/blob/master/src/internal/source-checkers.ts#L88) of 50 characters. Can we edit it somehow or at least make it bigger? 50 char names are not that rare.

Same thing with the minimum number of 3 characters - users sometimes do have like 1 char names for whatever reason :)

edit: After testing the problem is with `³` character. Exploring why is that.

**Comment by gulien** [comment]
Hello, I do not maintain the Gotenberg Javascript client. Please post an issue directly there 😄
