### ISSUE TITLE
Unable to convert DOCX Summaries

### ISSUE THREAD

**Issue by EdouardCourty** [gotenberg/gotenberg#657]
Hi, when converting a DOCX file that contains a Summary (automatically generated when using Titles in Office), and then converting to PDF, Gotenberg doesn't include the Summary in thr output PDF file.

LibreOffice doesn't create Summaries the same way, that's could be why it doesn't like it

**Comment by gulien** [comment]
Hello @EdouardCourty,

Does it work if you convert your document directly with the LibreOffice UI?
