### ISSUE TITLE
Possibility to send cookies along with Chromium requests

### ISSUE THREAD

**Issue by sgielen** [gotenberg/gotenberg#658]
I am trying to render a SPA (single-page application) output to PDF using Chromium in Gotenberg. This SPA performs an API call, which requires a cookie for authentication. It seems to be impossible to set this cookie in Chromium using the [Gotenberg Chromium API](https://gotenberg.dev/docs/modules/chromium).

I have tried setting the Cookie using the `extraHttpHeaders` field, but that didn't work - I expect it sets the Cookie only on the initial (SPA/frontend) request, and not in any subsequent backend API calls.

Could we add an additional `cookies` form field for Chromium requests, which will be added to the cookie jar in Chromium so it automatically sends them for every (matching) request, including Javascript-initiated API calls?

**Comment by gulien** [comment]
I wonder which fields would be convenient for most users. For now I have the following:

* Name, required.
* Value, required.
* URL, required if Domain is empty.
* Domain, required if URL is empty.
* Path, optional.
* Secure (bool), optional.
* HTTPOnly (bool), optional.
* SameSite, e.g., Strict, Lax, None - optional.
* Expires (datetime).

Should I calculate the URL field if no Domain nor URL are send by the user? For instance, "http://localhost" for file based conversion, or the actual URL of the website being converted.

**Comment by gulien** [comment]
Hey there 👋 I'm looking for testers: https://github.com/gotenberg/gotenberg/pull/848
