### ISSUE TITLE
Custom Gotenberg's log format

### ISSUE THREAD

**Issue by JulienWeintraub** [gotenberg/gotenberg#659]
Hi there,

We implemented Gotenberg on GKE clusters a few months ago.

Our log management is Datadog, to which we send all our application logs.
However, we are facing issue about one log attribute (in the Json log) : the `host` one.

It's a default Datadog's reserved keyword used to bind host on which pod is running.
Our problem is that Gotenberg use that field to get server when sending logs, and our Datadog Cluster agent is not able to raise custom tags and other useful informations.
![image](https://github.com/gotenberg/gotenberg/assets/95627324/86fe7161-4864-4c72-a589-2c6d20697fee)

I checked the code and focused on [code](https://github.com/gotenberg/gotenberg/blob/e2e06a8f83aef8638749260c0fa635742a215755/pkg/modules/api/middlewares.go#L164) I would be removed :p

My understanding is there is no possibility to have custom log format and don't want to fork or tweak that project for that single point.

Do you have some feedbacks on similar cases, or some guidances to help ? 

Thanks in advance 🙏 

N.B : I already check with Datadog Golang's pipeline integration processors, but no effect, because host binding is performed as before (preprocessing).

**Comment by gulien** [comment]
Hello @JulienWeintraub!

A simple solution could be a new property for setting an optional prefix to these fields, i.e., `—log-fields-prefix=gotenberg`. The `host` field would become `gotenberg_host`.

Would that work for you?

**Comment by JulienWeintraub** [comment]
Hi @gulien, thanks for your feedbacks!  

Added an optional prefix Gotenberg side, right ?
And global I guess, for all of them ?

That could be a solution for sure : I can easily remap Datadog side, attribute keys to new ones (`gotenberg_level` -> `level`) :)

Maybe some tests are required, to validate that solution 🤔

**Comment by gulien** [comment]
> Added an optional prefix Gotenberg side, right ?
And global I guess, for all of them ?

Yes, the new flag would add the prefix to all fields 👍

**Comment by JulienWeintraub** [comment]
Hello @gulien ! 

Just a quick update : I change a little bit the code to test the image in real conditions.
Very basic hard-coded modifications, because of my Go aknowledges :trollface: : 

```diff
+++ b/pkg/modules/api/middlewares.go
@@ -160,11 +160,11 @@ func loggerMiddleware(logger *zap.Logger, disableLoggingForPaths []string) echo.

 			// Now, let's log!
 			fields := make([]zap.Field, 12)
-			fields[0] = zap.String("remote_ip", c.RealIP())
-			fields[1] = zap.String("host", c.Request().Host)
-			fields[2] = zap.String("uri", c.Request().RequestURI)
-			fields[3] = zap.String("method", c.Request().Method)
-			fields[4] = zap.String("path", func() string {
+			fields[0] = zap.String("gotenberg_remote_ip", c.RealIP())
+			fields[1] = zap.String("gotenberg_host", c.Request().Host)
+			fields[2] = zap.String("gotenberg_uri", c.Request().RequestURI)
+			fields[3] = zap.String("gotenberg_method", c.Request().Method)
+			fields[4] = zap.String("gotenberg_path", func() string {
 				path := c.Request().URL.Path

 				if path == "" {
@@ -173,13 +173,13 @@ func loggerMiddleware(logger *zap.Logger, disableLoggingForPaths []string) echo.

 				return path
 			}())
-			fields[5] = zap.String("referer", c.Request().Referer())
-			fields[6] = zap.String("user_agent", c.Request().UserAgent())
-			fields[7] = zap.Int("status", c.Response().Status)
-			fields[8] = zap.Int64("latency", int64(finishTime.Sub(startTime)))
-			fields[9] = zap.String("latency_human", finishTime.Sub(startTime).String())
-			fields[10] = zap.Int64("bytes_in", c.Request().ContentLength)
-			fields[11] = zap.Int64("bytes_out", c.Response().Size)
+			fields[5] = zap.String("gotenberg_referer", c.Request().Referer())
+			fields[6] = zap.String("gotenberg_user_agent", c.Request().UserAgent())
+			fields[7] = zap.Int("gotenberg_status", c.Response().Status)
+			fields[8] = zap.Int64("gotenberg_latency", int64(finishTime.Sub(startTime)))
+			fields[9] = zap.String("gotenberg_latency_human", finishTime.Sub(startTime).String())
+			fields[10] = zap.Int64("gotenberg_bytes_in", c.Request().ContentLength)
+			fields[11] = zap.Int64("gotenberg_bytes_out", c.Response().Size)
```

I was able to perform multiple Datadog's log fields remapping (referer, status, ..., and all work fine ;) 
![image](https://github.com/gotenberg/gotenberg/assets/95627324/096d2446-e349-48fc-8aa6-8a1f2c97b51f)

Unused on my case after processing, but I remapped the `host` attribute to retrieve original Gotenberg content.

**Comment by gulien** [comment]
@JulienWeintraub great thank you for the feedback! I’ll try to implement it in a new release this week.

**Comment by gulien** [comment]
@JulienWeintraub version `7.9.0` is now available with the flag `--logs-fields-prefix` 😉

**Comment by JulienWeintraub** [comment]
Amazing ! 

Tested, validated and approved 🤩 

Thanks a lot @gulien for your quick release 😉
