### ISSUE TITLE
Chromium HTML to PDF landscape switch not working

### ISSUE THREAD

**Issue by chrisbbe** [gotenberg/gotenberg#660]
Hi,

I can't get the landscape switch to work when converting HTML to PDF, for example:

`curl --request POST 'https://demo.gotenberg.dev/forms/chromium/convert/url' --form 'url="https://sparksuite.github.io/simple-html-invoice-template/"' --form 'landscape="true"' -o my.pdf`

The returned PDF is rendered in portrait mode, Is this a bug or must some other conditions be met in order for the landscape switch to take effect?

**Comment by gulien** [comment]
Hello @chrisbbe,

Does it work with the form field `--form 'emulatedMediaType="screen"' ?

**Comment by chrisbbe** [comment]
Sorry, the original request indeed worked. Case closed.
