### ISSUE TITLE
Nordic characters break loading

### ISSUE THREAD

**Issue by ramonmedeiros** [gotenberg/gotenberg#662]
Tried to convert a html to pdf, but got a issue when the attachment has characters like `äåö`

This was the html:

```html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <style>
        .center {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 100%;
        }
    </style>
</head>

<body>
	<img src="Ska%cc%88rmavbild%202023-07-18%20kl.%2012.13.23.png" class="center">
	<img src="test.png" class="center">
</body>

</html>
```

Using this command:

```bash
curl \
--request POST 'http://localhost:3000/forms/chromium/convert/html' \
--form 'files=@"index.html"' \
--form 'files=@"test.png"' \
--form 'files=@"Skärmavbild 2023-07-18 kl. 12.13.23.png"' \
-o my.pdf
```

The output was a failed image on the first, and correct one on second.  Both pngs are same content

**Comment by ramonmedeiros** [comment]
Tried also rename `Skärmavbild 2023-07-18 kl. 12.13.23.png` to `Skärmavbild.png`and same issue happen

**Comment by gulien** [comment]
Hello @ramonmedeiros,

Sorry for the delay. Chromium is encoding `Skärmavbild.png` to `Sk%C3%A4rmavbild.png`. I've tried to find a fix, but for now without success. In the meantime, you should only use non-special characters
