### ISSUE TITLE
Helm Chart: Autoscaling api

### ISSUE THREAD

**Issue by tweiss-mdm** [gotenberg/gotenberg#665]
Hello,
When using the helm chart (5.2.0) with autoscaling enabled, the following errors is thrown:

`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"`

I suggest replaceing the api => `autoscaling/v2`

**Comment by gulien** [comment]
Hello,

I do not maintain any helm charts. If you're referring to https://github.com/MaikuMori/helm-charts, please open an issue there 😉
