### ISSUE TITLE
converting qrcode images in html to pdf

### ISSUE THREAD

**Issue by kadirguner** [gotenberg/gotenberg#666]
Hi,
When converting html files to pdf with qrcode images, it converts scanned result the qrcode, not qrcode image. How can I fix it?
Thanks.

**Comment by kadirguner** [comment]
note: using /forms/libreoffice/convert API

**Comment by gulien** [comment]
Hello @kadirguner,

Looks like a "feature" from LibreOffice. Maybe there is an option to cancel it.

**Comment by gulien** [comment]
[I don't see any option related to this behavior](https://help.libreoffice.org/latest/en-US/text/shared/guide/pdf_params.html). It might be a bug related to LibreOffice, or a default feature I cannot change. Feel free to reopen if anything new!
