### ISSUE TITLE
Formats in table

### ISSUE THREAD

**Issue by kk-rulezero** [gotenberg/gotenberg#667]
While converting a Word document with tables to pdf using LibreOffice, the styling seems lost, the data is permanently stuck to the top, and the cell borders are sometimes absent.

**Comment by gulien** [comment]
Hello @kk-rulezero,

Not sure I can do much there; does it work if you're using the LibreOffice UI?

**Comment by kk-rulezero** [comment]
@gulien Yes it does, the styling is still intact, I am using the latest version of Gotenberg

**Comment by gulien** [comment]
I’ll need a bit more of details:

* The LibreOffice version you’ve used for converting with the UI.
* The request you’ve done with Gotenberg
