### ISSUE TITLE
ver 7.9.1 use api /forms/chromium/convert/html error : 

### ISSUE THREAD

**Issue by sgamro** [gotenberg/gotenberg#671]
i deploy gotenberg  7.9.1 on openshift and i use convert html to pdf with htmfile and got error
convert HTML to PDF: convert to PDF: chromium PDF: wait for events: wait for event LoadEventFired: context deadline exceeded
convert HTML to PDF: convert to PDF: chromium PDF: wait for events: wait for event networkIdle: context deadline exceeded
![image](https://github.com/gotenberg/gotenberg/assets/70539472/05442b67-41ad-4b5e-8165-a68eccf15fca)

thank you.

**Comment by gulien** [comment]
Hello @sgamro,

Looks like the HTML document you're giving to Gotenberg cannot be converted before the timeout duration.

Could you try on the demo instance (https://demo.gotenberg.dev) or increase the API timeout with `--api-timeout`?

**Comment by sgamro** [comment]
> Hello @sgamro,
> 
> Looks like the HTML document you're giving to Gotenberg cannot be converted before the timeout duration.
> 
> Could you try on the demo instance (https://demo.gotenberg.dev) or increase the API timeout with `--api-timeout`?

how to set  args --api-timeout on openshift.

**Comment by sgamro** [comment]
I have solved this problem caused by html including the font from url to connect another server
I deleted these lines and converted the new pdf. It works fine.

Thank you very much for your help.
