### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ZiyaadQasem** [gotenberg/gotenberg#673]
version: 7.9.1

Error:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc345c9]

**The pod keeps restarting with this error**

**Comment by gulien** [comment]
Hello @ZiyaadQasem,

Did you give enough memory/CPU to your pod?
See also: https://github.com/MaikuMori/helm-charts

**Comment by ZiyaadQasem** [comment]
Hallo @gulien 
more even than recommended :)

**Comment by ZiyaadQasem** [comment]
not directly on startup. on the request /forms/pdfengines/merge

**Comment by gulien** [comment]
Ok, it may be related to a PDF engine issue. I wonder if this is related to #644.

As a workaround, you may change the PDF engines order by using the `--pdfengines-engines` property,  for instance: `--pdfengines-engines=qpdf,uno-pdfengine,pdftk,pdfcpu`

**Comment by ZiyaadQasem** [comment]
Thanks for your reply I will try that :)

**Comment by ZiyaadQasem** [comment]
Currently I have downgraded to the version 7.0.0 and everything is stable

**Comment by h4ckroot** [comment]
Help please. This issue is still showing with version: 7.10.2.
