### ISSUE TITLE
XLSX: hidden sheets printed/rendered

### ISSUE THREAD

**Issue by yan-hic** [gotenberg/gotenberg#677]
Bumping up https://github.com/gotenberg/gotenberg/issues/275#issue-782578747, especially the hidden sheet issue reported back then. 

LibreOffice would not print them, how come `gotenberg` does. I tried to set the sheets programmatically to `VERYHIDDEN` before sending for conversion but `gotenberg` still includes them in the output pdf. 

Am I missing an option or is this a bug ?

FYI, I cannot delete the hidden ones as visible sheets refer to it/them.

**Comment by yan-hic** [comment]
Found out that even if hidden, if the `print area` is set, the sheet would convert. 

Clear it and it won't print.

**Comment by gulien** [comment]
Thanks for the details @yan-hic!
