### ISSUE TITLE
Feature request - Optional Authorization

### ISSUE THREAD

**Issue by user7788** [gotenberg/gotenberg#684]
I have run the app in Google CloudRun and in AWS AppRunner, and both give by default public URL.
- in CloudRun i managed to access it trough service account  and bearer token
- in AppRunner it seems I have to setup a lot of infrastructure, VP endpoint, links even a Network Gateway and i stopped

I think it's easier to have the authorization with the app, I did add it as a middleware, but my Go experience is zero,
not sure if this is the right way to do it (with a typo, fixed later)
https://github.com/user7788/gotenberg/commit/73df0728dc814f83f7d5a11d3634929618f87824

**Comment by gulien** [comment]
Would basic authentication be enough?

Note for myself: https://echo.labstack.com/docs/middleware/basic-auth

**Comment by user7788** [comment]
Sure, any form of optional authentication is good, than you can run the
container on a public GoogleCloud or Aws AppRunner URL,
and not need to setup additional infrastructure.

Danny

**Comment by gulien** [comment]
Basic auth has been implemented here: https://github.com/gotenberg/gotenberg/commit/75c4a4f25335c47c5d72aab6a6048136d1f8f7fc

`gotenberg/gotenberg:edge` should soon have this feature available.

```
--api-enable-basic-auth (bool)   Enable basic authentication - will look for the GOTENBERG_API_BASIC_AUTH_USERNAME and GOTENBERG_API_BASIC_AUTH_PASSWORD environment variables
```
