### ISSUE TITLE
Incorrect pdf print results for document with different margins on the first and rest pages

### ISSUE THREAD

**Issue by dd-condat** [gotenberg/gotenberg#688]
Hi there! I tryed to use different margins on the first page an other pages with CSS. It doesnt' work as expected.

I found the bug/issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=1346874

The bug should have been solved in chromium version 117. In the current docker-container of gotenberg is chromium 115 installed. Does anyone have an idea how i update to the current chromium version? Or is an update of the gotenberg docker container planned?

Greetings!

**Comment by gulien** [comment]
It should be fixed in version `7.9.2` (release in progress).

**Comment by ytilotti** [comment]
Should be or fixed @gulien? I'm testing your new version on #697 but during my test I revert to the last version of Gotenberg because I have an effect on margin, weird.

**Comment by gulien** [comment]
@ytilotti dunno, but I did not touch anything related to the Chromium API. Maybe newer versions of Chromium have a different behavior (you could check if puppeteer has the same issue).

**Comment by ytilotti** [comment]
Sorry it's not the same issue with @dd-condat , the margin change on all the pages in my case.

**Comment by dd-condat** [comment]
We updated our gotenberg docker container and the margin effect has been resolved. We can now use different margins on different pages in a single pdf:

`@page {
    size: A4 landscape;
    margin: 20mm 15mm 20mm 25mm;
}
@page cover {
    size: A4 landscape;
    margin: 0;
}`
