### ISSUE TITLE
API Broken, Incorrect Documentation, and Adding Custom Fonts

### ISSUE THREAD

**Issue by lawfulsoftware** [gotenberg/gotenberg#691]
There seem to be several issues.  I am building from gotenberg/gotenberg:7.9.2 running locally on Docker Desktop.

### Incorrect Documentation

The page properties are incorrectly stated in the documentation for the [LibreOffice Conversion EndPoint](https://gotenberg.dev/docs/routes#page-properties-libreoffice).  "landscape" should be "Landscape".  "nativePageRanges" should be "PageRanges".

For confirmation, see the expected variables at lines 48 and 53 of [uno.go](https://github.com/lawfulsoftware/gotenberg/blob/main/pkg/modules/libreoffice/uno/uno.go)

Line 58 also looks for the PDFformat parameter however this is not documented.

### Parameters Not Passed to LibreOffice

They parameters are not properly passed to LibreOffice so they are effectively ignored.

### Important Parameters Not Supported

The [OpenOffice Wiki](https://wiki.openoffice.org/wiki/API/Tutorials/PDF_export) contains many supported properties that would be useful such as:

- UseLosslessCompression
- IsSkipEmptyPages
- Watermark

### Custom Fonts

See PR #690

**Comment by gulien** [comment]
Hello @lawfulsoftware,

*Incorrect documentations*

The documentation is about the REST API usage, not internal naming. In other words, the documentation lists the *form field keys* available. See also: https://github.com/gotenberg/gotenberg/blob/85d125463849b940c938f586ab0348263ddddce4/pkg/modules/libreoffice/routes.go#L35.

Regarding the PDF format, check https://gotenberg.dev/docs/routes#pdfa-libreoffice.

*Parameters Not Passed to LibreOffice*

How should they be passed?

**Comment by gulien** [comment]
> The route "Office documents into PDFs" has a tag which is the same weight as "Page Properties", "Merge", and "PDF/A" that follow. Visually, at a quick glance, they all appear to be separate routes.

<img width="249" alt="Capture d’écran 2023-09-26 à 10 37 14" src="https://github.com/gotenberg/gotenberg/assets/8983173/845557e7-bdbf-4aec-824c-76de612f6f38">

> As for UseLosslessCompression, IsSkipEmptyPages, and Watermark, I assume that they are not currently supported however they would be quite beneficial.

Could you create a separate issue?

> This file documents a test with both nativePageRanges and PageRanges and provides the debug log with my observations. Neither value works and the output for both is a PDF file with eleven pages.

Could you also create a separate issue?

> It was somewhat difficult to change the log level. I note that the option to set the LOG_LEVEL environment variable was removed. Are there any plans to make it easier to set the log level?

https://gotenberg.dev/docs/configuration#logging
