### ISSUE TITLE
arm64 - convert URL to PDF: convert to PDF: chromium PDF: chrome failed to start

### ISSUE THREAD

**Issue by gulien** [gotenberg/gotenberg#694]
### Discussed in https://github.com/gotenberg/gotenberg/discussions/693

<div type='discussions-op-text'>

<sup>Originally posted by **keyurmistry21** September 25, 2023</sup>
Hi,

I just Implemented gotenberg.

docker-compose.yml
 ```
 gotenburg:
    image: gotenberg/gotenberg:7
    ports:
      - "3009:3000"
```
I ran the command
```
curl \
--request POST 'http://localhost:3009/forms/chromium/convert/url' \
--form 'url="https://sparksuite.github.io/simple-html-invoice-template/"' \
-o my.pdf
```
I got an error like this: 

{"level":"error","ts":1695674237.8608663,"logger":"api","msg":"convert URL to PDF: convert to PDF: chromium PDF: chrome failed to start:\nqemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped\nqemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped\n[0925/203717.599775:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory\n[0925/203717.805805:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)\nAssertion failed: p_rcu_reader->depth != 0 (/qemu/include/qemu/rcu.h: rcu_read_unlock: 101)\n","trace":"895bbd5e-f793-4ab1-adad-4d353daddaac","remote_ip":"172.28.0.1","host":"localhost:3009","uri":"/forms/chromium/convert/url","method":"POST","path":"/forms/chromium/convert/url","referer":"","user_agent":"curl/8.1.2","status":500,"latency":2065853126,"latency_human":"2.065853126s","bytes_in":160,"bytes_out":21}

Does anyone have any solution ? I'm using Mac M1 pro.</div>

**Comment by gulien** [comment]
Hello @keyurmistry21,

Looks like an issue from the `arm64` platform Docker image variant. Which version are you actually using? `7.9.2`? Could you try to downgrade the Gotenberg version until it works?

**Comment by keyurmistry21** [comment]
Oh, that works. But I'm curious why it hasn't been integrated with the latest version?

**Comment by gulien** [comment]
Did you find a working version of Gotenberg? Which one? 😊

My guess is that newer versions of Chromium might be the culprits.

**Comment by gulien** [comment]
Closing this for now. Feel free to reopen if it is happening with latest version.
