### ISSUE TITLE
Color of image darker in rendered PDF

### ISSUE THREAD

**Issue by joshgdale** [gotenberg/gotenberg#695]
Hey,

It seems that Gotenberg is rendering the the color of one of my images darker. 

<img width="946" alt="Screenshot 2023-09-27 at 14 52 31" src="https://github.com/gotenberg/gotenberg/assets/46057976/564ea07d-520d-4ad8-8d49-6ec74e961246">

The section with "Foo" is the color is should be. That is a div with the background color set to the hex value.

When you open up the source image, the color is displayed correctly, just not once it's been through gotenberg.

[I've seen a previous issue with a similar error](https://github.com/gotenberg/gotenberg/issues/354), but I am using v7.9.2 so this fix should already be applied? Using on a Mac via Docker if that's relevant.

I appreciate your help! Thanks in advance.

**Comment by gulien** [comment]
Hello @joshgdale!

Looks like an issue with how Chromium is rendering the image in a PDF. For instance, there is a equivalent issue in puppeteer: https://github.com/puppeteer/puppeteer/issues/8076. Not sure I can do much here alas.

**Comment by joshgdale** [comment]
Hey @gulien, thanks for your response!

Okay thanks for taking a look. Is the way headless Chromium renders different to your normal browser (color spaces... clutching at straws!!)? Or does it essentially just take a screenshot?

Thank you!

**Comment by gulien** [comment]
No idea 😄 Maybe in headless mode it uses the "dark mode" by default, so darker images?
