### ISSUE TITLE
Ability to prevent header/footer on certain pages

### ISSUE THREAD

**Issue by EvanAsbuilt** [gotenberg/gotenberg#698]
This is simply a feature request (or if it's available already, a question on how I can accomplish this).

I've gotten the header and footer templates working but I'd like to prevent them from displaying on a specific page/section.

Is this possible or could it be added as a feature?

**Comment by gulien** [comment]
Hello @EvanAsbuilt, the Chrome dev protocol does not allow such behavior atm. Best option is to find a way to do it using JavaScript/CSS print libraries.
