### ISSUE TITLE
Margin changes since 7.9.2

### ISSUE THREAD

**Issue by ytilotti** [gotenberg/gotenberg#699]
The margin on the content (not header/footer) changes since the last version (7.9.2) on the generation html to pdf with Chromium.
Do you have more informations? A new parameter? Different resolution? Different default values?

See the screens:

**7.9.1**
![screen-7 9 1](https://github.com/gotenberg/gotenberg/assets/5848945/4ff5e5c1-648f-450d-8121-b0e1ffdabb36)

**7.9.2**
![screen-7 9 2](https://github.com/gotenberg/gotenberg/assets/5848945/a19b98b6-c421-48ab-9630-72ddef3f469f)

**Comment by ytilotti** [comment]
The height of header & footer seems to be different too.

**Comment by gulien** [comment]
Hello @ytilotti,

Thanks for the heads up!  No idea about what’s going on there... I did not change anything related to margins. I suspect a new behavior (or bug?) in Chromium. The [cdproto](https://github.com/chromedp/cdproto) dependency has been updated also, but it is auto-generated so I don’t suspect a breaking change here.

**Comment by ytilotti** [comment]
I check the issues on Chromium, there are feedbacks margin on 117.
But don't know if the same issue.

For the moment, I've made some modifications on margins for using 7.9.2.
I'll be careful on the next update. There are corrections to margins in version 119 (beta)

**Comment by gulien** [comment]
Yep, sorry about that. It's kinda hard to keep everything updated while also guaranteeing semver "fidelity".

**Comment by ytilotti** [comment]
It's not in your responsability, no problem.

But I'm having trouble understanding the modification of header and footer margins because we can't configure it outside css.
No change generation html to pdf on your side?

**Comment by gulien** [comment]
Nothing, just [dependencies updates](https://github.com/gotenberg/gotenberg/releases/tag/v7.9.2).

**Comment by ytilotti** [comment]
No, I mean "No change generation html to pdf on your side" on your tests?

**Comment by gulien** [comment]
I'm closing this for now. Alas, there is nothing I can really do there 😅

**Comment by ytilotti** [comment]
Hi @gulien. No Chromium update since?

**Comment by gulien** [comment]
New version is 119.0.6045.159, so with some luck they did fix this issue.

**Comment by will2877** [comment]
Any news about this Issue?
Is there a common workaround?

I also reported this issue to chromium: [41487881](https://issues.chromium.org/issues/41487881)
They don't seem to be able to reproduce.

**Comment by gulien** [comment]
I did not change anything code wise, maybe there were some changes in the ChromeDevTools protocol? I'm using the [chromedp/chromedp](https://github.com/chromedp/chromedp) library.
