### ISSUE TITLE
Can file url be supported of libreoffice convert?

### ISSUE THREAD

**Issue by seepine** [gotenberg/gotenberg#707]
like this
```
curl \
--request POST 'http://localhost:3000/forms/libreoffice/convert' \
--form 'url="https://example.com/file.docx"' \
-o my.pdf
```

**Comment by gulien** [comment]
Hello @seepine! Thanks for the proposal! However, it would involve to many things (security, specific headers, etc.) and I don’t have enough time nor the will to maintain such feature.
