### ISSUE TITLE
strange scaling bug on kubernetes cluster environment

### ISSUE THREAD

**Issue by xLEpEX** [gotenberg/gotenberg#718]
Hello,

i have been come across a strange bug. I'm using the URL into PDF route to generate PDF's with dynamic content through my remix application. The bug that i now have is, that gotenberg apply a scaling of 0.96 to the request, even when i have set the scaling explicitly to 1.0. This bug also only happend when i run gottenberg on my aks cluster. On my local docker environment the scaling work as expected. Is their anything im currenlty missing what can cause this strange behaviour

**Comment by gulien** [comment]
Hello @xLEpEX,

Are you using the exact same version of Gotenberg between your local and your kubernetes cluster?

**Comment by xLEpEX** [comment]
Yes, I'm using the image gotenberg/gotenberg:7, i also have been testing by proxying the cluster through my local environment to make sure that there bug is no related to my remix app. I also have double check that the output is really different by using the same static scaling. I was able to generate the same output, when i set the scaling to 1.04 and leave it locally on 1.0

**Comment by gulien** [comment]
I mean the exact version `7.x.y` (you may find the information on container startup) 😄 
Also, what's your platform locally? `amd64` or `arm64` (M1, M2, M3 chips)?
I wonder if there is a difference of Chromium versions between your local instance and remote instance.

**Comment by xLEpEX** [comment]
Okay, yeah so I'm pretty stupid since i''was not able to see the different docker image version. Now I get the scaling bug on my local environment as well after updating the dockerimage to the 7.9.2 version. I have compared it to a pdf document that i have downloaded manually through my chrome browser with a 1.0 scaling. It seems like that on the 7.9.2 that the scaling is applyed with scaling - 0.04. After i have been downgraded back to 7.9.1 the output have match again with my manually created pdf version

**Comment by gulien** [comment]
Yes, I wonder why the Chromium DevTool Protocol changed. Maybe the scaling was wrong and is now in fact "correct"? Anyway, not much I can do, and I'd rather not apply a correction of the scale in Gotenberg 🤔

**Comment by xLEpEX** [comment]
can you tell me how i could build gotenberg with the most recent google chrome version or are you planing on updating the version soon again?

**Comment by gulien** [comment]
You have everything at your disposal in this repository. Check the Makefile commands also!

I plan to release a new version in a few weeks otherwise.
