### ISSUE TITLE
Error when converting xls file with german special character ß in file name

### ISSUE THREAD

**Issue by joernv** [gotenberg/gotenberg#730]
Gotenberg conversion fails when file name contains German special character ß.

Test file has the name `Special_Chars_ß.xlsx`.

Used curl to upload the file:
`curl --request POST --url http://127.0.01:3000/forms/libreoffice/convert --header 'Content-Type: multipart/form-data' --form files=@'Special_Chars_ß.xlsx' -o result.pdf`

This leads to the following error:
`{"level":"error","ts":1701360920.8984268,"logger":"api","msg":"convert to PDF: convert to PDF: unix process error: wait for unix process: exit status 6","trace":"2a1e60d7-745c-474c-a444-2ef7a0a30c74","remote_ip":"192.168.65.1","host":"127.0.0.1:3000","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"curl/8.1.2","status":500,"latency":57993208,"latency_human":"57.993208ms","bytes_in":8946,"bytes_out":21}`

[Special_Chars_ß.xlsx](https://github.com/gotenberg/gotenberg/files/13515174/Special_Chars_ss.xlsx)

**Comment by gulien** [comment]
Hello @joernv,

For whatever reasons, LibreOffice (unoconv?) struggles to open a filnename that contains non-basic latin characters. Before I find a fix, you should only use non-special characters.
