### ISSUE TITLE
Paper Size & PPI issue

### ISSUE THREAD

**Issue by swordinthestone** [gotenberg/gotenberg#733]
I am trying to render a PDF with Chromium with Gotenberg 7 on docker in A4 paper size. The targeted rendering page is built on top of nextJs with Tailwind CSS. It is a borderless layout with page break css : page-break-after: always; on each page. I did not set the chromium->preferCssPageSize() option on rendering.

However, when I set up the paper size with inches provided on documentation, the rendered PDF content is taking only about 3/4 space of the page. I checked with Acrobat with the file, and the rendered PDF paper size is A4. However, the content of the page is smaller. 

After testing out different pixel conversion sets, it seem like the PPI(pixel per inch) setting is around 144ppi, but provided paper size is about 96ppi, which is how css's unit conversion happens. 8.27in = 1190px instead of 8.27in = 786px.

I am wondering it is the issue introduced from Tailwind that I am using or 144ppi is the default from Gotenberg, as I can't find much info on what is Chromium's default ppi by googling?

Is there any way that I can override the ppi settings?

Thank you very much.

Runtime: WIndows WSL2 Docker 24.0.6
Image: gotenberg/gotenberg:7

**Comment by gulien** [comment]
Looks like there is currently now way to set the DPI/PPI of a PDF with Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=741049v

Puppeteer users seem to have found a workaround, I may explore a solution around that but not ETA: https://github.com/puppeteer/puppeteer/issues/1057
