### ISSUE TITLE
Get page count in recieved PDF after using Merge at "Convert with LibreOffice"

### ISSUE THREAD

**Issue by feroxy01** [gotenberg/gotenberg#748]
After using "Merge" at "Convert with Libre Office" the finally resulted PDF contains a page count at the botton of each page. For instance "Seite 1 von 1" in english "Page 1 of 1". As far as I concerned, I'm not able to prevent this so far. Or is there already a possibility? 
Thanks :)

Endpoint: /forms/libreoffice/convert

**Comment by gulien** [comment]
Weird: could you try the same request but with different PDF engines?

1. `--pdfengines-engines=pdftk,libreoffice-pdfengine`
2. `--pdfengines-engines=pdfcpu,libreoffice-pdfengine`
3. `--pdfengines-engines=qpdf,libreoffice-pdfengine`
