### ISSUE TITLE
panic: cannot create context from nil parent

### ISSUE THREAD

**Issue by low613** [gotenberg/gotenberg#753]
I am running gotenberg version 7.10.1, I am periodically receiving the following stack trace
it is being run with the command line flag `--chromium-restart-after=1` to work around session expired cookies being persisted in the cookie jar.
```
panic: cannot create context from nil parent
goroutine 47582 [running]:
context.WithDeadlineCause({0x0?, 0x0?}, {0x1747860?, 0x36b16a1?, 0x1747860?}, {0x0?, 0x0?})
	/usr/local/go/src/context/context.go:615 +0x3d5
context.WithDeadline(...)
	/usr/local/go/src/context/context.go:607
context.WithTimeout({0x0, 0x0}, 0x1747860?)
	/usr/local/go/src/context/context.go:685 +0x4d
github.com/gotenberg/gotenberg/v7/pkg/modules/chromium.(*chromiumBrowser).pdf(0xc000114540, {0x1050b48, 0xc0001b5500}, 0xc0001b5420, {0xc0003ff5e0, 0x50}, {_, _}, {0x0, 0x3b9aca00, ...})
	/home/pkg/modules/chromium/browser.go:236 +0x2cf
github.com/gotenberg/gotenberg/v7/pkg/modules/chromium.(*Chromium).Pdf.func1()
	/home/pkg/modules/chromium/chromium.go:434 +0x67
github.com/gotenberg/gotenberg/v7/pkg/gotenberg.(*processSupervisor).runWithDeadline.func1()
	/home/pkg/gotenberg/supervisor.go:220 +0x22
created by github.com/gotenberg/gotenberg/v7/pkg/gotenberg.(*processSupervisor).runWithDeadline in goroutine 47300
	/home/pkg/gotenberg/supervisor.go:219 +0x94
```

I am usure what is triggering this though as it is occurring intermittently.

**Comment by gulien** [comment]
@low613 `gotenberg/gotenberg:edge` is available with a fix. I was not able to reproduce your issue with the new version.
I plan to make another release with a new flag for clearing the cache between requests.

**Comment by gulien** [comment]
@low613 the new `gotenberg/gotenberg:edge` version now also provides a `--chromium-clear-cookies` flag (bool, default to `false`) so that you don't have to restart your browser between each conversion.

**Comment by low613** [comment]
Thanks, Looking forward to when 8.0 is release :)

**Comment by JorenNagels** [comment]
Hey, I am on v8.23.2 and got this same error `cannot create context from nil parent`
Any idea if this was fixed already?

**Comment by maciejk-code** [comment]
I got the same issue on v8.25.0
