### ISSUE TITLE
[BUG] Header and footer resolution changed between Versions 7.9.1 and 7.9.2

### ISSUE THREAD

**Issue by will2877** [gotenberg/gotenberg#766]
There is a difference in the header and footer resolution between the versions 7.9.1 and 7.9.2.

I am using the chromium endpoint to convert html to pdf.
The image was base64 encoded and added to the `header.html` document.

Converting it using Gotenberg 7.9.1 gives this result:
![Screenshot from 2024-01-03 15-00-45](https://github.com/gotenberg/gotenberg/assets/43466887/90877872-4d82-4aa4-be4d-abeee2685731)

Converting it using Gotenberg 7.9.2 gives this result:
![Screenshot from 2024-01-03 15-00-06](https://github.com/gotenberg/gotenberg/assets/43466887/1c4c5d08-58d5-4867-87f0-9768926a4db5)

Did you make any changes to this functionality between the versions?
Is there a logical migration path?
All my headers and footers are set to the result in version 7.9.1....

**Comment by gulien** [comment]
I did not 😕 It is either a bug or new behavior from Chromium. Nothing much I can do alas.

Related: https://github.com/gotenberg/gotenberg/issues/699.
