### ISSUE TITLE
v8.0.0 high cpu usage - reverted to previous version

### ISSUE THREAD

**Issue by mobiledude** [gotenberg/gotenberg#768]
after updating on my unraid machine it looks like the v8 version fully allocates the cpu, making my system unresponsive. returning to previous version makes it run properly again

**Comment by gulien** [comment]
Hello @mobiledude,

I do not see any change regarding CPU usage on both the demo instance and locally. Also, the v8 release did not change anything particular vs latest v7. If anything, it looks like an issue on your end 🤔 

Which version have you rollback to?

**Comment by mobiledude** [comment]
I went back to 7.10.2. And things turned quiet. It must be system specific as other unraid users have reported back having it working with version 8 and not having issues. Will try to update again this weekend and see if it returns. Will report back.

**Comment by gulien** [comment]
I’m closing this as the issue does not seem related to Gotenberg. Feel free to reopen it if you find new information suggesting the contrary 👍
