### ISSUE TITLE
Is it possible to pass the SinglePageSheets parameter to LibreOffice through gotenberg?

### ISSUE THREAD

**Issue by cuipengfei** [gotenberg/gotenberg#778]
Ref Link: https://ask.libreoffice.org/t/libreoffice-xls-to-pdf-conversion-breaks-single-page-content-into-multiple-pages-on-ubuntu-18-04/49104/2

This parameter is supported by LibreOffice fater v7.4, can it be passed through gotenberg?

**Comment by gulien** [comment]
Hello @cuipengfei thanks for the details!

I’m not using LibreOffice directly when it comes to conversion, but UNO via unoconv. I’ll plan to work on my own implementation but no eta 😅

if you want to dig in the meantime: https://github.com/gotenberg/unoconverter

**Comment by gulien** [comment]
Done in #844
