### ISSUE TITLE
How to generate PDF/A compatible PDF files?

### ISSUE THREAD

**Issue by HoffmannTom** [gotenberg/gotenberg#779]
Hello, 
I couldn't create a PDF/a compatible pdf-file with the current Gotenberg 8.0.1 version.
According to https://gotenberg.dev/docs/configuration I set the pdf-engines in my compose-file :
```
    environment:
      - pdfengines-engines="libreoffice-pdfengine,pdftk"
```

Afterward, I created a test.docx and tried to create a PDF/A compatible file with curl:
`curl --request POST https://hostname/forms/libreoffice/convert --form 'pdfa="PDF/A-3b"' --form files=@test.docx -o test.pdf`

According to https://gotenberg.dev/docs/routes the parameter pdfa should produce PDF/A compatible format.

I validated the file online at https://avepdf.com/pdfa-validation which shows several errors (missing XMP Metadata etc.)

Is there anything wrong in my setting or is the parameter not passed to LibreOffice?
When I use LibreOffice, the resulting PDF is PDA/A compatible.

PDF/A compatible invoices will be mandatory in Germany next year. Thus, this feature will be essential.

Thanks for any advice in advance!
Thomas

**Comment by gulien** [comment]
Hello @HoffmannTom,

What's your LibreOffice version? Do you ask specifically for `PDF/A-3b`?  Does it happens with other variant, i.e., `PDF/A-1b`, `PDF/A-2b`, etc.

**Comment by HoffmannTom** [comment]
Hello @gulien 
I downloaded LibreOffice 7.6.4.1 and successfully tested it. It generates PDF/A compatible files according to the online check.

I also tried setting the gotenberg parameter to PDF/A-1b and PDF/A-2b but with the same negative result.
(for electronic invoices, PDF/A-3b is needed because embedding of XML-files is not specified for older versions)

It looks like the parameter pdfa doesn't have any effect in my case. 
Can you reproduce the behavior? If it happens on your side too, it might be a general issue.
Otherwise, it might depend on my setting.

**Comment by gulien** [comment]
Does it work on the demo instance? (https//demo.gotenberg.dev)

**Comment by HoffmannTom** [comment]
Hello @gulien 
it shows the same negative result about PDF/A compability:
![image](https://github.com/gotenberg/gotenberg/assets/27145868/f632e243-8cec-4b93-ad29-b9b070488bc3)

I used:
`curl --request POST https://demo.gotenberg.dev/forms/libreoffice/convert --form 'pdfa="PDF/A-3b"' --form files=@test.docx -o test2.pdf`
So it seems, that it is not related to the setup. Could you track if the parameter reaches the LibreOffice instance?

**Comment by gulien** [comment]
<img width="302" alt="Capture d’écran 2024-01-17 à 17 08 04" src="https://github.com/gotenberg/gotenberg/assets/8983173/277cb45c-9a7b-4e01-bf66-b16d5d52755a">

That's weird, it should not validate against `PDF/A-1a` there.

**Comment by HoffmannTom** [comment]
Hello, 
I used the default "Auto-detect" on the website.
When choosing PDF/A-3b explicitly there are even more errors:
![image](https://github.com/gotenberg/gotenberg/assets/27145868/184ef3bb-0e78-47d9-ab56-fbf6a62e51c7)
You could also use other validation websites like https://www.pdfforge.org/online/en/validate-pdfa 
This website also reports the same errors.
PDF/A-3b allows the embedding of new file formats. If you don't embed any file, then PDF/A-2b and PDF/A-3b might be the same.

**Comment by gulien** [comment]
```
curl --request POST \
  --url http://localhost:3000/forms/libreoffice/convert \
  --header 'Content-Type: multipart/form-data' \
  --form files=@document.docx \
  --form pdfa=PDF/A-3b
```

Using https://avepdf.com/fr/pdfa-validation with "Auto-Detect":

1. Gotenberg 7.10.0 & LibreOffice 7.5.8.2 - ✅ [7.10.0.pdf](https://github.com/gotenberg/gotenberg/files/13974538/7.10.0.pdf)
2. Gotenberg 7.10.2 & LibreOffice 7.6.4.1 - ✅ [7.10.2.pdf](https://github.com/gotenberg/gotenberg/files/13974611/7.10.2.pdf)
3. Gotenberg 8.0.1 & LibreOffice 7.6.4.1 - ✅ [8.0.1.pdf](https://github.com/gotenberg/gotenberg/files/13974650/8.0.1.pdf)

Those are simple converted files though.

---

```
 environment:
      - pdfengines-engines="libreoffice-pdfengine,pdftk"
```

Btw, this is not how you set flags, see: https://gotenberg.dev/docs/getting-started/installation#modules-configuration

**Comment by HoffmannTom** [comment]
Ah... so the compose file might be the issue.
I will try that on weekends and report back.
Thanks for your hints :)

**Comment by HoffmannTom** [comment]
Got it now 😶‍🌫️
The issue lies in the curl parameters.

Working:
`curl --request POST https://xxx/forms/libreoffice/convert --header "Content-Type: multipart/form-data" --form files=@test.docx --form pdfa=PDF/A-3b -o test.pdf`

Not working:
`curl --request POST https://xxx/forms/libreoffice/convert --header "Content-Type: multipart/form-data" --form files=@test.docx --form 'pdfa="PDF/A-3b"' -o test.pdf`

Maybe it is a Windows issue but I needed to omit the ' and " in the form parameters. I had to remove them all in order to make it work.
I copied the curl example from:
https://gotenberg.dev/docs/routes
![image](https://github.com/gotenberg/gotenberg/assets/27145868/dabf7817-38db-4b99-accd-ff799d9952ca)

Maybe you can remove the quotes there too.
(for the parameter pdfua one quote would be missing anyway)

**Comment by HoffmannTom** [comment]
what also worked for me on Windows:
`--form "pdfa=\"PDF/A-3b\""`

Single quotes don't work on Windows and double quotes have to be escaped therefore.

**Comment by gulien** [comment]
Ah sh*t, good catch! Those are c/c from Postman, I may have to update them 🤔

**Comment by HoffmannTom** [comment]
If you want it to be compatible with Linux and Windows, I recommend omitting the quotes (single and double) as much as possible.
They are treated differently and cause trouble 😬
Many thanks for your support and teamwork to figure it out 👍👍

**Comment by gulien** [comment]
Documentation has been updated 👍 

I've removed most quotes, but wasn't able to delete all of them. For instance for headers:

```bash
curl \
--request POST http://localhost:3000/forms/chromium/convert/url \
--header 'Gotenberg-Webhook-Extra-Http-Headers: {"MyHeader": "MyValue"}' \
--header 'Gotenberg-Webhook-Url: https://my.webhook.url' \
--header 'Gotenberg-Webhook-Method: PUT' \
--header 'Gotenberg-Webhook-Error-Url: https://my.webhook.error.url' \
--header 'Gotenberg-Webhook-Error-Method: POST' \
--form url=https://my.url
```

**Comment by Cluster2a** [comment]
> Hello @gulien I downloaded LibreOffice 7.6.4.1 and successfully tested it. It generates PDF/A compatible files according to the online check.
> 
> I also tried setting the gotenberg parameter to PDF/A-1b and PDF/A-2b but with the same negative result. (for electronic invoices, PDF/A-3b is needed because embedding of XML-files is not specified for older versions)
> 
> It looks like the parameter pdfa doesn't have any effect in my case. Can you reproduce the behavior? If it happens on your side too, it might be a general issue. Otherwise, it might depend on my setting.

@HoffmannTom, how are you planning to embedd additional XMLs with gotenberg?

**Comment by HoffmannTom** [comment]
Hello Alex!
I can create PDF/A-3b with gotenberg. In Java the HTTP post looks like:
MultipartEntityBuilder builder = MultipartEntityBuilder.create();
builder.addTextBody("pdfa", "PDF/A-3b");

After conversion to PDF the plan is to add the XML file via the following library:
https://github.com/ZUGFeRD/mustangproject

Just theory for now, I hope it will work as planned.

**Comment by Cluster2a** [comment]
@HoffmannTom, currently we are creating the PDF via gotenberg and the XML via Easybill\ZUGFeRD2.
I was able to migrate the pdf with mpdf (https://mpdf.github.io/what-else-can-i-do/pdf-a3-xmp-rdf.html).

I thought there might be a way to use gotenberg for the embedding of the xml.
