### ISSUE TITLE
Persian fonts not loaded in header and footer

### ISSUE THREAD

**Issue by WolfDeveloper97** [gotenberg/gotenberg#783]
Hi 

I have gotenberg installed with docker compose

and mount a volume in docker-compose file to load custom persian fonts 
`      - /opt/gotenberg/fonts:/usr/local/share/fonts/`

but in header and footer fonts not loaded

**Comment by MRezaKarimi** [comment]
Update to the version 8. The problem solves!

**Comment by gulien** [comment]
Closing this. Please reopen if necessary 👍
