### ISSUE TITLE
Improvement on the documentation

### ISSUE THREAD

**Issue by MarkTro** [gotenberg/gotenberg#785]
I know, this isn't the right place for this change, but I couldn't found any place where to contribute.

I followed the instruction to create a footer of this documentation: https://gotenberg.dev/docs/routes#header-footer-chromium
And I found to unlucky point in the example:

- The `font-size` is set with a rem value. I had the problem that my root object (html) had had a font size of 0, which results to a footer font size of 0 as well. For this reason I recommend to change the font-size to a px value to avoid this problem. I know that rem sizing is the state of the art, but an example should be easy to understand and should have less dependencies as possible.
- The second thing are the `margin` values. With the values `4rem auto` the footer is shift out of focus of the site, because the margin effects vertical. And again, I hadn't a footer visible. I would suggest to change this to a horizontal margin like `auto 20px`.

**Comment by gulien** [comment]
Hey @MarkTro,

Thanks for the heads up!

> I had the problem that my root object (html) had had a font size of 0, which results to a footer font size of 0 as well

Interesting, I was always on the impression that most CSS were totally separate between the header/footer and the actual page.

> With the values 4rem auto the footer is shift out of focus of the site, because the margin effects vertical

Could you give me a working example and a screenshot before/after?

**Comment by MarkTro** [comment]
Hey @gulien ,
you're right, they're separated. I think that is the root of way "rem" doesn't work fine. 
If you change the example to this:
```
<html>
<head>
    <style>
    body {
        font-size: 12px;
        margin: auto 20px;
    }
    </style>
</head>
<body>
<p><span class="pageNumber"></span> of <span class="totalPages"></span></p>
</body>
</html>
```
it looks like that (without the red border):
![pdf-footer-example](https://github.com/gotenberg/gotenberg/assets/12793886/a67d9741-d40f-46b1-8a2f-f443b31840bc)

**Comment by gulien** [comment]
Thanks @MarkTro!

**Comment by gulien** [comment]
Documentation has been updated 👍
