### ISSUE TITLE
 chrome failed to start

### ISSUE THREAD

**Issue by RobinKamps** [gotenberg/gotenberg#790]
On debian 10  / docker version: 19.03.8 gotenberg:latest fails with logs:

```
[FATAL] starting chromium: launch supervisor: start process: run exec allocator: chrome failed to start:
[0201/191831.586807:FATAL:spawn_subprocess.cc(236)] posix_spawn: Operation not permitted (1)
[0201/191831.747550:WARNING:spawn_subprocess.cc(260)] intermediate process terminated by signal 5 (Trace/breakpoint trap) (core dumped)
```

the machine has enough ressources (8Gib, 4CPUs), sadly i can not update Debian or the old docker version.

**Comment by gulien** [comment]
Hello @RobinKamps,

Might be the same issue as described here #784.

> sadly i can not update Debian or the old docker version.

Not much I can do there, alas. Maybe try to host your Gotenberg instances elsewhere?

**Comment by RobinKamps** [comment]
it works with gotenberg/gotenberg:7.9

**Comment by RobinKamps** [comment]
it seems on docker <20.10.10 images with binaries are linked via glibc>=2.34 . these will throw EPERM Errors on some syscalls.

perhaps the latest gotenberg:gotenberg docker images are build with glibc>=2.34 (e.g. based on bookworm).
