### ISSUE TITLE
Chrome fails to start on Docker for macOS

### ISSUE THREAD

**Issue by jgimenez** [gotenberg/gotenberg#792]
I'm using the `gotenberg:8` docker image  (but also tested with 7 images) and I consistently get a 500 error when running something like this:

```sh
curl --request POST 'http://localhost:10000/forms/chromium/convert/url' \
--form 'url="https://sparksuite.github.io/simple-html-invoice-template/"'
Internal Server Error
```

The logs produced are quite cryptic:

```
gotenberg-1  | {"level":"error","ts":1707220350.6079977,"logger":"api","msg":"convert URL to PDF: convert to PDF: process first start: start process: run exec allocator: context canceled","trace":"761c3461-22f1-4518-b1e9-2f35d9320bc1","remote_ip":"192.168.65.1","host":"localhost:10000","uri":"/forms/chromium/convert/url","method":"POST","path":"/forms/chromium/convert/url","referer":"","user_agent":"curl/8.4.0","status":500,"latency":1353376793,"latency_human":"1.353376793s","bytes_in":208,"bytes_out":21}
```

I figured the problem has to do with the "Use Virtualization framework" in Docker Desktop for macOS. Disabling that feature makes gotenberg work again. I'm on a x86 mac.

I don't think this is a bug in the gotenberg project, but maybe it could provide a better error message and the documentation could mention this workaround.

This issue is likely the cause of the problem: https://github.com/docker/for-mac/issues/6824

**Comment by gulien** [comment]
Thanks for the details @jgimenez!

**Comment by gulien** [comment]
Documentation has been updated 👍
