### ISSUE TITLE
how to emulate css media type screen when generating PDF via chromium?

### ISSUE THREAD

**Issue by hrvoj3e** [gotenberg/gotenberg#794]
It seems that this is supported by Chromium and Puppeteer uses it also so why not Gotenberg.

I am just trying to get an exact page in PDF but print media overrides are getting in the way.
Forcing or emulating css media type would make a big difference.

Context
 - https://developer.chrome.com/docs/devtools/rendering/emulate-css
 - https://pptr.dev/api/puppeteer.page.emulatemediatype
 - https://github.com/puppeteer/puppeteer/issues/2061

**Comment by gulien** [comment]
Hello @hrvoj3e,

Is https://gotenberg.dev/docs/routes#emulated-media-type-chromium not enough?

**Comment by hrvoj3e** [comment]
OMG, how did I miss this. 
Sorry. Delete this issue.

**Comment by gulien** [comment]
haha, it happens 👍
