### ISSUE TITLE
gotenberg doesn't apply page sizing to excel file conversion when sheet is just a large figure

### ISSUE THREAD

**Issue by PrathamSoni** [gotenberg/gotenberg#799]
despite adding scale and page size options the figure is still cut between multiple pages. also, landscape is only applied to some pages.

**Comment by PrathamSoni** [comment]
@gulien  can you add this option for single page sheets: 'pdf:calc_pdf_Export:{"SinglePageSheets":{"type":"boolean","value":"true"}}'

**Comment by gulien** [comment]
Closing this as duplicate of #36
