### ISSUE TITLE
Merge order hard to obtain in some scenarios

### ISSUE THREAD

**Issue by hazrul** [gotenberg/gotenberg#805]
## Expected Behavior
when i merge multiple pdf files, the result pdf should be ordered . for example : i merge 1.pdf , 2.pdf ,3.pdf , 4.pdf , the sum pdf file should be 1,2,3,4 turn ,the asc order. The number of pdf I merge varies, could be more than 20 pdf files.

## Current Behavior
i got the result pdf ,which have the 1,4,3,2 turn , it's out-of-order

## Steps to Reproduce (for bugs)
1.prepare three or more pdf files , 1.pdf , 2.pdf ,3.pdf,4.pdf 2.request the merge feature 3.check the order of the result pdf 4.

## Context
* Version used: 8

**Comment by gulien** [comment]
Hey @hazrul

I was not able to reproduce your issue:

```bash
curl --request POST \
  --url https://demo.gotenberg.dev/forms/pdfengines/merge \
  --header 'Content-Type: multipart/form-data' \
  --form files=@1.pdf \
  --form files=@2.pdf \
  --form files=@3.pdf \
  --form files=@4.pdf
```

[PDF_Engines_Merge-1708333204221.pdf](https://github.com/gotenberg/gotenberg/files/14328821/PDF_Engines_Merge-1708333204221.pdf)

**Comment by hazrul** [comment]
Hi @gulien can you try reproduce with more pdf. I did one with 40 pdf still having the same issue

**Comment by gulien** [comment]
I suppose this is because, alphabetically, 1 or 10 are sorted before 2 and 20 for instance. I've solved this using in my PHP client by using an [hrtime](https://www.php.net/manual/en/function.hrtime.php) index (https://github.com/gotenberg/gotenberg-php/blob/main/src/HrtimeIndex.php). 

No ideal overall.
