### ISSUE TITLE
Header/Footer identify even/odd page

### ISSUE THREAD

**Issue by ITspirit** [gotenberg/gotenberg#806]
I need to know it the Header/Footer is on a even or odd page Number.

As far the Header/Footer doesn´t execute JS. 
I have only placeholders for limited variables.

I need a suitable option that i can use different CSS on even/odd pages.

Maybe a automatic injected body class "even" / "odd" would help a lot.

Or are there any other possible solutions/workarounds?

**Comment by gulien** [comment]
Hey @ITspirit,

The header/footer feature is enabled by Chromium, I cannot add anything more than what’s currently available. 

A workaround may be to create your own header/footer directly in the `body` and find a way to determine if a page is even using JS or else.
