### ISSUE TITLE
pdfcpu - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by h4ckroot** [gotenberg/gotenberg#808]
I am facing the same issue happening in this one: https://github.com/gotenberg/gotenberg/issues/673

I have gone through testing various old releases,  and I found that the merge was working up to version 7.9.0. Starting from version 7.9.1, it started crashing (panic). 

I hope that could narrow down the problematic release.

=== Error Log from container =====

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc066a3]

goroutine 343 [running]:
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.EnsureOutlines(0xc0001117d0, {0xc0004d258f, 0x5}, 0x0)
	/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/pkg/pdfcpu/merge.go:78 +0x5e3
github.com/pdfcpu/pdfcpu/pkg/api.prepDestContext({0xc0004d2540, 0x54}, {0x10ae758, 0xc0001340a0}, 0xc00048b520)
	/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/pkg/api/merge.go:91 +0x99
github.com/pdfcpu/pdfcpu/pkg/api.Merge({0x0?, 0x77?}, {0xc00003e600?, 0x1?, 0x1?}, {0x10a5440, 0xc000134088}, 0x7d2c65?, 0xb0?)
	/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/pkg/api/merge.go:134 +0x265
github.com/pdfcpu/pdfcpu/pkg/api.MergeCreateFile({0xc00003e600, 0x3, 0x4}, {0xc0002e2000, 0x77}, 0x1?, 0x1?)
	/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/pkg/api/merge.go:191 +0x145
github.com/gotenberg/gotenberg/v8/pkg/modules/pdfcpu.(*PdfCpu).Merge(0x0?, {0xc000440500?, 0xc00003e600?}, 0x3?, {0xc00003e600?, 0xc00002b7d0?, 0x8c2c85?}, {0xc0002e2000?, 0xc000140000?})
	/home/pkg/modules/pdfcpu/pdfcpu.go:44 +0x38
github.com/gotenberg/gotenberg/v8/pkg/modules/pdfengines.(*multiPdfEngines).Merge.func1({0x7fbb52e85308?, 0xc00049c0f0?})
	/home/pkg/modules/pdfengines/multi.go:31 +0x4d
created by github.com/gotenberg/gotenberg/v8/pkg/modules/pdfengines.(*multiPdfEngines).Merge in goroutine 341
	/home/pkg/modules/pdfengines/multi.go:30 +0x265

**Comment by h4ckroot** [comment]
@gulien Thanks for you prompt response.

Yes, I tested on latest version 8.1.0, and it have the same issue.

**Comment by gulien** [comment]
Looks like an issue with *pdfcpu v0.0.6* 🤔

Using `--pdfengines-engines=qpdf,uno-pdfengine,pdftk` is still a valid workaround.

Could you share the faulting PDFs?

**Comment by h4ckroot** [comment]
Unfortunately, it does contain some sensitive information!. Any suggestions with that?

**Comment by gulien** [comment]
Could you remove somehow these sensitive data? 😅

**Comment by stefannovak** [comment]
Hey, I had the same issue. Putting pdfcpu at the end of the pdf engine order solved the issue for me. Hope it can be resolved because it's kind of scary having a broken engine to fallback on! Cheers

**Comment by gulien** [comment]
👍 I'll soon release a new Gotenberg version that contains the latest pdfcpu version. Hopefully it will resolve this issue.

**Comment by stefannovak** [comment]
> 👍 I'll soon release a new Gotenberg version that contains the latest pdfcpu version. Hopefully it will resolve this issue.

Cool! I'll test it when you do and let you know

**Comment by gulien** [comment]
@stefannovak Could you test your scenario with Gotenberg `8.2.2`? Thanks 😊

**Comment by stefannovak** [comment]
> @stefannovak Could you test your scenario with Gotenberg `8.2.2`? Thanks 😊

It's fixed! Nice one!

**Comment by gulien** [comment]
Thanks for your quick response!
