### ISSUE TITLE
Filename not being set on upload to S3.

### ISSUE THREAD

**Issue by kabobbob-alto** [gotenberg/gotenberg#809]
Similar to #495, we have a service that is sending requests to gotenberg to generate a PDF and upload the result to S3. In our request, we are setting the headers `Gotenberg-Output-Filename` with our intended filename and `Gotenberg-Extra-Http-Headers` with "Content-Disposition: attachment; filename=[intended filename]". For the majority of our requests (about 90%), the filename is set as intended, however for others, the filename that is sent is the temporary filename from the [api package](https://github.com/gotenberg/gotenberg/blob/25ce0b9aeeeffa79542e575f10d4133c487acf8a/pkg/modules/api/context.go#L267) that is used in the PDF generation. We're running gotenberg 8.1.0. 

Request:
```dispatch report to gotenberg with headers: map[Content-Type:[multipart/form-data; boundary=cde7d6f7561fa1c61ecb86f03b78fa129d0ea29022ec132db8ef21f10b15 multipart/form-data; boundary=MyBoundary] Gotenberg-Output-Filename:[Report-2023-12-909097] Gotenberg-Webhook-Error-Method:[PUT] Gotenberg-Webhook-Error-Url:[http://internal-service/[report_uuid]] Gotenberg-Webhook-Extra-Http-Headers:[{"Content-Disposition": "attachment; filename=Report-2023-12-909097"}]```

**Comment by gulien** [comment]
Hello @kabobbob-alto,

Specifying the *Content-Disposition* in `Gotenberg-Extra-Http-Headers` won’t do anything, as Gotenberg [overrides this header anyway](https://github.com/gotenberg/gotenberg/blob/25ce0b9aeeeffa79542e575f10d4133c487acf8a/pkg/modules/webhook/middleware.go#L257).

Also, I don’t see any reason in the source code that could explain your issue 🤔 are you sure that you’re always sending the output filename?

**Comment by kabobbob-alto** [comment]
Thank you for getting back to me. We log the headers right before we send the request like so:

```
func (c *Client) Do(logger zerolog.Logger) (*http.Response, error) {
	client := &http.Client{}
	logger.Info().Msgf("request headers: %+v", c.Request.Header)
	resp, err := client.Do(c.Request)
	return resp, err
}
```

and here is an example of a request with the header set (I dumped "extra http headers"):

```
request headers: map[Content-Type:[multipart/form-data; boundary=c58067ac46420fbe2c0c2c65896e32b9ad4fd8298e7be0e2dc836776bd2d multipart/form-data; boundary=MyBoundary] Gotenberg-Output-Filename:[Report-2023-12-561483] Gotenberg-Webhook-Error-Method:[PUT] Gotenberg-Webhook-Error-Url:[http://internal-service/[report-uuid]] Gotenberg-Webhook-Method:[PUT] Gotenberg-Webhook-Url:[http://aws.s3.put.url]]
```

We've looked in the logs for gotenberg, however, we're not seeing any headers in the request [output](https://github.com/gotenberg/gotenberg/blob/25ce0b9aeeeffa79542e575f10d4133c487acf8a/pkg/modules/api/middlewares.go#L190).

**Comment by gulien** [comment]
The logging for a webhook process is actually done [here](https://github.com/gotenberg/gotenberg/blob/25ce0b9aeeeffa79542e575f10d4133c487acf8a/pkg/modules/webhook/client.go#L109).

> For the majority of our requests (about 90%), the filename is set as intended

I actually want to know if your are always setting the `Gotenberg-Output-Filename` header, or if there is a bug on your side where it's en empty string?

This feature has been available for a few years, and that's the first time I've heard of this issue 🤔 

Also, I cannot explain this randomness code wise, nor I am able to reproduce your issue 😅

**Comment by kabobbob-alto** [comment]
Sorry for the delay in responding. Yeah, it's a weird random issue that we were seeing and we were curious if the devs had any experience with it. For the time being, we've gone a different route. If we circle back on this, we'll be sure to update what happened. Thank you!
