### ISSUE TITLE
Feature: Ability to specify emulated device metrics and clipping screenshot in chromium image screenshot route

### ISSUE THREAD

**Issue by rslinckx** [gotenberg/gotenberg#816]
This is a followup from https://github.com/gotenberg/gotenberg/issues/421

Gotenberg now has the ability to take a full-page image screenshot of an URL. However there is no way to specify the size of the resulting image.

The way we achieve this internally is by using the following two features of the devtools protocol:
* `Emulation.setDeviceMetricsOverride(width=1280, height=800)`
* `Page.captureScreenshot(format='png', clip={"x": 0, "y": 0, "width": 1280, "height": 800, "scale": 1})`

This will of course crop the website to the desired dimensions, and is no longer a full-page screenshot, but at least it can be served up as a thumbnail of the website with known dimensions. It is somehow equivalent to using paperHeight/paperWidth on the pdf conversion.

It would be great to be able to specify width and height in pixel value as form parameters for the `/forms/chromium/screenshot/url` route. Maybe the two should be exposed separately (clip and device metrics) as I believe the full-page capture also benefits from the device metrics being set.

I also found a PR https://github.com/gotenberg/gotenberg/pull/787 and another issue https://github.com/gotenberg/gotenberg/issues/786 which seem related, but do something with the viewport, which i'm not sure is the way to go here.

**Comment by gg-gaborginter** [comment]
Hi @rslinckx,

There is no magic done in #787: I was using the https://pkg.go.dev/github.com/chromedp/chromedp#EmulateViewport function of the Chrome API, which does in effect the same thing as `Emulation.setDeviceMetricsOverride(...)`.

What I learned out of my experiment is that you need to split the resizing into two steps:
1. have the browser window resized to the desired sizes (emulate viewport call)
2. navigate to the page you would like to render
3. make the screenshot, with the desired viewport (this can be different to the one in step one)

Had you also defined capturing beyond the viewport, then your screenshot height will automatically adapt to the rendered page content.

**Comment by gulien** [comment]
Done in https://github.com/gotenberg/gotenberg/commit/0f0a6ce042e58a36a80ce9168238367434c6c052.
