### ISSUE TITLE
Versions > 7.9.2 slower with increased timeouts

### ISSUE THREAD

**Issue by sww314** [gotenberg/gotenberg#819]
## Problem

Increased timeouts/poor performance with Headless Chrome HTML -> PDF.

I am  running gotenberg and HeadlessChrome to convert html pages to PDF. It is running on Google Cloud in Cloud Run. 
Version 7.9.2 was working fine - no issues. 

We tried to upgrade to 8.0.2. We noticed poorer performance overall. (Slower). Along with that increased timeouts. 
Then we recently tried 8.2.0 and the performance is worse. We ended up rolling back to 7.9.2.

## Setup: 
gotenberg is Docker container running in Cloud Run
The generated HTML is hosted in same Google Cloud project. 

Using same test setup:
 - 8.2.0 timed out at 60 seconds 
 - 7.9.2 was returning < 10 seconds

It is in an isolated test environment, so it is not a traffic/cpu/memory issue. 

Any ideas on what to look for or how to debug the issue?

**Comment by gulien** [comment]
Hello @sww314 👋 

I’d suggest the following:

1. `—chromium-auto-start=true`
2. Use the form field `skipNetworkIdleEvent`

`8.2.0` now produces tagged PDFs by default, I guess it may increase the rendering time 🤔

I did not notice anything particular regarding performance on the demo instance though.

With `—log-level=debug`, do you see if the URL where your generated content comes from is actually loaded?

**Comment by MathiasGr** [comment]
Hey there - I just wanted to flag that we've seen the same regression and `skipNetworkIdleEvent` seems to have fixed the issue. Thanks!
