### ISSUE TITLE
every morning Oman time the PDF rendering is having break down! with Maximum CPU Usage

### ISSUE THREAD

**Issue by mjapple** [gotenberg/gotenberg#826]
` docker exec -it cb29da838ac0 ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
gotenbe+       1  0.0  0.0   2464   884 ?        Ss   08:47   0:00 /usr/bin/tini -- gotenberg
gotenbe+       8  0.2  0.1 1247464 19580 ?       Sl   08:47   0:00 gotenberg
gotenbe+      29  1.4  0.7 34036864 117968 ?     Sl   08:48   0:01 /usr/bin/chromium --mute-audio --disable-backgrounding-occluded-windows --disable-ipc-flooding-protection --disable-popup-blocking --disable-client-side-phishin
gotenbe+      34  0.0  0.0   2616   880 ?        S    08:48   0:00 cat
gotenbe+      35  0.0  0.0   2616   892 ?        S    08:48   0:00 cat
gotenbe+      37  0.0  0.0 33575504 1644 ?       Sl   08:48   0:00 /opt/google/chrome/chrome_crashpad_handler --monitor-self-annotation=ptype=crashpad-handler --database=/tmp/Crashpad --url=https://clients2.google.com/cr/report
gotenbe+      41  0.0  0.3 33848420 55220 ?      S    08:48   0:00 /opt/google/chrome/chrome --type=zygote --no-zygote-sandbox --no-sandbox --headless --headless --crashpad-handler-pid=37 --enable-crash-reporter
gotenbe+      42  0.0  0.3 33848424 56168 ?      S    08:48   0:00 /opt/google/chrome/chrome --type=zygote --no-sandbox --headless --headless --crashpad-handler-pid=37 --enable-crash-reporter
gotenbe+      57  0.3  0.4 33978344 72004 ?      Sl   08:48   0:00 /opt/google/chrome/chrome --type=gpu-process --no-sandbox --disable-dev-shm-usage --disable-breakpad --headless --ozone-platform=headless --use-angle=swiftshade
gotenbe+      62  0.4  0.5 33914708 96152 ?      Sl   08:48   0:00 /opt/google/chrome/chrome --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --no-sandbox --disable-dev-shm
gotenbe+      65  0.1  0.4 1186119968 80024 ?    Sl   08:48   0:00 /opt/google/chrome/chrome --type=renderer --headless --crashpad-handler-pid=37 --no-sandbox --disable-dev-shm-usage --disable-background-timer-throttling --disa
gotenbe+     153  4.4  0.6 1186145096 111660 ?   Sl   08:50   0:00 /opt/google/chrome/chrome --type=renderer --headless --crashpad-handler-pid=37 --no-sandbox --disable-dev-shm-usage --disable-background-timer-throttling --disa
gotenbe+     165 33.3  0.0   8080  3920 pts/0    Rs+  08:50   0:00 ps aux`

to me honestly is interesting this command line 

`/usr/bin/chromium --mute-audio --disable-backgrounding-occluded-windows --disable-ipc-flooding-protection --disable-popup-blocking --disable-client-side-phishin`

**Comment by gulien** [comment]
Hello @mjapple,

It may be a good idea to restart your Gotenberg instances from time to time. The long running Chromium process may become unstable overtime.

Not much I can do on my side alas.
