### ISSUE TITLE
v8.2.1 still produces tagged pdf

### ISSUE THREAD

**Issue by fu-infotrack** [gotenberg/gotenberg#831]
https://github.com/gotenberg/gotenberg/commit/804fcff5b6a06a113f882fc87a2bfa8db709a986 does not work as expected. chromium is still producing tagged pdf

tested on docker image 8.2.1

``` sh
curl --request POST http://localhost:3000/forms/chromium/convert/url --form url=https://gotenberg.dev/ -o my.pdf
```

![image](https://github.com/gotenberg/gotenberg/assets/146898020/84cad1a7-d836-4fc2-bd20-e3a3cbf829b8)

related: https://github.com/gotenberg/gotenberg/pull/818

**Comment by gulien** [comment]
Thanks @fu-infotrack!

Does it happens with version `8.1.0`?

**Comment by gulien** [comment]
Thanks!

So it seems, whatever the input sent via the DevTool protocol*, Chromium always generates tagged PDF 🤔 

*no tagged PDF instruction & explicit disabling of tagged PDF.

**Comment by gulien** [comment]
According to the internet, another option is to use `--disable-pdf-tagging` when launching Chromium.

**Comment by gulien** [comment]
@Deadly0 A new release is required for this change. No idea about the Chromium version that introduced this change.

**Comment by gulien** [comment]
Fixed in https://github.com/gotenberg/gotenberg/commit/7b7ffb427d7f441a8ef5a9c44601af3fc8570e50.
