### ISSUE TITLE
Convert into PDF/A & PDF/UA route does not work with many pdfs

### ISSUE THREAD

**Issue by roy20021** [gotenberg/gotenberg#835]
Hello,

in the process of upgrading from version 7 to 8, I am encountering an issue regards the route for converting to pdf/a format when more files are given as input.

Fine with 1 pdf:
![image](https://github.com/gotenberg/gotenberg/assets/1174320/5bfe501d-29ee-4e94-949d-16d7002f8287)

Failure with 2 pdfs:
![image](https://github.com/gotenberg/gotenberg/assets/1174320/0d3eb6a5-fabc-497b-9483-819768fef20c)

This the full log (debug level): 
[gotenberg pdfa.log](https://github.com/gotenberg/gotenberg/files/14569822/gotenberg.pdfa.log)

On the other hand, this is a success when using version 7:
![image](https://github.com/gotenberg/gotenberg/assets/1174320/db98ea10-1793-47ed-b70e-7f4e0e6206d8)

Additionally, the merge route works fine when using version 8:
![image](https://github.com/gotenberg/gotenberg/assets/1174320/47fba4ba-1d5b-4f3d-8bf9-81005fd2cd3d)

Regards,
Andrea

**Comment by gulien** [comment]
Hello @roy20021,

Thanks for the details! For version 7, you're using `7.10.2` I guess?

I was also able to reproduce the issue on the demo with very simple documents.

Could you test your scenarios with Gotenberg `8.0.2`, `8.0.3` and `8.1.0`?

**Comment by gulien** [comment]
I did some tests:

* ✅ 8.0.2
* ✅ 8.0.3
* 🔴 8.1.0

I suspect the following change is the culprit:

> Enhancements to .zip archive handling: original filenames are preserved in the output, eliminating the need for UUID-based naming conversions (e.g., document.docx to document.docx.pdf, file.pdf to file.pdf). This feature resolves issue https://github.com/gotenberg/gotenberg/issues/771, thanks to @chrishughes20!

**Comment by gulien** [comment]
Fixed in https://github.com/gotenberg/gotenberg/commit/5ad90ccdb88da9a3ca34e8aa1362d405406e3851.

**Comment by roy20021** [comment]
Hello @gulien , I have tested https://github.com/gotenberg/gotenberg/releases/tag/v8.2.2 and I confirm that now it is working fine.
Thank you for your prompt fix!
