### ISSUE TITLE
LibreOffice can convert more extensions

### ISSUE THREAD

**Issue by roy20021** [gotenberg/gotenberg#840]
Hello,

this is an enhancement request.

Gotenberg has hard-coded the list of the capable extensions that LibreOffice is able to manage: https://github.com/gotenberg/gotenberg/blob/eb054146d27aadbe8824e2f11c39bfaf030ecdbd/pkg/modules/libreoffice/api/api.go#L267

Therefore, at least the excluded extensions are not converted even if it would be fine: that's a pity.
![image](https://github.com/gotenberg/gotenberg/assets/1174320/c3a97433-1039-4d75-9369-1f0b82fb4277)

Example: [bridge.dxf.zip](https://github.com/gotenberg/gotenberg/files/14632539/bridge.dxf.zip) (I zipped it due of github's constraint)

![image](https://github.com/gotenberg/gotenberg/assets/1174320/56169ebe-1ec1-4839-b6c2-2538ec4825c4)

I converted manually with libreoffice and it works fine: [bridge.pdf](https://github.com/gotenberg/gotenberg/files/14632577/bridge.pdf)

At least, can the extensions list be updated in order to be exhaustive?
In general, might be interesting evaluate a best-effort approach and try to convert the submitted file regardless the extension (enabling such policy with a specific flag?).

**Comment by gulien** [comment]
Hello @roy20021!

Indeed, this might not be the best approach. 

A better way could be to try to convert whatever the user is sending us.

Do you know where I could find the complete list of file types that LibreOffice handles?

**Comment by roy20021** [comment]
@gulien I found something here: https://books.libreoffice.org/en/GS74/GS7410-FileFormatsSecurityExporting.html
I haven't digged into LibreOffice's source code.
