### ISSUE TITLE
How to change libreoffice api Fonts in docker Containers ?

### ISSUE THREAD

**Issue by zdn-leochen** [gotenberg/gotenberg#855]
Hey guys!

I run gotenberg in docker container, and use  Convert with LibreOffice.

convert xlsx to PDF 

But PDF font  is "Arial"

I want to change Font.

How could I change it?

**Comment by gulien** [comment]
Hello @zdn-leochen 👋 

No idea 🤔 

@mrbech do you know if there is a LibreOffice flag or else to handle such a scenario?

**Comment by mrbech** [comment]
Not sure, if the xlsx uses Arial probably not. If its because the xlsx file uses a font thats unavailable in the container, maybe.
Without an example file and more info on the desired output its hard to tell.

**Comment by zdn-leochen** [comment]
@gulien @mrbech  Thank you for your reply. My xlsx file uses a font thats unavailable in the container. So its uses default font.  
Such as Arial.
