### ISSUE TITLE
Add Version (/version) Route

### ISSUE THREAD

**Issue by Jaben** [gotenberg/gotenberg#856]
For the C# client (https://github.com/ChangemakerStudios/GotenbergSharpApiClient), I'd like to be able to query the current version of Gotenberg for support. It would be very handy to have a /version endpoint on Gotenberg to verify which API I'm working with.

Thanks for an awesome project!

**Comment by gulien** [comment]
Looks like it’s a recurring demand from client maintainers (ping @stumpylog) 😅 I still believe it’s better to have a specific client version per Gotenberg version, or, a client configuration that enables compatibility with a particular Gotenberg version.

Anyway, as it seems helpful, I’ll implement it 👍

**Comment by Jaben** [comment]
> Looks like it’s a recurring demand from client maintainers (ping @stumpylog) 😅 I still believe it’s better to have a specific client version per Gotenberg version, or, a client configuration that enables compatibility with a particular Gotenberg version.
> 
> Anyway, as it seems helpful, I’ll implement it 👍

Thank you! The version check will help with mismatched API problems that would otherwise be tough to track down.

**Comment by gulien** [comment]
Done in https://github.com/gotenberg/gotenberg/commit/2267c5be002a21c3ec6305ebca372cc4e5919093.

The route `/version` directly returns the version in *text/plain*. Please note that not all Gotenberg variants have a semver version. For instance, the demo instance will return `{gotenberg_version}-live-demo-snapshot`.

The `)/gotenberg:edge` tag should be available in ~1hour with this new feature.

**Comment by Jaben** [comment]
Great -- thanks!
