### ISSUE TITLE
Gotenberg docker crashed occasionally 

### ISSUE THREAD

**Issue by eyal-honeycomb** [gotenberg/gotenberg#868]
Hi,
We are using gotenberg (8.0.2) docker container in our microservice environment (GCP, K8s) to convert docx to pdf files. 
Most of the time everything works just fine, however, once in a while a request to the container will fail.
These are the logs we see:

![Screenshot 2024-04-28 at 23 05 55](https://github.com/gotenberg/gotenberg/assets/117825065/40c686d1-17e6-4758-ba86-bd6679d340ed)

Any idea why this happens and how to prevent such a crash?

**Comment by gulien** [comment]
Hello @eyal-honeycomb,

It looks like it's actually LibreOffice that crashes 🤔 (and hopefully your health check probes are restarting your instance).

Does it happen on a particular file?

**Comment by eyal-honeycomb** [comment]
Hi @gulien, thank you for your response.
It doesn't happen on a particular file, we convert many files from docx templates into pdfs, and it happens quite randomly it would seem. There is usually 5-7 days I think between each incident.

**Comment by gulien** [comment]
Did you setup a particular restart policy for LibreOffice? Alas, not much I can do in Gotenberg. The best approach is to let Kubernetes restart your pod in such a scenario.

**Comment by gulien** [comment]
Feel free to reopen this issue @eyal-honeycomb!
