### ISSUE TITLE
Why do webhooks not work with Google Cloud Run?

### ISSUE THREAD

**Issue by sweber83** [gotenberg/gotenberg#876]
Your docs state, that the gotenberg webhook feature does not work with Google Cloud Run.
https://gotenberg.dev/docs/getting-started/installation#cloud-run

What is the reason for that?
From looking at how Cloud Run works, I don't see why the webhook feature should not work there.

**Comment by gulien** [comment]
Hey @sweber83 👋 

The problem is that the container may be shutdown by the Cloud Run orchestrator before the webhook request is done. The reason is that Cloud Run only considers the « front » HTTP requests and is not aware of asynchronous processes.

**Comment by sweber83** [comment]
Hi @gulien 👋,

Thanks for your fast response!
That explains it.
