### ISSUE TITLE
Response Content-Length mismatch

### ISSUE THREAD

**Issue by gclego** [gotenberg/gotenberg#880]
Hello, Im getting this error - Exception Message : Response Content-Length mismatch: too many bytes written (3469 of 2937).
![image](https://github.com/gotenberg/gotenberg/assets/128026377/aaef1a68-e5de-468d-a795-35f35de9f4a9)

The docker is deployed on an azure app service. I'm using html route "/forms/chromium/convert/html", and got this error.

Any leads is appreciated!

**Comment by gulien** [comment]
Do you have more details? Does it happen on the demo instance (https://demo.gotenberg.dev)?

**Comment by gclego** [comment]
We increased cpu and memory of the app service and it now works!
