### ISSUE TITLE
[CHROMIUM] Route to allow source as PDF file to be converted (currently only HTML/Markdown/URL)

### ISSUE THREAD

**Issue by michelrisucci** [gotenberg/gotenberg#882]
Currently we have Chromium routes for sources in HTML, Markdown and URLs:

![image](https://github.com/gotenberg/gotenberg/assets/1094167/43edc6df-989e-4d24-abae-3b311436e858)

Is there a way to have a PDF file as source?
It's useful for when you want to change it's PDF-A standard or simply by regenerating it to normalize/fix broken PDF.

Currently, PDF Engines endpoints have a route able to convert from source PDF file:

![image](https://github.com/gotenberg/gotenberg/assets/1094167/328edf3b-7eaf-49f6-aa6f-872ecdccd112)

But it's simply not reliable as Chromium is. Tried some PDF files with EXIF pictures and it is breaking while trying to convert these attached pictures.
I would love to have the same behavior for Chromium.

**Comment by gulien** [comment]
Hello @michelrisucci 

Chromium only handles HTML based inputs. When you ask to convert to a specific PDF/A format, it's actually the LibreOffice PDF engine that does the job. In other words, HTML into PDF via Chromium, and then PDF/A via LibreOffice. The PDF engines endpoint just skip the HTML part and calls LibreOffice directly.

**Comment by michelrisucci** [comment]
@gulien got it, but Chrome browser is able to read PDFs and regenerate them by printing to PDF.
Aren't we able to have an API to print PDF from PDF file?
I tried LibreOffice PDF engine, but, as I said, I faced some errors logging something related to "EXIF" pictures converting (PDF attachments?).

**Comment by gulien** [comment]
Does Chrome really re-render a PDF? 🤔 

> It's useful for when you want to change it's PDF-A standard or simply by regenerating it to normalize/fix broken PDF.

So it won't work for PDF/A, but it might work to normalize a broken PDF?
