### ISSUE TITLE
human readable timestamp

### ISSUE THREAD

**Issue by rojomisin** [gotenberg/gotenberg#883]
logs currently use non-human readable format...
```{"level":"info","ts":1716341760.9513757,"logger":"api```

is there a flag to use iso8601?

some projects have it so you can do
```
  extraArgs:
    zap-time-encoding: iso8601
```

**Comment by gulien** [comment]
Hello @rojomisin 👋 

Currently not, unless a terminal is attached. See:
https://github.com/gotenberg/gotenberg/blob/9b1399c9d519151df658cc487b83af8abbc36f17/pkg/modules/logging/logging.go#L173
