### ISSUE TITLE
splitting Docker build into shell script stages for use in other scripts/containers

### ISSUE THREAD

**Issue by jrhy** [gotenberg/gotenberg#885]
HI! For those trying to run in an existing container, the Dockerfile is an invaluable source of what prerequisites and variables need to be set, but derived scripts need maintenance to keep in sync with the Dockerfile. Would you be opposed to having the Dockerfile stages split into separate shell scripts? That way, the same steps can be performed in other contexts, and they'll always be in sync with the release image. I'd be happy to submit a PR if this sounds OK to you.

**Comment by gulien** [comment]
Hello @jrhy 😄 ,

While I understand the idea behind your proposal, I believe it will end with more issues on my side (e.g., people trying to use the script in another context than Docker). 

Also, it won't leverage the caching system of Docker AFAIK.
