### ISSUE TITLE
8.7.0 userAgent form field (previously deprecated)

### ISSUE THREAD

**Issue by dcaraxes** [gotenberg/gotenberg#902]
Hi! I saw the new release 8.7.0, which added a new form field, but which was marked as Deprecated in release 8.0.0. Is this field not processed in versions 8.0.0 to 8.6.0?

**Comment by gulien** [comment]
It was not, indeed! In v7 I was using a mechanism that is no more available in v8. I found another way to override the default *User-Agent* header in 8.7.0.
