### ISSUE TITLE
Facing issue while converting docs to pdf for indian language hindi, tamil, telugu.

### ISSUE THREAD

**Issue by sauravsinha137** [gotenberg/gotenberg#908]
I am using gotenberg in our service to convert docx to pdf.  Text in my docs have indian language and few of them are bold, When converting to pdf texts are coming but those texts aren't coming as bold. Do we have a solution for this.
[test-gotenberg.docx](https://github.com/user-attachments/files/15886090/test-gotenberg.docx)
Attaching a sample docx file here

**Comment by gulien** [comment]
Hello @sauravsinha137,

No idea 🤔 maybe an issue with fonts? Are they available in the default Docker image?
