### ISSUE TITLE
CSS overflow and text alignment issues in PDF/A generation

### ISSUE THREAD

**Issue by RomainTFasst** [gotenberg/gotenberg#911]
### Description
When generating a PDF with Gotenberg via Chromium and enabling the PDF/A feature, CSS properties such as `overflow: hidden` and `text-align: justify` do not behave as expected. The text or item overflows beyond its container, and justified text is left-aligned instead.
### Steps to Reproduce
1. Use the following HTML and CSS code as a file:
```html
<!DOCTYPE html>
<html lang="fr">
<head>
  <title>Test PDF</title>
  <meta charset="utf-8">
  <style>
    .wrapper {
      width: 600px;
      height: 500px;
      border: 1px solid red;
      overflow: hidden;
    }
    .p1, .p2 {
      font-size: 12px;
      font-family: Arial, sans-serif;
      color: rgb(56, 26, 10);
      text-align: justify;
      border: 1px solid blue;
    }
    .p1 {
      width: 800px;
    }
    .p2 {
      width: 600px;
      border-color: green;
    }
    .line {
      width: 800px;
      height: 1px;
      background-color: black;
    }
  </style>
</head>
<body>
  <div class="wrapper">
    <p class="p1">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ac risus aliquam, tempor ante sit amet, vehicula erat. Vivamus tempus, diam et pellentesque condimentum, dolor lorem ornare dui, et mattis lorem elit nec neque. Suspendisse at nisl convallis, convallis lectus vitae, blandit velit. Aliquam tempus quam metus, ac efficitur arcu sagittis nec. Cras malesuada bibendum aliquam diam.</p>
    <p class="p2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ac risus aliquam, tempor ante sit amet, vehicula erat. Vivamus tempus, diam et pellentesque condimentum, dolor lorem ornare dui, et mattis lorem elit nec neque. Suspendisse at nisl convallis, convallis lectus vitae, blandit velit. Aliquam tempus quam metus, ac efficitur arcu sagittis nec. Cras malesuada bibendum aliquam diam.</p>
    <div class="line"></div>
  </div>
</body>
</html>
```
2. Generate a PDF with Gotenberg using the demo route with PDF/A option enabled, eg;
```
curl --location 'https://demo.gotenberg.dev/forms/chromium/convert/html' \
--form 'files=@"/path-to-file/index.html"' \
--form 'pdfa="PDF/A-1b"'
```
3. Observe the output where the text and line overflow, and text is not justified.
4. Retry without the PDF/A option, all is OK.
### Expected Behavior
- The text and line (div tag with "line" class name) should be contained within the .wrapper div without overflowing.
- The text should be justified as specified in the CSS.
### Actual Behavior
- The text and line overflow beyond the .wrapper div.
- The text is left-aligned instead of justified.
### Environment
Tested with v7.x, and 8.x via the demo route
### Screenshots
PDF/A enabled:
![image](https://github.com/gotenberg/gotenberg/assets/129773118/55df45f3-2b60-4222-a3cc-33b7aa902e48)
PDF/A disabled:
![image](https://github.com/gotenberg/gotenberg/assets/129773118/c2070ad2-bfa7-48db-ba6a-0d51c971ecbd)

**Comment by gulien** [comment]
Hello @RomainTFasst,

That's an issue with LibreOffice alas (Chromium convert to PDF, then LibreOffice to PDF/A). I cannot do much on my side. You should try https://bugs.documentfoundation.org/!

**Comment by RomainTFasst** [comment]
Thanks for your reply, for those who would like to follow this issue I have opened a bug report here: https://bugs.documentfoundation.org/show_bug.cgi?id=161778

**Comment by RomainTFasst** [comment]
Hi,
Following the answers of LibreOffice (see [here](https://bugs.documentfoundation.org/show_bug.cgi?id=161778)), isn't there a modification to consider on the generation of PDF/A on the Gotenberg side? According to them, "it's a bad idea to treat PDF as a format you re-open and re-save. PDF is an export-only format."
Any thoughts about this?

**Comment by gulien** [comment]
I guess they are right (in a LibreOffice point of view), but that’s the only straightforward way I found to handle PDF/A. 

That being said, softwares like Ghostscript offer a PDF -> PDF/A feature, so I guess the use case is not uncommon.

**Comment by RomainTFasst** [comment]
Hi,
Following the answers of LibreOffice (see [here](https://bugs.documentfoundation.org/show_bug.cgi?id=161778)), isn't there a modification to consider on the generation of PDF/A on the Gotenberg side? According to them, "it's a bad idea to treat PDF as a format you re-open and re-save. PDF is an export-only format."
Any thoughts about this?

**Comment by donovan-fournier** [comment]
Hi,
I faced the same issue recently.
Did you find a solution (I cannot  or any other way to perform the PDF to PDF/A transformation out of Gotenberg ?
Most of the tools that I found are commercial products and the integration of Ghostscript is not straightforward.
Thank you 🙏
