### ISSUE TITLE
Restart LibreOffice right away

### ISSUE THREAD

**Issue by MaxLap** [gotenberg/gotenberg#915]
Once `--libreoffice-restart-after` is reached. The next call to Gotenberg will be much slower due to the restarting happening.

This would be a lot less noticeable if the restarted was done right after the `--libreoffice-restart-after`-nth request.

Right now, if I have a request every 10 seconds. Then they take about ~200ms each, except once every 10 request, the request takes ~2000ms. With a change as proposed, The ~2000ms would never be seen and it would always take only ~200ms.

Personally, I don't see a reason for this to be a configuration and should just be the default. It seems beneficial in basically all cases. Thoughts?

I'd be willing to look into making a PR for this if you are interested.

**Comment by gulien** [comment]
Hello @MaxLap,

Indeed, that would be better. I did try to implement such a solution, but failed to build something stable enough. Most of the magic happens here: https://github.com/gotenberg/gotenberg/blob/main/pkg/gotenberg/supervisor.go.
That being said, under heavy load, restarting before or after is the same 😄
