### ISSUE TITLE
Numbers deformed converting html to pdf

### ISSUE THREAD

**Issue by BjornLenoir** [gotenberg/gotenberg#921]
### Discussed in https://github.com/gotenberg/gotenberg/discussions/852

<div type='discussions-op-text'>

<sup>Originally posted by **BLenoir10** April  5, 2024</sup>
Hi,

I've noticed some problems with converting html to pdf: for some reason the numbers 6 and 8 get a bigger font size than other numbers after conversion. Does anyone else experience this problem? Is there a way to avoid this from happening besides not using these specific numbers? 

So far, I tried things like using a different font (Arial) but that didn't fix it. So to be clear: the problem isn't with the HTML, everything renders just fine. After conversion the resulted PDF file shows this problem.

Here an example of the problem:

![image](https://github.com/gotenberg/gotenberg/assets/47782338/c651939f-2161-492d-94f9-ec1e1ad4bc2e)

</div>

**Comment by gulien** [comment]
Hello @BjornLenoir,

No idea what's happening 🤔 

> So to be clear: the problem isn't with the HTML, everything renders just fine.

Yep, but PDF generation is another beast lol it's not always 1:1 when it comes to rendering.

**Comment by gulien** [comment]
Hello @BjornLenoir,

Feel free to reopen this issue if anything new on your side. 

I did not find anything during my investigation, and I suspect a bug on the Chromium side 😕 not much I can do alas.
