### ISSUE TITLE
Can't get pdfua=true to work

### ISSUE THREAD

**Issue by lennartb-** [gotenberg/gotenberg#924]
Hi,

I'm trying to convert a (really simple, see attached) docx or odt document into a PDF/UA compatible PDF. I'm basically using the sample request from the [documentation](https://gotenberg.dev/docs/routes#pdfa-libreoffice):

```
curl --request POST https://demo.gotenberg.dev/forms/libreoffice/convert --header "Content-Type: multipart/form-data" --form files=@empty.docx --form pdfua=true -o out.pdf
```
(Using the public instance here, our internal instance has the same issue).

This returns a PDF, but is missing the PDF/UA metadata. We're using [PDF Accessibility Checker](https://pac.pdf-accessibility.org) to check if the PDF/UA identifier is set, but that fails:

![image](https://github.com/gotenberg/gotenberg/assets/5563601/22798700-65ea-4464-9e7f-08e3b95db6be)

Using the LibreOffice GUI to export the PDF with PDF/UA enabled works as expected. I've tried all other formats (i.e. `--form pdfa=PDF/A-2b` etc., but that doesn't change anything).

What am I doing wrong?

[empty.odt](https://github.com/user-attachments/files/16176838/empty.odt)
[empty.docx](https://github.com/user-attachments/files/16176840/empty.docx)

Edit:

I looked around in the sources a bit and comparing the part where [pdfua is passed to libreoffice](https://github.com/gotenberg/gotenberg/blob/45a9eca0cef90aed424c5c91506c603938854875/pkg/modules/libreoffice/api/libreoffice.go#L310) to the [available CLI parameters](https://help.libreoffice.org/latest/en-US/text/shared/guide/pdf_params.html), it looks like `PDFUACompliance=true` might be missing?

**Comment by gulien** [comment]
@lennartb- https://github.com/gotenberg/gotenberg/commit/d90e431b5b9bbb2b01b2505aeaeaa28d83f5caa1 adds the `PDFUACompliance` flag. However, during my testing with veraPDF, it did not change anything.

Once the https://github.com/gotenberg/gotenberg/actions/runs/9892139408 job is done (~1 hour), you may retry with `gotenberg/gotenberg:edge`.

**Comment by lennartb-** [comment]
@gulien Thanks! I'll try it, but it might be a couple of days.

I also played around with veraPDF, but could never get it to output anything sensible (to me) - I generated quite a lot of sample PDFs in all versions, with and without PDF/UA from LibreOffice and could never determine whether the flag was set or not.

**Comment by lennartb-** [comment]
That seemed to do the trick, at least with PAC and the PDF/UA identifier:

![image](https://github.com/user-attachments/assets/557f9aeb-467c-4699-882e-621b5c79527c)

Not an accessibility expert, but as far as I understand the PDF/UA flag only signals that the document itself _claims_ UA conformity. The actual conformity (what e.g. veraPDF validates) depends on a lot more, like content and formatting, which is not something the PDF producer/LibreOffice can "fix" during creation but requires that the author actually has their designed with accessibility in mind.

**Comment by gulien** [comment]
Thanks for the feedback! I guess it closes the issue 👍
