### ISSUE TITLE
Healthcheck failing. Need to restart service very often.

### ISSUE THREAD

**Issue by sauravsinha137** [gotenberg/gotenberg#940]
Hey @gulien 
I am using this to convert docx to pdf. It works fine normally but sometimes API fails with error :
**convert to PDF: process restart before task: restart process: start process: LibreOffice socket not available: context deadline exceeded**

I have provided enough reosources to this instance, even request is quite below max limit.  After this error health check api fails it starts responding with 503. We need to manually restart this service to fix this. Can you please help in resolving this issue.

**Comment by gulien** [comment]
Hello @sauravsinha137,

You should configure your Docker orchestrator so that it automatically restarts your container on health check failure.

For instance, with Docker Compose: https://www.paulsblog.dev/how-to-successfully-implement-a-healthcheck-in-docker-compose/

**Comment by sauravsinha137** [comment]
hey @gulien  i understand we need to restart in case of health check failure and we have already implemented. I want to understand why these failure happens, so that i can minimise restarts. Currently i need to restart container  1-2 time very hour.

**Comment by gulien** [comment]
You have some options to mitigate this issue:

* Increase the LibreOffice start timeout with `--libreoffice-start-timeout`.
* Increase the number of conversions before a restart with `--libreoffice-restart-after`.
* Increase the number of Gotenberg instances?


That being said, I don’t have a definitive answer about the why. On the demo instance, it almost never happens  🤷‍♂️
