### ISSUE TITLE
Application stopped working with exit status 5

### ISSUE THREAD

**Issue by hahalulu** [gotenberg/gotenberg#941]
`{"level":"error","ts":1723101579.8591974,"logger":"api","msg":"convert to PDF: supervisor run task: convert to PDF: unix process error: wait for unix process: exit status 5","trace":"55945f36-bd68-4f1e-be97-34209943596b","remote_ip":"10.244.248.201","host":"gotenberg.eapp:3000","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"Apache-HttpClient/4.5.14 (Java/11.0.16)","status":500,"latency":2482148194,"latency_human":"2.482148194s","bytes_in":29996,"bytes_out":21}`
[
[gotenberg.log](https://github.com/user-attachments/files/16620817/gotenberg.log)
](url)
After run few days. I got some error logs, and the application stopped working. It will works fine if I restart application.

**Comment by gulien** [comment]
Hello @hahalulu,

You should setup a health check to automatically restart your Gotenberg instance. LibreOffice may struggle after some time, even with auto restart.
