### ISSUE TITLE
PDF Headers rendering wider than expected on v8.9.0+

### ISSUE THREAD

**Issue by Flambe** [gotenberg/gotenberg#942]
Reproduction repo: https://github.com/Flambe/gotenberg-header-rendering-issue

In v8.8.1 of Gotenberg the header does not extend the page width as expected. Since v.8.9.0 the header is too wide, even though the css width is explicit in stating that the page should only be 210mm in width

v8.8.1: working
![image](https://github.com/user-attachments/assets/75573855-db90-4e79-879b-fd1761a4a5ca)

v8.9.0: not working
![image](https://github.com/user-attachments/assets/2352fa79-2f58-421e-a4d3-99875607241e)

**Comment by gulien** [comment]
Hey @Flambe!

It’s not the first time a « bug » like that is introduced in Chromium.

I’m on vacation, could you help me by printing the version of Chromium in each Gotenberg versions? `chromium —version`

I suspect a bug (or a fix lol) from Chromium.

**Comment by Flambe** [comment]
That seems to be a running theme haha

v8.8.1: `126.0.6478.182`
v8.9.0: `127.0.6533.72`

And no worries, I've just pinned our side to v8.8.1 at the moment. Enjoy your vacation!

**Comment by gulien** [comment]
Thanks! 😁

Totally missed the version change on `amd64` for Chromium! 

I did not find anything yet on the Chromium bug tracker.  If you want to update the Gotenberg image, you’ll have to find workarounds with your content to make it work again 😅

**Comment by Flambe** [comment]
Thanks for checking!

The issue seems to be with the wrapping `<div>` in the header (removing that fixes the issue as well) but unfortunately I don't have access to that in our actual header. I'll have to give it a more in depth look some time soon so we can upgrade Gotenberg!
