### ISSUE TITLE
Gotenberg add white border for some paperwidth and height

### ISSUE THREAD

**Issue by demobiel** [gotenberg/gotenberg#943]
hi

We are using Gotenberg 8.5.0 (Docker image), and run into a small issue.

We have the following HTML document: 

```<html>
<style>
    html, body {
        margin: 0;
        padding: 0;
        background-color: green;
        height:100vh;
    }

    @page {
        margin: 0;
        padding: 0;
    }

</style>

<div class="big">
    <div class="small"></div>
</div>
</html>
```

When we try to render this via gotenberg, for some page sizes it adds a white border (1px width?) to the right and bottom of the page.

For example
````
 curl \
--request POST http://localhost:3000/forms/chromium/convert/html \
--form index.html=@index.html \
--form paperHeight=100px \  
--form paperWidth=100px \  
--form printBackground=false \
--form marginTop=0 \
--form marginBottom=0 \
--form marginLeft=0 \
--form marginRight=0 \
-o render_100.pdf
`````
returns a PDF with a white pixel (see render_100.pdf)
[render_100.pdf](https://github.com/user-attachments/files/16726439/render_100.pdf)

However the following command just works fine, and renders a pdf as we want (see render_101.pdf)
[render_101.pdf](https://github.com/user-attachments/files/16726438/render_101.pdf)

````
 curl \
--request POST http://localhost:3000/forms/chromium/convert/html \
--form index.html=@index.html \
--form paperHeight=101px \  
--form paperWidth=101px \  
--form printBackground=false \
--form marginTop=0 \
--form marginBottom=0 \
--form marginLeft=0 \
--form marginRight=0 \
-o render_101.pdf
`````

What is weirder is that for 100.1px it also renders fine. What can cause this? We are not looking for a fix, but an explanation why this is happening, so we can work around the "bad numbers" :)

Kind regards

Andries

**Comment by demobiel** [comment]
we notice that those pixels changes when using gotenberg 8.5.0 or gotenberg 8.8.0 which is even weirder for us :)

I guess this is a chromium bug , but not sure...

**Comment by gulien** [comment]
Hey @demobiel 👋 

That’s certainly a change on the Chromium side, maybe an issue has been resolved or the engine has been updated somehow in version 127 😅

For a more consistent result, you may use `preferCssPageSize=true` and set the page size via CSS. Not sure it will do anything though (it might just reproduce the same behavior).
