### ISSUE TITLE
Feature request: HEAD support for Health endpoint

### ISSUE THREAD

**Issue by omni-htg** [gotenberg/gotenberg#946]
Hey gulien !

Recently, while trying to set up a Docker `HEALTHCHECK` against the `/health` route, I stumbled upon the option to use `HEAD` instead of `GET` for it (ie. `curl -I`) -- unfortunately, it is not allowed in the current latest (8.9.1).
As you have probably guessed by now, the basic idea is to just request the Status Code and base a decision off that.

If interested, I could also try to tackle it as a "first and simple" contribution.

On a completely different note, I have an extra question:
Is it currently possible to override a LibreOffice's _Page Property_ on initialization (using one of the gotenberg flags)?
For example, I'd like to set `skipEmptyPages` to `true` for all requests (maybe except when the Form entry is there, but that's secondary).

Thanks a lot!

Regards.

**Comment by gulien** [comment]
Hello @omni-htg! 👋

Of course, feel free to try a PR! I’ll review it 😉

Regarding your second question, I think it’s better to handle « defaults » on the client side. For instance, if a user post an issue, it’s easier for me to ask for the failing request and replay it on the demo instance than to setup a Gotenberg instance with the « defaults » from the user. 

That being said, I will provide more sensible defaults for the next Gotenberg major version.

**Comment by omni-htg** [comment]
Will try! Thanks for the encouragement!

> I think it’s better to handle « defaults » on the client side

Oh don't get me wrong, I fully agree, I was curious if that sort of behaviour was available in the current releases, as it could prove useful for some usecases.

> I will provide more sensible defaults for the next Gotenberg major version.

IMHO I'd say it's good that you follow LibreOffice's defaults, as it makes it easier to correlate 1-1.
Which is why I'd perhaps be more welcoming of being able to easily override them to my tastes on startup / configuration than them being different from LO's behaviour.

---

I'll take the chance to drop one more question:
Is all the information that you have available about `convert to PDF: unix process error: wait for unix process: exit status 5` available in your previous responses, like #850 ?
Have things changed / improved since?
(Also please let me know if I should move this to a Discussion instead).
Thanks!

**Comment by gulien** [comment]
Dunno regarding the issue mentioned in #850 🤷‍♂️ those kind of issues are quite random; it depends on a lot of parameters that I may not have a hand on (files sent etc.). But if you have more information please consider adding them in the mentioned thread!

**Comment by omni-htg** [comment]
Unfortunately it is the _lack_ of information that makes me ask!
In my experience I can test against multiple files and everything is alright, only to then see this weird error once hosted -- classic "it works on my machine", I guess.

That's why I'd like to at least get a grasp of the reason behind it and whatnot.
So far my understanding is it's related to LibreOffice, and that's why the "recycle" is there for?

**Comment by gulien** [comment]
The _recycle_ is mostly for avoiding memory leaks overtime. 

The problem with #850 is that it is not caught by the health check (e.g., LibreOffice is responding as expected on a given TCP port).

**Comment by gulien** [comment]
@omni-htg I went ahead and added the HEAD method 😄 

`gotenberg/gotenberg:edge` is available with this feature.

**Comment by omni-htg** [comment]
My apologies @gulien , I did not intend to rush you into solving it, yet -- thank you so much for taking the time!
