### ISSUE TITLE
Unable to start the docker image in google cloud run

### ISSUE THREAD

**Issue by Fank** [gotenberg/gotenberg#950]
I just used the `gotenberg/gotenberg:8-cloudrun` image and started it:

```
  _____     __           __               
 / ___/__  / /____ ___  / /  ___ _______ _
/ (_ / _ \/ __/ -_) _ \/ _ \/ -_) __/ _ '/
\___/\___/\__/\__/_//_/_.__/\__/_/  \_, / 
                                   /___/
A Docker-powered stateless API for PDF files.
Version: 8.9.2
-------------------------------------------------------
[SYSTEM] modules: api chromium exiftool libreoffice libreoffice-api libreoffice-pdfengine logging pdfcpu pdfengines pdftk prometheus qpdf webhook 
[SYSTEM] chromium: Chromium ready to start
[SYSTEM] libreoffice-api: LibreOffice ready to start
[SYSTEM] prometheus: collecting metrics
[SYSTEM] pdfengines: exiftool libreoffice-pdfengine pdfcpu pdftk qpdf
[SYSTEM] api: server listening on port 3000
Default STARTUP TCP probe failed 1 time consecutively for container "gotenberg-1" on port 8080. The instance was not started.
```

[Listening for requests on the correct port (services)](https://cloud.google.com/run/docs/container-contract#port):
> By default, requests are sent to 8080, but you can [configure Cloud Run](https://cloud.google.com/run/docs/configuring/services/containers#command-line) to send requests to the port of your choice. Cloud Run injects the PORT environment variable into the ingress container.

I would recommend to listen to the `PORT` environment variable by default.

**Comment by gulien** [comment]
You may setup this behavior with the flag `--api-port-from-env=PORT`.

 But you're right, it's not clear in the documentation and I may setup default flags.

**Comment by Fank** [comment]
Thanks for the update.
Using following command i was able to boot up the instance:
```console
gcloud run deploy gotenberg-prod
--image=gotenberg/gotenberg:8-cloudrun
--args=gotenberg
--args="--api-port-from-env=PORT"
```

If `--args=gotenberg` is not provided i will run into
```console
[FATAL tini (2)] exec --api-port-from-env=PORT failed: No such file or directory
```

**Comment by Fank** [comment]
@gulien If you update the documentation I would suggest to use `--memory=1Gi` for a better experience, because the default is `512Mi`, which caused some issues.

Here the metric of our service running in production:
<img width="2005" alt="image" src="https://github.com/user-attachments/assets/569ac132-61f0-4b8c-85cd-bf6a907a4c53">

I was running with default first, then I ran into memory issues.
I increased it to `1Gi` since then the memory usage is 55% on average, sometimes peaks to 60%.

*And thank you for this smooth plug and play experience. We replaced a chrome headless using CDP with gotenberg, and it runs so smooth*

**Comment by gulien** [comment]
Thanks for the heads up @Fank! The 512 Mo requirement seems to really depend on the type of infrastructure. I'll add it to the documentation 👍 

> And thank you for this smooth plug and play experience. We replaced a chrome headless using CDP with gotenberg, and it runs so smooth

Glad you appreciate, and thanks for the feedback! Most often than not, I have no idea how users are experiencing with Gotenberg 😄

**Comment by gulien** [comment]
@Fank I have improved the documentation regarding Cloud Run based on your feedbacks 😉 

I think its best to let the users add the flags themselves instead of putting default flags in the image. It's less *magic*, but it eases the process of adding more flags if needed (e.g., not overriding default ones with the risk that their containers do not work anymore).
