### ISSUE TITLE
URL convert render empty PDF on error

### ISSUE THREAD

**Issue by eMerzh** [gotenberg/gotenberg#959]
Hello, thanks for this project :) 

it seems that for some reason if you try to render an URL, but the site is not reachable (ie not route to host)

then it render an empty pdf instead of an error

repro :
```
curl --request POST \
  --url http://localhost:9995/forms/chromium/convert/url \
  --header 'Content-Type: multipart/form-data' \
  --form url=http://19226565944.com
```
will give you an empty pdf 

version 8.9.1

**Comment by gulien** [comment]
Hello @eMerzh 👋 

Your issue looks similar as https://github.com/gotenberg/gotenberg/issues/913. 

Could you enable the debug logging level and find a line with a similar error as:

```
gotenberg-1  | {"level":"debug","ts":1719471864.3495355,"logger":"chromium.browser","msg":"<- {\"method\":\"Network.loadingFailed\",\"params\":{\"requestId\":\"7458B3B7335C136ABA12568DEFD5A756\",\"timestamp\":141894.928028,\"type\":\"Document\",\"errorText\":\"net::ERR_CONNECTION_REFUSED\",\"canceled\":false},\"sessionId\":\"EB1CF54DB4678427B493F65D718BCE0D\"}"}
```

I guess it's an equivalent  of `net::ERR_CONNECTION_REFUSED`.

**Comment by eMerzh** [comment]
@gulien Thanks for your quick reply

is seems to be similar but not the same 😬 

gotenberg-1              | {"level":"debug","ts":1725614648.191612,"logger":"chromium.browser","msg":"<- {\"method\":\"Network.loadingFailed\",\"params\":{\"requestId\":\"DD60A1D1F4A2870C93482F5138C4B509\",\"timestamp\":60510.551307,\"type\":\"Document\",\"errorText\":\"net::ERR_NAME_NOT_RESOLVED\",\"canceled\":false},\"sessionId\":\"9FC4276ADA9E533A551F5AE86AD43D68\"}"}

**Comment by gulien** [comment]
@eMerzh `gotenberg/gotenberg:edge` should be available within ~1 hour with the fix!

**Comment by eMerzh** [comment]
yeesss, it seems to 400 now... thanks 👍
