### ISSUE TITLE
office to pdf language

### ISSUE THREAD

**Issue by juanpvs** [gotenberg/gotenberg#97]
## Expected Behavior
I have a docx file with some combination fields. I created the docx in Spanish, but when I convert it to pdf it returns to me in English in this case it is a date, is it possible to specify the language? I uploaded the example docx
 
[mergefields.docx](https://github.com/thecodingmachine/gotenberg/files/3419286/mergefields.docx)

**Comment by gulien** [comment]
Hello @juanpvs 

Sorry for the delay. Nothing exists right now for this use case. Maybe it is possible to set the locale of the LibreOffice Instances.

**Comment by tobwen** [comment]
@juanpvs Maybe you have to add this package https://packages.debian.org/buster/libreoffice-l10n-es. But you need to rebuild the Dockerfile on your own.

**Comment by leMaik** [comment]
Stumbled upon this today (needed spreadsheets with german locale for date and number formatting). Here's a `Dockerfile` that adds the german locale, the resulting images works just like gotenberg (but german). Adjust as needed for other languages.

```dockerfile
FROM thecodingmachine/gotenberg:6
USER root

RUN apt-get update &&\
    apt-get --no-install-recommends -t buster-backports -y install libreoffice-l10n-de &&\
    rm -rf /var/lib/apt/lists/*

RUN sed -i '/de_DE.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen
ENV LANG de_DE.UTF-8  
ENV LANGUAGE de_DE:en  
ENV LC_ALL de_DE.UTF-8 

USER gotenberg
```

**Comment by gulien** [comment]
Thanks @leMaik for the input.

**Comment by gulien** [comment]
Documentation udpated.
