### ISSUE TITLE
503 Service Unavailable with pdf file conversion under libreoffice/convert

### ISSUE THREAD

**Issue by jankrikava** [gotenberg/gotenberg#970]
We just encoutered a **503 Service Unavailable** error, when uploading a certain set of pdf files (see below) to Gotenberg (Route _/forms/libreoffice/convert_). @gulien Can you please try reproducing this error for a root cause analysis?

**Docker versions tested**
8.9.2 (latest)
7.7.2

**JHOVE Results (pdf validation check)**
![JHOVE Result blurred](https://github.com/user-attachments/assets/d76eb972-1f08-4c14-b107-89f415b55a92)
ℹ [https://github.com/openpreserve/jhove](https://github.com/openpreserve/jhove)

**Payload PDF files:**
http://decapoda.nhm.org/pdfs/25900/25900-001.pdf
http://decapoda.nhm.org/pdfs/25900/25900-004.pdf

**Comment by gulien** [comment]
Hello @jankrikava,

Did you try any of https://gotenberg.dev/docs/troubleshooting#timeouts-libreoffice?

**Comment by gulien** [comment]
Increasing the `--api-timeout` did the trick on my side!

**Comment by jankrikava** [comment]
Thanks @gulien, worked fine for us. 

The converted file looks somehow corrupted with doubled text. Do you have an hint for us here? 🙂
![Error Conversion](https://github.com/user-attachments/assets/924b3f83-bb8d-4c24-8b7b-ef5ea273eb5c)

**Comment by gulien** [comment]
No, alas I think it's a side effect of "re-converting" a PDF file with LibreOffice. Maybe playing with [those form fields](https://gotenberg.dev/docs/routes#images-libreoffice) may do the trick, but I don't really believe it 😄
