### ISSUE TITLE
Cant load files if <base href="/"> set in html in forms/chromium/convert/html

### ISSUE THREAD

**Issue by Vovcharaa** [gotenberg/gotenberg#973]
If index.html contains `<base href="/"> ` Chromium tries to load file from wrong place.
I believe this need to be mentioned somewhere in docs at least.

Curl:
```
curl --location 'http://localhost:3000/forms/chromium/convert/html' \
--form 'files=@"path/to/index.html"' \
--form 'files=@"path/to/header.jpg"'
```

Log:
```
{"level":"warn","ts":1726494803.706587,"logger":"api.formschromiumconverthtml","msg":"'file:///header.jpg' matches the expression from the denied list: value filtered","trace":"3f647546-d8be-4b74-b707-b5907e14c6f9"}
```

Gotenberg Version: 8.9.2

**Comment by gulien** [comment]
Thanks @Vovcharaa!

Note that you may override this behavior by setting the flag  `--chromium-deny-list` with an empty value or a better regex. Be aware that overriding the default value may allow one to print unwanted local files.

**Comment by Vovcharaa** [comment]
@gulien That won't help because request files are not saved in the root folder of the container. This element just breaks path resolution for any relative href.

**Comment by gulien** [comment]
🤦‍♂️ yes indeed
