### ISSUE TITLE
Feature Request: Benchmarking between releases

### ISSUE THREAD

**Issue by pieterocp** [gotenberg/gotenberg#981]
For the sake of performance regression / as a way of consistently comparing different releases, it would be nice to build out a consistent benchmark using the same setup/system. Run a set of consistent file conversions, check the outputs with a visual diff afterwards/compare things like time taken, memory usage, etc.

But I'd wholly understand if this is beyond the scope of the confides of this project, and more something best to live outside of it, maybe as a separate repo to reproduce-able generate a suite of runs to benchmark for differing releases. If someone else has/is doing this and I'm as blind as a bat, then appreciate any prior examples.

(happy to give it a go myself since for my use case, speed is nice.)

**Comment by gulien** [comment]
Hello @pieterocp 👋 

I use the demo instance to monitor such things. It handles 30k requests per week, so it gives me a pretty good overview. The performance has been pretty stable over time, so I did not find the need for extra testing.

if you still want to try on your side, you may check https://github.com/gotenberg/gotenberg/tree/6.4.4/loadtesting. It might require some updates but it’s a good starting point 😉
