### ISSUE TITLE
Scale doesn't change the size of images

### ISSUE THREAD

**Issue by dave-yotta** [gotenberg/gotenberg#997]
Setting scale [here](https://gotenberg.dev/docs/routes#page-properties-chromium) to less than 1.0 scales the rendering of text etc, but the images remain the same size on the produced pdf.

**Comment by gulien** [comment]
Hello @dave-yotta 👋

I’m directly using the Chromium Devtool Protocol for this feature, so there isn’t much I can do on Gotenberg side to change this behavior.

I guess you could somehow tweak this with CSS or else, but that out of the scope of this project. However, if you find anything, please feel free to reopen this issue!
