### ISSUE TITLE
Feature: Allow accepting HTML as a string in a POST request body 

### ISSUE THREAD

**Issue by NGorco** [gotenberg/gotenberg#999]
Hi! 

First of all, thanks to amazing team and amazing software. It's a great tool. It solved so much problems for my team.

## Context
We are looking to use Gotenberg to generate reports from HTML string, not only from HTML files. 

## Problem
It's tricky to push HTML string from server to Gotenberg's API as a file. Requires a lot of boilerplate for no specific reason.

## Proposal
Add another endpoint that will accept pure HTML string. Doesn't matter body field as a json or just pure raw body text.

Thanks.

**Comment by gulien** [comment]
Hey @NGorco 👋

Thanks for the kind words.

Regarding your issue, it’s actually quite simple to do from the client side. For instance, this is how I do it in the PHP client:

```php
Gotenberg::chromium($apiUrl)
    ->pdf()
    ->html(Stream::string('<html><body><p>Hello, world!</p></body></html>'));
```

Here is another example in node.js:

```js
const htmlBuffer = Buffer.from('<html><body><p>Hello, world!</p></body></html>')
const formData = new FormData()
formData.append('files', htmlBuffer, {
    filename: 'index.html'
})
```

I don’t want to create another endpoint as I think it not worth the hassle. The solution is quite easy to implement from the client side, whatever the language.

**Comment by NGorco** [comment]
Yup, we are doing exactly what you mentioned with Node.js. But for me it feels controversial to push string as a file, while task of an API (in general) is to generate PDF from a string, not from HTML file.

What if I'd put a PR for review? I think it would simplify setup and make it more clear, since pushing string with POST request is a most basic concept it could possibly be.

**Comment by gulien** [comment]
Problem is you will start with the `index.html` file, then some people will ask for being able to send assets as string too and I will end up with an unmaintainable code on the server side.

`multipart/form-data` requests are natively able to send files, and using a buffer/stream to create a form file is a totally valid use case. 

I really don’t see the substantial gains a new route or form field could add comparing to the current solution. And to be totally honest, I think there is none 😅
